### ISSUE TITLE
Vendor Payments dashboard may appear empty

### ISSUE THREAD

**Issue by dd32** [WordPress/wordcamp.org#1002]
**Describe the bug**

In the network admin, there's a Vendor Payments dashboard that lists pending payments for WordCamps, this is used to ensure that we can pay things out appropriately that needs paying.

However, due to [the implementation of how it queries the data](https://github.com/WordPress/wordcamp.org/blob/bf395f67aa85e3058605a6e183fde016f5d0bf1f/public_html/wp-content/plugins/wordcamp-payments-network/includes/payment-requests-dashboard.php#L87-L107) it's possible for users of this dashboard to encounter a blank dataset.

The implementation, on a cron task, does..
 1. Truncates the table
 2. Queries each site for payments
 3. Inserts into the aggregate table

When you view the page at any point while the cron task runs, you'll encounter an empty dataset.

**Comment by iandunn** [comment]
Mitigated by #1004

**Comment by iandunn** [comment]
Actually, #1004 didn't fix it (although it didn't hurt anything either). #1005 should fix it.
