### ISSUE TITLE
Add nav breadcrumbs to Events child theme

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#1014]
The Events site uses the global header/footer, but doesn't have a link in either of them. If someone is on one of the landing pages (see #1007), then won't have any link to go to the events.wordpress.org homepage, only w.org. That may confuse visitors.

We could add a nav breadcrumb like the News theme has on pages like https://wordpress.org/news/2023/08/lionel/

**Comment by ryelle** [comment]
There's a local navigation block in wporg-mu-pluigns, which handles the breadcrumbs in the About & Download subpages, that could be used here? Here's [an example of how it's used on download](https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/themes/wporg-main-2022/patterns/_nav-download.php).

![Screen Shot 2023-08-22 at 15 54 22](https://github.com/WordPress/wordcamp.org/assets/541093/31753e59-e031-4c11-a7a1-d5b65ec1d877)

Also see https://github.com/WordPress/wporg-mu-plugins/issues/465, it's still evolving but if you use the block hopefully it should inherit those improvements 🙂

**Comment by iandunn** [comment]
That looks perfect, thanks 👍🏻
