### ISSUE TITLE
Prevent nulling past WordCamp site with Site Cloner

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/wordcamp.org#1040]
Looks like organisers can use Site Cloner to clone sites from the new WordCamp to the previous WordCamp (i.e. 2024 -> 2023) and null the site / cause lots of issues for past event sites that would be otherwise kept as-is for archive purposes.

Reported on https://wordpress.slack.com/archives/C08M59V3P/p1694606665478859

**Expected behavior**

Cloning a site for an event that is ongoing or in the past shouldn't be allowed.

Tho not sure what pointer we should use for checks on this, since tracker status can be "in schedule", but the organising team is still developing the site 🤔

Also, labelling this as low prio since the linked Slack discussion is the first time I'm hearing something like this happening.

**Comment by timiwahalahti** [comment]
@iandunn fixed in #1047

**Comment by iandunn** [comment]
Doh, I forgot about this issue, thanks!
