### ISSUE TITLE
Group landing page events by type

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#1045]
See https://wordpress.slack.com/archives/C05JYJJRNKB/p1695113875234049?thread_ts=1694555515.164809&cid=C05JYJJRNKB

On the home page, create a column for each type of event, so that NextGen events are more obvious.

We'll need to figure out a way to make that work on mobile, though, since some of the columns will be very long, and you'd have to scroll a long ways to get to the next type.

**Comment by StevenDufresne** [comment]
This was finished indirectly.
