### ISSUE TITLE
Page Not Found on "use the new unified application" under Handbooks page- https://make.wordpress.org/community/handbook/

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/wordcamp.org#1070]
**Describe the bug**

**To reproduce**

1. Go to [https://make.wordpress.org/community/handbook/](https://make.wordpress.org/community/handbook/) Top section "Apply to be an Event or Program Supporter" text & scroll and you can see the sidebar "In-person Events are Back" section.
2. Click on [the new unified application](https://make.wordpress.org/community/handbook/community-deputy/new-supporter-orientation-script/join-the-community-supporter-program/)

**Screenshots**
![image](https://github.com/WordPress/wordcamp.org/assets/23701579/5f29f649-b53f-438c-9480-037214960227)
![[image](https://make.wordpress.org/community/)](https://github.com/WordPress/wordcamp.org/assets/23701579/50c4ef96-4442-44c1-95c9-c5706691fac9)

**Comment by devinmaeztri** [comment]
Hello @sumitsinghwp! Thanks for reporting. It's fixed now. :)

**Comment by sumitsinghwp** [comment]
Thank you so much for a quickly fixed @devinmaeztri

**Comment by sumitsinghwp** [comment]
I am still able to see 404 here - Apply to be an [Event or Program Supporter](https://make.wordpress.org/community/handbook/community-deputy/new-supporter-orientation-script/join-the-community-supporter-program/).
https://make.wordpress.org/community/handbook/community-deputy/new-supporter-orientation-script/join-the-community-supporter-program/

**Comment by timiwahalahti** [comment]
I believe this was resolved.
