### ISSUE TITLE
Page Not Found on "use the new unified application" under Handbooks page- https://make.wordpress.org/community/handbook/contributor-day/

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/wordcamp.org#1071]
Describe the bug

To reproduce

Go to https://make.wordpress.org/community/handbook/contributor-day/ page
Click on [Theme Review Team](https://make.wordpress.org/themes/handbook/about/getting-started-at-a-contributor-day/)
See error - redirection on 404 page.
Screenshots
![image](https://github.com/WordPress/wordcamp.org/assets/23701579/0406b6ba-cde7-4479-b921-b527b0e8fb5a)

**Comment by timiwahalahti** [comment]
Updated the link, thanks @sumitsinghwp!
