### ISSUE TITLE
Sessions Block: Should non-"Regular" sessions be included?

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#109]
There are currently two types of sessions: "Regular" and "Break, Lunch, etc.". In the old `[sessions]` shortcode, the non-regular session posts were excluded from the query.

Right now in the Sessions block, the PHP renderer excludes these sessions as well, but the backend JS UI does not. We need to decide which way to go, and/or create a setting for the block that toggles these non-"Regular" sessions on/off.

My inclination would be to omit them for now, and if people ask for a way to include them, we can add the toggle, with the default value still being "off".

**Comment by iandunn** [comment]
I agree, I don't see a use case for including them in the front or back ends of that block.

**Comment by hlashbrooke** [comment]
Agreed - keep the same functionality as the shortcode and don't display breaks, etc. in the block.

**Comment by coreymckrill** [comment]
Fixed via the following commits:

* https://meta.trac.wordpress.org/changeset/8755
* https://meta.trac.wordpress.org/changeset/8756
* https://meta.trac.wordpress.org/changeset/8757
