### ISSUE TITLE
Radio buttons value is hard to read on Incident Report page

### ISSUE THREAD

**Issue by harshgajipara** [WordPress/wordcamp.org#1105]
## Describe the bug
Radio buttons are hard to read on the "Incident Report" form on page (https://central.wordcamp.org/incident-report/). 

##  Steps to reproduce the behavior:
- go to https://central.wordcamp.org/incident-report/
- go to Was a police report filed field 
- you will able to see the issue

## Screenshot: 
![before_patch](https://github.com/WordPress/wordcamp.org/assets/60835353/2807bad7-8f2d-4985-9d77-4942798b5994)

## Expected behavior
- it should be visible properly & easy to read.

it should show like this: 
![after-patch](https://github.com/WordPress/wordcamp.org/assets/60835353/bca64f87-ce23-49f0-8b92-19c2f1949083)

## Solution: 
After Applying Below CSS Issue will be resolved

```
.contact-form .grunion-radio-options label span {
    opacity: 1 !important;
}
```

**Comment by iandunn** [comment]
Thanks! This is fixed in #1106, but that won't be deployed until next week.
