### ISSUE TITLE
Events: Landing page performance

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wordcamp.org#1128]
Current Lighthouse score

![Screenshot 2023-12-07 at 10 22 13 AM](https://github.com/WordPress/wordcamp.org/assets/1017872/aff78b3b-4e5b-407f-b7bc-2bee442b2e96)

Key problems:

![Screenshot 2023-12-07 at 10 22 33 AM](https://github.com/WordPress/wordcamp.org/assets/1017872/d313793e-f0ac-4dcb-81f0-482a4b92eb9e)

**Comment by adamwoodnz** [comment]
Converting images to webp will help

**Comment by StevenDufresne** [comment]
>Converting images to webp will help

I turned on [JetPack site acceleration](https://jetpack.com/support/site-accelerator/?site=events.wordpress.org) which should convert to WebP. I see it working on `/organize-and-event` but not on the homepage. Not sure why yet.

What are the acceptance criteria for this ticket? As in, when can we close it?

**Comment by pkevan** [comment]
I guess some of this was probably down to the page not being live as such, a quick reference in lighthouse shows a page speed of 86 (logged out). 

![Screenshot 2023-12-12 at 10 19 30](https://github.com/WordPress/wordcamp.org/assets/2290623/d981eeb8-e669-41ba-9064-b3678ae801dd)

I'll update the lighthouse cron crawler with the current URL (without `?preview`).

**Comment by adamwoodnz** [comment]
> I guess some of this was probably down to the page not being live as such, a quick reference in lighthouse shows a page speed of 86 (logged out).

Yeah I expected a bit of a bump once all the live infrastructure was in place, that's great.

**Comment by adamwoodnz** [comment]
> What are the acceptance criteria for this ticket? As in, when can we close it?

I think we're done 🙂

**Comment by StevenDufresne** [comment]
I'm still confused as to why the JetPack gallery is not converting the image to WebP. I wonder if they need to be served from the media library? Probably the case because the `/organize-an-event` page serves the feature image as WebP but not the one linked to the file system.

[Reference](https://jetpack.com/support/site-accelerator/)
> It only acts on images in posts and pages, as well as featured images/post thumbnails via the [image_downsize](https://developer.wordpress.org/reference/functions/image_downsize/) filter. Examples of WordPress functions using the image_downsize filter: [the_post_thumbnail_url](https://developer.wordpress.org/reference/functions/the_post_thumbnail_url/), [get_the_post_thumbnail](https://developer.wordpress.org/reference/functions/get_the_post_thumbnail/), [get_the_post_thumbnail_url](https://developer.wordpress.org/reference/functions/get_the_post_thumbnail_url/), [wp_get_attachment_image](https://developer.wordpress.org/reference/functions/wp_get_attachment_image/), [wp_get_attachment_image_src](https://developer.wordpress.org/reference/functions/wp_get_attachment_image_src/)
