### ISSUE TITLE
Events: Update meetup.com link

### ISSUE THREAD

**Issue by angelasjin** [WordPress/wordcamp.org#1137]
On https://events.wordpress.org/, under "Where all WordPress contributors meet", there are a number of links to Central, Do_action, etc. 

The Meetup.com link currently goes to https://www.meetup.com/. Can it be updated to go to https://www.meetup.com/pro/wordpress/ instead?

**Comment by dorsvenabili** [comment]
Oh yes! That was a typo. The link @angelasjin has shared is the right one. Thank you both! :)
