### ISSUE TITLE
Events: Breakpoint change for a cleaner cover

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wordcamp.org#1138]
I noticed that cover area changes from Mobile to Desktop, as per [design documentation](https://www.figma.com/file/jdMk5ssz2Av7KFfEaeK7de/Events?node-id=1617%3A13314&mode=dev) when viewport reaches `782px`. This makes the map and events table to look tight

| Cover area | Events table |
|:---|:---|
| ![Screenshot of cover area](https://github.com/WordPress/wordcamp.org/assets/895819/a863eb69-2d87-4c49-a413-4cc572aef205) | ![Screenshot of upcoming events area](https://github.com/WordPress/wordcamp.org/assets/895819/c68aad2d-bfd6-4547-b395-1a55d7f0f89c) |

## Proposal

The whole page may look cleaner with two changes:

- [x] Keep the Mobile's vertical distribution of cover area (Heading, sub text, and map) until it reaches the last breakpoint of `959px`, (from what I see in Chrome's inspector), and change it to horizontal from `960px` to beyond.

- [x] Place location, date, and time labels horizontally in a single line, as the [small variant of event item component](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=3721%3A1117&mode=dev) (image attached).

![Event item in its small variant](https://github.com/WordPress/wordcamp.org/assets/895819/2bb91902-3fd7-4fd9-ab04-feae23bdba0b)

**Comment by outdoor2kode** [comment]
> Place location, date, and time labels horizontally in a single line, as the [small variant of event item component](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=3721%3A1117&mode=dev) (image attached).

Is this also applicable only when the width is less than `960px`?

**Comment by fcoveram** [comment]
> Is this also applicable only when the width is less than `960px`?

Yes. I forgot to add that, thanks for asking.
