### ISSUE TITLE
Events: Sticky local nav in Organize an event

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wordcamp.org#1139]
While in home and Upcoming events pages local nav remains sticky when scrolling down, in Organize an event the component does not.

### To reproduce

1. Go to "Organize an event" page from a laptop
2. Scroll down the page
3. See the error

### Expected behavior

Local nav should remain sticky in all pages

### Screenshots

![Screenshot of Organize an event page](https://github.com/WordPress/wordcamp.org/assets/895819/723daf50-3429-4b9d-942f-581f3e008264)

**Comment by outdoor2kode** [comment]
Note: I can't reproduce this in my local environment, but it definitely exists in production.

**Comment by StevenDufresne** [comment]
It looks likes it working, the logo switches but it doesn't stick. hmm.
