### ISSUE TITLE
Events: Add social media share image & description.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wordcamp.org#1158]
We need to add social media share tags. 

We can use the [showcase code](https://github.com/WordPress/wporg-showcase-2022/blob/625b65aa1876da9c68c5c08e00b6fbdabb8acde2/source/wp-content/themes/wporg-showcase-2022/functions.php#L453C26-L453C26) as inspiration.

@WordPress/meta-design Can we get an image? [Here's showcase's image](https://github.com/WordPress/wporg-showcase-2022/blob/main/source/wp-content/themes/wporg-showcase-2022/images/social-image.png) for sizing.

**Comment by jasmussen** [comment]
This is a first draft just to have something ready.

![Thumbnail-events](https://github.com/WordPress/wordcamp.org/assets/1204802/5949f3d8-f5d7-4d80-8ddd-b75a25bb40a8)

If @fcoveram gets a chance to refine this, I would defer to any design he makes as superior. [Here's the Figma](https://www.figma.com/file/jdMk5ssz2Av7KFfEaeK7de/Events?type=design&node-id=1937%3A1665&mode=design&t=XgoOfzsPkHJVyd9R-1).

**Comment by fcoveram** [comment]
I don't think the `W` symbol is necessary. I reused the style of Showcase with a white and blueberry mix.

![Events social-image](https://github.com/WordPress/wordcamp.org/assets/895819/6769c1fb-e30a-4ccc-abcb-0f1aa057edc9)

**Comment by thetinyl** [comment]
@StevenDufresne Suggesting the following for the description:

> Find upcoming WordPress events near you and around the world. Join your local WordPress community at a meetup or WordCamp, or learn how to organize an event for your city.
