### ISSUE TITLE
Events: Cancelled event is showing up in the results set.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wordcamp.org#1165]
At the time of logging this bug, we have this event listed but it's cancelled.

| Header | Screenshot |
|--------|--------|
| Page | <img width="1142" alt="Screenshot 2023-12-11 at 8 44 06 AM" src="https://github.com/WordPress/wordcamp.org/assets/1657336/bfc8c82a-740e-46bd-b722-1f7a1319c255"> |
| Event | <img width="371" alt="Screenshot 2023-12-11 at 8 44 31 AM" src="https://github.com/WordPress/wordcamp.org/assets/1657336/730074fb-6b1d-4c27-8d49-6412e8688578"> | 

[Link](https://www.meetup.com/warri-wordpress-meetup/events/297508834)

**Comment by dd32** [comment]
As of now, the event is no longer showing in the results. There's a potential that the event sync process simply hadn't caught up with the meetup event change yet.

**Comment by StevenDufresne** [comment]
Ah, you are right. Must be a cron job that had not run yet.
