### ISSUE TITLE
Text correction on wordcamp Incident Report form

### ISSUE THREAD

**Issue by harshgajipara** [WordPress/wordcamp.org#1177]
**Describe the bug**
In the Incident Report form "Yes" text is not visible. (https://central.wordcamp.org/incident-report/). 

**Steps to reproduce the behavior:**
- go to https://central.wordcamp.org/incident-report/
- go to Was a police report filed field 
- you will able to see the issue

**Expected behavior**
- it should be visible properly & easy to read.

**Screenshots**
![image](https://github.com/WordPress/wordcamp.org/assets/60835353/0983d9af-97f4-4986-b3cc-7387b4302c57)

## Solution: 
Just need to replace "legend" tag with "label"
![image](https://github.com/WordPress/wordcamp.org/assets/60835353/89a1c72d-dfa9-48cb-82a5-c5da99b35ca3)

**Comment by dd32** [comment]
This HTML is generated by the Jetpack Contact form module.

The relevant shortcode is this:
> [contact-field label="Was a police report filed?" type="radio" options="Yes,No"]

It looks like this changed the HTML markup intentionally:
https://github.com/Automattic/jetpack/pull/34147

Unfortunately, the twentyten theme styles legends differently than labels, and I'm not sure Jetpack should expect otherwise.

**Comment by dd32** [comment]
Additionally the above PR added an extra `fieldset`, so now it's `fieldset > fieldset` which results in the double padding and margins.

The fix required here is going to be a bunch of CSS styles that override twentytens styles, and/or a jetpack bug report to revert/change the behaviour.

**Comment by sabernhardt** [comment]
I did not find a problem with the Jetpack form in my own WordPress installation, so https://github.com/Automattic/jetpack/pull/34147 seems to have fixed the Jetpack plugin. In my test, the group has one fieldset with a visible legend as its first child element, and each option has a visible label programmatically connected to its button.

![Jetpack contact form radio buttons in WordPress 6.4](https://github.com/WordPress/wordcamp.org/assets/17100257/15594004-8f4f-409a-b90a-593595e2a442)

However, the **WordCamp** site has _temporary_ tweaks from #874 that probably do not belong there anymore.

https://github.com/WordPress/wordcamp.org/blob/7823c7aa3c076f37e99a9ba8f66050ed569b94e4/public_html/wp-content/mu-plugins/jetpack-tweaks/miscellaneous.php#L199-L206

The first item ("Yes") needs to be a label for the radio button, and the [screen-reader-only styles for legend elements](https://github.com/WordPress/wordcamp.org/blob/7823c7aa3c076f37e99a9ba8f66050ed569b94e4/public_html/wp-content/mu-plugins/jetpack-tweaks/miscellaneous.php#L251-L259) are not appropriate on the Incident Report page (any other forms likely should not hide the legend either).
