### ISSUE TITLE
Request to add fonts for https://asia.wordcamp.org/2024/

### ISSUE THREAD

**Issue by candy02058912** [WordPress/wordcamp.org#1189]
Related Issue: https://github.com/WordPress/wordcamp.org/issues/1075

As @StevenDufresne suggested:
> For the time being, as @dd32 has suggested, we'll manually add fonts until https://github.com/WordPress/gutenberg/issues/55063.
> If you want to use a Google Font, open an issue with the fonts you want to be added.

Would like to make a request for the following fonts to be added for https://asia.wordcamp.org/2024/

```
@import url('https://fonts.googleapis.com/css2?family=Roboto&family=Roboto+Slab:wght@400;500;600;700;800&family=Sansita&display=swap');
```

Appreciate the help 🙏

**Comment by StevenDufresne** [comment]
Update: I've tried manually adding them to the fonts folder, but it does appear like some built-it post types are being created: 

https://github.com/WordPress/gutenberg/blob/45dc4b1a0e59abe6870078d3538a4e81a58e8191/lib/experimental/fonts/font-library/class-wp-font-family.php#L483

I haven't figured out how to create those yet.

**Comment by outdoor2kode** [comment]
Just noted that the requested fonts have already been added to the site and font variants can now be activated in the fonts manager. 
However, due to existing typekit dependencies, they need to be removed first before activation to avoid conflicts that could break the website.
@candy02058912 @miminari

**Comment by miminari** [comment]
@renintw Thank you so much!
