### ISSUE TITLE
Make clean filter URLs on events.wordpress.org

### ISSUE THREAD

**Issue by jdevalk** [WordPress/wordcamp.org#1196]
Right now the overview of WordCamps on events.wordpress.org has the following URL: `https://events.wordpress.org/upcoming-events/?event_type%5B%5D=wordcamp`

I'd prefer that to be: `https://events.wordpress.org/upcoming-events/wordcamp/`

Is that doable?

**Comment by iandunn** [comment]
What would be the best URL when multiple facets, and multiple values for a facet, are applied at once? e.g., https://events.wordpress.org/upcoming-events/?country[]=DE&country[]=NZ&event_type[]=meetup&format_type[]=in-person&month[]=02&month[]=03
