### ISSUE TITLE
Local: Bump PHP/MYSQL versions in docker

### ISSUE THREAD

**Issue by pkevan** [WordPress/wordcamp.org#1200]
When setting up the docker local environment, it wouldn't load with php 7.4 and mysql 5.7 for some reason - bumping to php 8.2 and mysql 8.0 seemed to fix the issue.

Unsure if this is something we want to roll out, but noting for discussion.

**Comment by pkevan** [comment]
possibly partially fixed by #1229

**Comment by candy02058912** [comment]
> mysql 8.0 seemed to fix the issue

Has been bumped in https://github.com/WordPress/wordcamp.org/pull/1261

**Comment by pkevan** [comment]
Fixed in #1261
