### ISSUE TITLE
Local: built plugins fail to install

### ISSUE THREAD

**Issue by pkevan** [WordPress/wordcamp.org#1201]
Both the `blocks` and `virtual-embeds` mu-plugins fail to be built upon local initialisation, resulting in fatal errors.

Unsure if the built versions of the plugins should be installed, or if a build script needs to be run within the environment.

**Comment by ryelle** [comment]
There's a `build` in [step 6 here](https://github.com/WordPress/wordcamp.org/tree/production/.docker), as part of all the local installation (composer deps, yarn) — running that before booting up the docker should have built all the required files. Did it not work for you?

**Comment by pkevan** [comment]
hmm - i'm sure I did that but maybe it failed - i'll try again, thanks!

**Comment by pkevan** [comment]
i've redone the step 6, reinstalling `nvm` - it must have failed when I did it originally. 

Thanks @ryelle !
