### ISSUE TITLE
Request to add fonts to https://europe.wordcamp.org/2024/ and https://wceutest24.wordcamp.org/2024/

### ISSUE THREAD

**Issue by hideandgeek404** [WordPress/wordcamp.org#1203]
Related Issue: https://github.com/WordPress/wordcamp.org/issues/1075

As @StevenDufresne suggested:

> For the time being, as @dd32 has suggested, we'll manually add fonts until https://github.com/WordPress/gutenberg/issues/55063.
> If you want to use a Google Font, open an issue with the fonts you want to be added.

Would like to make a request for the following fonts to be added for both https://europe.wordcamp.org/2024/ and https://wceutest24.wordcamp.org/2024/

```
@import url('https://fonts.googleapis.com/css2?family=Krona+One&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Lora&display=swap');
```

Thank you very much for all your help!

**Comment by pkevan** [comment]
@StevenDufresne did you figure out a solution for this?

**Comment by StevenDufresne** [comment]
This should be done.

You'll need to activate the variant on each site:

| Screenshot |
|--------|
| <img width="1204" alt="Screenshot 2024-01-17 at 1 36 03 PM" src="https://github.com/WordPress/wordcamp.org/assets/1657336/09236484-4f98-46c5-bbe8-2dbdef50ff74"> |

**Comment by hideandgeek404** [comment]
Hmm, maybe we aren't doing something right but even with those fonts appearing in the Global Styles options, they do not seem to be getting loaded. There are some font's being loaded from Google (such as Inter) but these custom ones are not appearing anywhere and the site falls back to the sans serif default font. 

Any ideas what we might be missing?

I looked at the `Install fonts` section and noticed that that one seemed to have the correct font but the variant was `Krona One 400 normal`. Could this be the issue?
<img width="354" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/81396999/e472602f-cb67-408b-84bc-212686f64452">

**Comment by ryelle** [comment]
It looks like we need to do a little more on the WordCamp site to make this work— I added [a draft page to test fonts](https://europe.wordcamp.org/2024/?page_id=4026) to the WC Europe site which I've been using to test this, but so far I haven't gotten it working.

**Comment by ryelle** [comment]
@hideandgeek404 Okay, Krona One and Lora should be available for WordCamp Europe now. I see them loaded and rendered on the front end in my test page:

<img width="978" alt="Screenshot 2024-01-22 at 11 37 03 AM" src="https://github.com/WordPress/wordcamp.org/assets/541093/ef088ee0-82c5-4004-a814-1c86dccdbb72">

**Comment by CarlosLongarela** [comment]
Thanks @ryelle in our testing website (https://wceutest24.wordcamp.org/2024/) in frontend, don't load the fonts (we force to load with CSS loading the file from Google Fonts):

![image](https://github.com/WordPress/wordcamp.org/assets/2273486/80db1c5a-4163-43ad-9df4-0b3efb176ebb)

But if it's working on the live website, it's ok.

Thought is, would be possible to load the fonts in woff2 format? (we have the fonts in that format if they are necessary).

Thanks.

**Comment by ryelle** [comment]
I only activated them on the main WCEU site, but they are available on the test site too. If you load these, you can remove your google fonts workaround.

<img width="891" alt="Screenshot 2024-01-22 at 6 15 28 PM" src="https://github.com/WordPress/wordcamp.org/assets/541093/13e78cfd-206e-4eca-b600-44b0a9451e3e">

> Thought is, would be possible to load the fonts in woff2 format? (we have the fonts in that format if they are necessary).

The process we've got right now is a patch until this feature is better supported in core, and it sounds like the core process should support woff2. But yes, I can swap out the files for woff2. I'll let you know when that's done.

**Comment by CarlosLongarela** [comment]
Oh, fantastic, I deactivated the two additional fonts, activated these two fonts as Theme fonts, deleted the additional CSS hack, deleted cache and working fine. Thanks.

![image](https://github.com/WordPress/wordcamp.org/assets/2273486/c9a8151e-5ee4-40a9-8e9f-a85180fd011d)

**Comment by CarlosLongarela** [comment]
@ryelle sorry to bother you with this again. On the live website, we will change the current theme (2023) to the 2024 theme in a few days to transfer the staging website design. Would be necessary to install these two fonts again?

**Comment by ryelle** [comment]
> Would be necessary to install these two fonts again?

No, the fonts should be available for any block theme 👍🏻
