### ISSUE TITLE
Add instructions to add host's security certificate inside Docker

### ISSUE THREAD

**Issue by vedanshujain** [WordPress/wordcamp.org#121]
In docker setup, currently security exception needs to be added by the browser when visiting sites for the first time. Please add instruction to generate/add trusted certificate to docker.

**Comment by iandunn** [comment]
Related #126

**Comment by coreymckrill** [comment]
I _think_ this is fully addressed by 4dad5ff. Closing, but feel free to reopen if you think there's more to do here.
