### ISSUE TITLE
Events: query-filter broke with upgrade to Gutenberg 17.5.1

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#1225]
`r4725-wordcamp` upgraded Gutenberg from `17.1.2` to `17.5.1` in order to fix #1220. It looks like the `query-filter` block on event.wordpress.org is no longer working, though.

When the page loads, these errors appear in the console:

```
Uncaught SyntaxError: Unexpected token 'export' (at index.min.js?ver=17.5.1:1:33659)

view.js?ver=801619dd5405f13e806c:3 Uncaught TypeError: Cannot read properties of undefined (reading 'store')
    at view.js?ver=801619dd5405f13e806c:3:140
    at view.js?ver=801619dd5405f13e806c:3:1673
(anonymous) @ view.js?ver=801619dd5405f13e806c:3
(anonymous) @ view.js?ver=801619dd5405f13e806c:3
```

If you click on one of the filters, this error appears:

```
hooks.tsx:260 Uncaught TypeError: Cannot read properties of undefined (reading 'wporg')
    at hooks.tsx:260:50
    at Array.forEach (<anonymous>)
    at hooks.tsx:260:20
    at Nt.l.evaluate.u.scope (hooks.tsx:276:17)
    at t.props.<computed> [as clickfalse] (directives.js:93:5)
    at HTMLButtonElement.A (preact.module.js:1:4501)
(anonymous) @ hooks.tsx:260
(anonymous) @ hooks.tsx:260
Nt.l.evaluate.u.scope @ hooks.tsx:276
t.props.<computed> @ directives.js:93
A @ preact.module.js:1
```

**Comment by ryelle** [comment]
I believe the interactivity API changed — see https://github.com/WordPress/wporg-mu-plugins/issues/490. Unfortunately we needed to update to 17.2+ for the fix in #1220, but 17.2 is when the change occurred. Doubly unfortunate, we can't update GB on wp.org, so any fix will need to account for both Interactivity API standards.

**Comment by pkevan** [comment]
It's unfortunate that Blocks Everywhere requires a set version of Gutenberg to work, aside from using https://github.com/WordPress/wporg-mu-plugins/pull/561 is it worth moving away from that plugin?

**Comment by ryelle** [comment]
Just an update: I've got an update to `wporg-mu-plugins` working locally, I'll get the PR(s) up tomorrow. I think @dd32's GB version switcher is probably the best bet, while we figure out if we can replace Blocks Everywhere with something else.

**Comment by ryelle** [comment]
The updated Query Filter block has been deployed, and the WC network is now running GB 17.6 👍🏻
