### ISSUE TITLE
External links opening in the same tab on events.wordpress.org

### ISSUE THREAD

**Issue by sourabhgarg01** [WordPress/wordcamp.org#1234]
**Describe the bug**

External links on the events.wordpress.org site are currently configured to open in the same tab/window. This behavior deviates from standard user experience practices, where external links should open in a new tab/window. This inconsistency may lead to users inadvertently navigating away from the events site, potentially causing a disruption in their browsing experience.

**To reproduce**

Steps to reproduce the behaviour:
1. Navigate to the events.wordpress.org.
2. Locate an external link, such as one pointing to a different website or resource.
3. Click on the external link.

**Expected behaviour**

Upon clicking on an external link, it should open in a new tab/window. This behaviour ensures that users remain on the events.wordpress.org site while also providing access to external content. This approach aligns with standard user experience principles, minimizing the risk of users unintentionally leaving the events site and improving the overall navigation flow.

**Screenshots**

1. https://prnt.sc/Z8d5jeNk8hfW
2. https://prnt.sc/HXR4BA6CKqVi

**WordCamp**

https://events.wordpress.org/

**Comment by pkevan** [comment]
This is expected behaviour (not opening links in new tabs/windows) and is designed in this way for accessibility.

More information on this can be found here: https://www.w3.org/TR/WCAG20-TECHS/G200.html
