### ISSUE TITLE
WordCamp Font Installer Doesn't Work

### ISSUE THREAD

**Issue by timbouchard** [WordPress/wordcamp.org#1249]
Font manager for WordCamp site install doesn't work. Hoping to get help adding a font to use to our install.

**To reproduce**

1. Go to WordCamp Site Editor > Typography > Install Fonts
2. Upload woff2 font
3. Activate font in list (see it showing)
4. Refresh typography list (it will not show properly)

**Expected behavior**

Using typography style font installation. File uploads, even shows temporarily, then no longer works on refresh. Alternatively using a remote stylesheet with @import via GitHub also doesn't work due to @import being blocked via remote CSS.

**Screenshots**

![font-upload-error](https://github.com/WordPress/wordcamp.org/assets/2424927/32b15449-5e96-44f0-b9bd-2cd3772300c8)
![font-uploaded-showing](https://github.com/WordPress/wordcamp.org/assets/2424927/6c70a9a8-0eb1-4d38-99ae-271eafbcf155)
![font-uploaded-not-showing](https://github.com/WordPress/wordcamp.org/assets/2424927/5bcc2a7b-5b97-4d7e-8a4c-b2e8f105ad1e)

**WordCamp**

https://buffalo.wordcamp.org/2024/

**System**

 - Device: Macbook
 - OS: OSX Ventura
 - Browser Chrome
 - Version 121.06

**Comment by timbouchard** [comment]
Can you add the following font for use on https://buffalo.wordcamp.org/2024/?

(if we can use a github hosted font):
@import url('https://github.com/timbouchard/wcbuf24/raw/master/fonts/OffBit-Bold.woff2');

(if it has to be a google font):
@import url('https://fonts.googleapis.com/css2?family=VT323&display=swap');

**Comment by dd32** [comment]
> Can you add the following font for use on https://buffalo.wordcamp.org/2024/?

This has been requested here:
https://github.com/WordPress/wordcamp.org/issues/1075#issuecomment-1936184119

Font installation will probably be fixed via #1245 and #1075.
