### ISSUE TITLE
Exchange Rate Issue with Automated Invoicing in QBO

### ISSUE THREAD

**Issue by harmonyromo** [WordPress/wordcamp.org#1250]
**Describe the bug**

When an invoice is approved in the [Sponsor Dashboard](https://wordcamp.org/wp-admin/network/admin.php?page=sponsor-invoices-dashboard) and sent to QBO, if said invoice is in a currency other than USD, the exchange rate populates as 1:1 versus listing the actual rate for the date of creation. If an invoice is created directly in QBO in a currency other than USD, the exchange rate is populated appropriately. QBO Support was contacted in February of 2024, but no solution was offered. [This has been an issue since 2017.](https://a8c.slack.com/archives/C204BD7PT/p1484872496000472)

**To reproduce**

1. Go to any event site that has selected to run the event in a currency other than USD. For example, [WCEU](https://europe.wordcamp.org/2024/wp-admin/edit.php?post_type=wcb_sponsor_invoice).
2. Click on `Add New` in the upper left corner.
3. Once the test invoice has been created in EUR, send the invoice for approval. Then visit the main [Sponsors Invoice Dashboard](https://wordcamp.org/wp-admin/network/admin.php?page=sponsor-invoices-dashboard) and click `Approve` to the right of the test invoice.
4. Return to the WCEU sponsor invoice dashboard, and after opening QBO to the WPCS business, click on the link in the upper right corner `View QBO Invoice`

**Expected behavior**

You will notice the exchange rate in the upper left corner will reflect 1 EUR = 1 USD

[example.pdf](https://github.com/WordPress/wordcamp.org/files/14313919/example.pdf)

**System (please complete the following information):**

 - Device: laptop
 - OS: iOS
 - Browser Chrome
 - Version 121.0.6167.160

**Comment by kcristiano** [comment]
Flagging this up again as I ran across it.  Do we have any dev updates?

**Comment by outdoor2kode** [comment]
Hi @harmonyromo 👋 

I followed the instructions and tested the process, can confirm the issue still persists. 
I have a couple of questions before diving into researching this issue.

How frequently are you encountering this issue?
How you're currently handling this? 

And I sent you a DM regarding the test data cleanup. 
Could you take a look at it when you have a moment? 

Thanks!

**Comment by harmonyromo** [comment]
Hey @renintw 

The issue still persists, yes. Every single invoice that is not in USD is affected by this issue. Currently, I am manually adjusting the exchange rate by entering each invoice individually, and clicking "edit totals" under the listed rate, then edit again on the side menu.
<img width="732" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/55291530/953dc08e-42f2-49b1-b6b2-b060e46c0503">
I then enter another screen where I can actually adjust the rate: 
<img width="333" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/55291530/9ba8810c-204e-4eb9-b11d-f46fc607b3a5">
The process is more tedious now that QBO has updated the user interface, which is annoying.
