### ISSUE TITLE
Local: "No such file or directory" and "Failed opening" issues after setting up local environment

### ISSUE THREAD

**Issue by candy02058912** [WordPress/wordcamp.org#1265]
**Describe the bug**

After following the Initial Setup in https://github.com/WordPress/wordcamp.org/blob/production/.docker/readme.md, https://central.wordcamp.test/ shows a fatal error: 

![error](https://github.com/WordPress/wordcamp.org/assets/6586048/2961d60d-b659-4b9c-abe7-906ccd6b6c84)

After commenting the related lines mentioned from the error, the test site loads with a warning.
* https://github.com/WordPress/wordcamp.org/blob/0c93c974be234aea879f09c1b4511867852b5ff7/public_html/wp-content/mu-plugins/load-other-mu-plugins.php#L21
* https://github.com/WordPress/wordcamp.org/blob/0c93c974be234aea879f09c1b4511867852b5ff7/public_html/wp-content/db.php#L3

![warning](https://github.com/WordPress/wordcamp.org/assets/6586048/84de9310-6ca7-4788-b573-e859edb22b37)

**To reproduce**

1. Follow the Initial Setup in https://github.com/WordPress/wordcamp.org/blob/production/.docker/readme.md 
2. The following error is shown when opening https://central.wordcamp.test/

```
Warning: include_once(/usr/src/public_html/wp-content/plugins/wp-super-cache/wp-cache-phase1.php): failed to open stream: No such file or directory in /usr/src/public_html/wp-content/advanced-cache.php on line 32 Warning: include_once(): Failed opening '/usr/src/public_html/wp-content/plugins/wp-super-cache/wp-cache-phase1.php' for inclusion (include_path='.:/usr/local/lib/php') in /usr/src/public_html/wp-content/advanced-cache.php on line 32 Warning: require_once(/usr/src/public_html/wp-content/plugins/hyperdb/db.php): failed to open stream: No such file or directory in /usr/src/public_html/wp-content/db.php on line 3 Fatal error: require_once(): Failed opening required '/usr/src/public_html/wp-content/plugins/hyperdb/db.php' (include_path='.:/usr/local/lib/php') in /usr/src/public_html/wp-content/db.php on line 3
```

**Expected behavior**

After going through Initial Setup, a local WordCamp site can be seen without errors.

**Screenshots**

Provided above

**WordCamp**

The local environment

**System (please complete the following information):**

 - Device: laptop
 - OS: macOS 13.2.1
 - Browser: Chrome
 - Version: 122.0.6261.111 (arm build)

**Comment by pkevan** [comment]
I've seen this happen before, and it's usually a failure in the composer installation part of the setup.

https://github.com/WordPress/wordcamp.org/blob/production/.docker/config/composer.json#L117

The packages exist, and are valid from the [source](https://wpackagist.org/search?q=hyperdb&type=any&search=).

**Comment by hideokamoto** [comment]
I met a similar issue before.
My workaround is the following:

 1: Copy the plugins files manually:
`cp -R /.docker/config/public_html/wp-content/plugins/* public_html/wp-content/plugins/`

 2: Copy the wp-config.php file manually:
`cp .docker/wp-config.php public_html `

 3: Copy the mu-plugins manually:
```
% cd .docker/config
% composer install
% cd ../../
% cp -R .docker/config/public_html/wp-content/mu-plugins-private public_html/wp-content 
```
