### ISSUE TITLE
Autofill more fields on the new events.wordpress.org Events Organizer Application

### ISSUE THREAD

**Issue by catederosia** [WordPress/wordcamp.org#1267]
This is an internal fix and does not need a P2. Based on research, it seems the new [Event Organizer Application](https://central.wordcamp.org/event-organizer-application/) does not autofill some important fields that the WC organizer application does.

- organizer location
- organizer WP.org username
- organizer email address

My request is to please have these three fields autofill as well.

Screenshots available upon request.

**Comment by pkevan** [comment]
I think the above PR (https://github.com/WordPress/wordcamp.org/pull/1268) should fix these issues.

**Comment by catederosia** [comment]
Thank you @pkevan for opening the other ticket. Should I do anything with this ticket for now, or wait until we see what the outcome of ticket [#1268](https://github.com/WordPress/wordcamp.org/pull/1268) is?

**Comment by catederosia** [comment]
@pkevan Should I close this request or wait to see if the other GitHub issue was sufficient?

**Comment by catederosia** [comment]
Because issue #1268 is similar and I am leaving community work, I'm going to go ahead and close this now.
