### ISSUE TITLE
Visa Docs - Country of Residency vs Country Issuing Password

### ISSUE THREAD

**Issue by shawnhooper** [WordPress/wordcamp.org#1277]
**Describe the bug**

While getting ready to send out Visa letters for WordCamp Canada speakers and volunteers, we saw that the WordCamp site prompts for the Country of Residence. 

I'm not sure how this works elsewhere, but in Canada, we actually need to Country that issued the person's passport. Where they live isn't important. 

I'm wondering if the Visa letter form needs updating in the WordCamp site, or if is this something unique to Canada. 

**To reproduce**

1. Go to a WordCamp site's wp-admin
2. Click on Docs from the sidebar
3. Go to the Speaker Visa Letter, or Attendee Visa Letter (applies to both)
4. Click Next 
5. See the field called "Country of Residency"

**Expected behavior**

I wanted to see a field for Passport Issuing Country.  Instead I saw Country of Residency.

**Screenshots**

![image](https://github.com/WordPress/wordcamp.org/assets/2073284/183c186c-7f36-478e-9460-dd89a14ebddd)

**Comment by pbearne** [comment]
Parched
