### ISSUE TITLE
Cookie banner form element should have a (universal) ID

### ISSUE THREAD

**Issue by jonoalderson** [WordPress/wordcamp.org#1334]
We're iterating on our analytics setup for WordCamp websites, and want to understand form interactions in particular.

However, the cookie policy acceptance form currently pollutes that data, in a way that's hard to filter. Adding a simple `id` parameter to the current markup (with a simple/consistent value) would help us to significantly improve our understanding of what's going on on these sites.

![image](https://github.com/WordPress/wordcamp.org/assets/11629607/40c6f865-cadb-49a1-834c-3fc3125be54e)

![image](https://github.com/WordPress/wordcamp.org/assets/11629607/9367a63a-6229-42dd-b7d0-ea5f46ffa35e)

**Comment by pkevan** [comment]
Updated Jetpack to 13.6, and the id now appears on the form 🥳
