### ISSUE TITLE
Need data of WordCamp tickets per year 2015-2019

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/wordcamp.org#1336]
We were checking [these reports](https://central.wordcamp.org/reports/ticket-revenue-report/?report-year=2019&period=all&wordcamp-id=&action=Show+results) in order to populate data of WordCamp tickets sold per year.

However, we might get inaccurate results of total tickets sold in 2019 as it should be the year with more WordCamps, and zero results from 2015 to 2018. We were wondering if it happened because the Ticket Revenue Report page was created in 2019.

We would need help to gather the following data: 

- Ticket sold
- Tickets refunded
- Total tickets

For WordCamps in:

- 2015
- 2016
- 2017
- 2018
- 2019

**Comment by pkevan** [comment]
The data for these reports only starts from Nov 2019, so this is not possible through the reporting tool.
