### ISSUE TITLE
[Schedule Block] "Time" column header string has no translation in French

### ISSUE THREAD

**Issue by alexandrebuffet** [WordPress/wordcamp.org#1346]
### Describe the bug

"Time" column header string in Schedule block has no French translation. How can I help translate the project?

### Screenshots / Screencasts

![image](https://github.com/user-attachments/assets/8cb7b637-4883-430f-bcfa-291131567a6f)

### WordCamp

[WordCamp Bretagne 2024](https://bretagne.wordcamp.org/2024) 

The schedule page is not yet published.

**Comment by ryelle** [comment]
Thanks for the report. I looked into this briefly, and I think it's the same root issue as #1096. I'm going to close this issue, and you can follow the other issue for updates.

**Comment by eduardozulian** [comment]
@ryelle, can you confirm if #1299 is the same issue? I think so, but I wanted to check with you first. Thanks!
