### ISSUE TITLE
Incorrect event name shows up in the WordCamp Report tool

### ISSUE THREAD

**Issue by peiraisotta** [WordPress/wordcamp.org#1348]
### Describe the bug

The event "[WordPress Day for Developers Lisboa 2024](https://central.wordcamp.org/wp-admin/post.php?post=6849564&action=edit)" shows up with the name "WordPress Events" on the [WC Status Report](https://central.wordcamp.org/wp-admin/index.php?page=wordcamp-reports&report=wordcamp-status).

### To reproduce

1. Go to [WC Status Report](https://central.wordcamp.org/wp-admin/index.php?page=wordcamp-reports&report=wordcamp-status)
2. Select range date between July 6 and July 19 2024
3. Select WordCamp Status "In-Pre Planning"
4. Click on "Show Results" button
5. See the events showing up and one has as a title "WordPress Events"

### Expected behavior

There is no event with "WordPress Events" as a title, and after researching we've identified that it seems to be the "[WordPress Day for Developers Lisboa 2024](https://central.wordcamp.org/wp-admin/post.php?post=6849564&action=edit)" event instead.

### Screenshots / Screencasts

![image](https://github.com/user-attachments/assets/bb80b649-6eb4-4dd6-9d64-e08d8647394c)

### WordCamp

If this is a problem on a specific WordCamp's site, list the site or page URL here: https://central.wordcamp.org/wp-admin/post.php?post=6849564&action=edit

### System (please complete the following information)

- Device: MacBook Air
- OS: Sonoma version 14.5
- Browser Chrome

### Security Issues

To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by pkevan** [comment]
![Screenshot 2024-08-05 at 11 36 55](https://github.com/user-attachments/assets/175a8c48-3ab7-4489-952b-acb4a72e68ba)

This looks like a setup problem rather than a bug, as the title now appears.
