### ISSUE TITLE
Please redirect attendee survey link

### ISSUE THREAD

**Issue by peiraisotta** [WordPress/wordcamp.org#1362]
### Components / Tools

Can you please redirect the following link https://wordcampcentral.survey.fm/wordcamp-attendee-survey-2019 to https://form.jotform.com/WordPress_Community/wordpress-event-attendee-feedback ?

### Priority

High priority, as some attendees might want to fill up surveys from events happened in late August.

If I should post this request somewhere else, or is there is a way I can do it by myself, please let me know.

**Comment by pkevan** [comment]
No idea if this is possible, but that request would be with crowdsignal, not within any code controlled by the wordcamp repo.
