### ISSUE TITLE
Please stop sending survey emails to WP Events (former next-gen) attendees

### ISSUE THREAD

**Issue by peiraisotta** [WordPress/wordcamp.org#1363]
Hello, can you please stop sending the currently automated survey emails to WP Events (former next-gen) attendees? 

We'll want them to fill out the same survey we've created for WordCamps.

Do you know if [this automated reminder](https://central.wordcamp.org/wp-admin/post.php?post=3039437&action=edit) is also sent only to WordCamp organizers or is it also sent to organizers of events other than WCs (former “next-gen”)?

If it is only sent to WC organizers, can you please activate it for organizers of events other than WCs as well?

Thanks a lot!

**Comment by StevenDufresne** [comment]
> Do you know if [this automated reminder](https://central.wordcamp.org/wp-admin/post.php?post=3039437&action=edit) is also sent only to WordCamp organizers or is it also sent to organizers of events other than WCs (former “next-gen”)?

I don't think Organizer Reminders is configured for the events network (//events.wordpress.org). Is this the only feature that will cross over? 

If not, I think we need to have a better understanding of what WP Events are now. My concern is that we start migrating over most WC functionality to the Events and we end up with duplicate code everywhere.

> Hello, can you please stop sending the currently automated survey emails to WP Events (former next-gen) attendees?

Do you still need access to the data? If so, please export the data and confirm. You can do that by visiting the "Feedback" section of the event and clicking "Export".

**Comment by peiraisotta** [comment]
Thanks @StevenDufresne. We've exported the data. 

>I don't think Organizer Reminders is configured for the events network (//events.wordpress.org). 

I'll discuss with the rest of the program managers about it. For sure some reminders should be received by all organizers, but probably not all reminders. I'll come back about this later on. Thank you.

**Comment by StevenDufresne** [comment]
I've turned off the plugin. I'll go ahead and delete it as well.
