### ISSUE TITLE
WordCamp Login Change - UI Improvement Needed Urgently

### ISSUE THREAD

**Issue by aashishpahwa** [WordPress/wordcamp.org#1397]
The recent changes of WordCamp making it mandatory to create an account for buying tickets is hampering ticket sales greatly.There are several first-timers too and people don’t want to take an extra step to get the ticket.  Is there a way to go away with this requirement?
Tickets sales have slumped after this.

The UI is not optimized as well. There's just a paragraph text to tell them to login, not even a login button or CTA.Several potential attendees don't know how to proceed.

Here's how WordCamp Delhi's website looks to the visitors right now - 

![Image](https://github.com/user-attachments/assets/73340fce-bd7c-43d8-a6c5-7b7f9d7366b0)

There isn't a CTA now at all.

I'd suggest keeping the 'Register' CTA as it is and redirecting them to a login or signup page as an interstitial.

Currently, no CTA means people don't know how to proceed. 

![Image](https://github.com/user-attachments/assets/6b54ed0e-9e57-4e0f-9675-adb3c43aac6c)

Even the wordpress.org login page can be improved to cater to these first timers. It should tell them about it being one of the steps to buy the ticket - 

![Image](https://github.com/user-attachments/assets/5b4881e2-1567-453b-a625-c647e88bdf78)

Honestly, the change affected us and might hamper our promise to the sponsors.

**Comment by markmemayank** [comment]
Hi @aashishpahwa great suggestion and this should be addressed at earliest.

**Comment by GautamMKGarg** [comment]
Nice suggesion

**Comment by kumaranup594** [comment]
@aashishpahwa @markmemayank create a small video and add top of that with thumbnail clearly mentioned - Please watch to buy ticket "something like this I mean".

**Comment by adamwoodnz** [comment]
> Even the wordpress.org login page can be improved to cater to these first timers. It should tell them about it being one of the steps to buy the ticket

We customise the login form introduction copy when the request is from wordcamp.org

<img src="https://github.com/user-attachments/assets/36362be9-1f2e-46e2-9f69-afd32d164a0e" width="400">

We could likely do the same for the account creation form introduction copy.

**Comment by adamwoodnz** [comment]
> I'd suggest keeping the 'Register' CTA as it is and redirecting them to a login or signup page as an interstitial.

Someone will be looking into this option, thanks for the suggestion.

**Comment by aashishpahwa** [comment]
Thanks, team, for quickly solving the ticketing UX issue. But it still needs some work.

The current UX makes it almost impossible for newbies to register a ticket for WordCamps (16 steps before they see the checkout button - then 3 more steps to confirm payment). Had a word with several newbies. It won't just affect us but all the scheduled WordCamps - hindering the mission of bringing new people to the WordCamps. 

I've recorded the steps here -

https://scribehow.com/embed-preview/Buy_A_Ticket_For_WordCamp_Delhi__Co0obiBrSxGvRZdQ4V1DRA?as=video


Also, for the time being, can we allow Scribehow to be embedded? So we can show these steps to the users?
