### ISSUE TITLE
Unable to proceed to checkout when *I don't know who will use this ticket yet* option is enabled

### ISSUE THREAD

**Issue by mbigul** [WordPress/wordcamp.org#1400]
### Describe the bug
I am Bigul, organizer of WordCamp Kerala. There is an issue in CAMPTIX. It happens when we are purchasing multiple tickets by choosing the following option.

_I don't know who will use this ticket yet_

One of the attendee of WordCamp Kerala has noticed it and I can replicate it. It happens in different browsers also.

### To reproduce

1. Go to https://kerala.wordcamp.org/2024/tickets
2. Select 2 or more tickets
3. Proceed to register
4. Enter the registration information for the first ticket 
5. Choose *I don't know who will use this ticket yet* option
6. Enter phone number and select the options (like *Do you have any accessibility needs*)
7. Proceed to checkout, it will be stuck 

### Expected behavior
Proceed to checkout when choosing *I don't know who will use this ticket yet* option

### Screenshots / Screencasts

Please check this screencast for more details - https://dl.dropboxusercontent.com/scl/fi/m2u994zahjszatkv5ls4n/2024-10-18_14h45_35.mp4?rlkey=h04crsz8p7n26ltr68ortcn4g&dl=0

### WordCamp

We noticed the issue in WCKerala website - https://kerala.wordcamp.org/2024/tickets. But it looks like a common issue. 

### System (please complete the following information)

 - Device: Laptop or Desktop
 - OS:  Windows 11 Pro
 - Browser: Chrome, Firefox
 - Version: latest

### Security Issues

To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by pkevan** [comment]
Thanks for reporting this issue - i'm taking a look at it.
