### ISSUE TITLE
Ticketing login UX Still need work

### ISSUE THREAD

**Issue by aashishpahwa** [WordPress/wordcamp.org#1406]
Thanks, team, for quickly solving the ticketing UX issue. But it still needs some work.

The current UX makes it almost impossible for newbies to register a ticket for WordCamps (16 steps before they see the checkout button - then 3 more steps to confirm payment). Had a word with several newbies. It won't just affect us but all the scheduled WordCamps - hindering the mission of bringing new people to the WordCamps. 

I've recorded the steps here -

https://scribehow.com/embed-preview/Buy_A_Ticket_For_WordCamp_Delhi__Co0obiBrSxGvRZdQ4V1DRA?as=video

Also, for the time being, can we allow Scribehow to be embedded? So we can show these steps to the users?

**Comment by StevenDufresne** [comment]
It appears like you pasted the same information that you added in https://github.com/WordPress/wordcamp.org/pull/1399#issuecomment-2423622543.

While I agree there are changes we can make, as mentioned in [my reply](https://github.com/WordPress/wordcamp.org/pull/1399#issuecomment-2425308025), your test case scenario is not real world. You skipped many of the steps in the process and didn't actually create an account. Please take a look at my reply, and adjust your test case so we can make sure we're accurately discussing the sign up flow. After doing so, please create a new ticket or reopen this one.
