### ISSUE TITLE
WordCamp Reports » WordCamp Counts not showing all closed events

### ISSUE THREAD

**Issue by peiraisotta** [WordPress/wordcamp.org#1412]
https://central.wordcamp.org/wp-admin/index.php?page=wordcamp-reports&report=wordcamp-counts

By setting date range from August 27 until October 22, only 2 WordCamps with status "closed", when we actually have had 12 WordCamps and 6 events.

Until the end of August 2024, all WordCamps and Events correctly showed up on this report, and we were able to use the results to track one of the community team's KPI: first time attendee rate (example on who we use this info: results would be past in this [spreadsheet](https://docs.google.com/spreadsheets/d/1T8lbhggTWg1I1Ub7uYppM6muqzejNvTZzyaalaPmolc/edit?usp=sharing), and the obtained FTA rate used for updates like this one: https://make.wordpress.org/updates/2024/07/16/community-team-event-updates-july-16-2024/ ). 

Can you please look into it and, if possible, fix it? We haven't been able to track these data since September.

Thanks a lot.

![Image](https://github.com/user-attachments/assets/d455fc7a-bc10-4c70-aa12-2ae7777f2d44)

**Comment by pkevan** [comment]
> when we actually have had 12 WordCamps and 6 events.

just noting that this report is only for WordCamps, as it grabs data from the individual sites.

**Comment by pkevan** [comment]
> > when we actually have had 12 WordCamps and 6 events.
> 
> just noting that this report is only for WordCamps, as it grabs data from the individual sites.

Correction - should work on any sites within the network (events, wordcamps) where the data can be retrieved.
