### ISSUE TITLE
Create new GitHub issues when new event is created on WC Central

### ISSUE THREAD

**Issue by felipevelzani** [WordPress/wordcamp.org#1415]
### Components / Tools

WordCamp Central / GitHub

### Description

We have been creating events manually on [the Community Team repo](https://github.com/WordPress/Community-Team/issues) whenever there is a new Meetup group, WordCamp, or other WordPress event application.

It would be fantastic if we could have a really simple integration that creates these events directly automatically, as this would save so many hours for the team.

The only data we need there is the Event/Meetup Name, Event Type, and Tracker URL. Then, we need to add the labels `Awaiting Triage`, `application`, and `event`.

* If it is a meetup application, we also need the labels `Meetup` and `meetup-application`.
* If it is a WordCamp, we also need the labels `WordCamp` and `wordcamp-application`.
* For other WordPress events, we also need the labels `WordPress Event` and `wordpress-event-application`.

We can use this here as a reference: https://github.com/WordPress/Community-Team/issues/333

After creating the issue, it would be a "nice to have" if we could add the GitHub issue link to the tracker (as a comment or as a field value).

### Stakeholders

Program Managers & Program Supporters

### How does this new feature contribute to the goals

This would primarily save a lot of time as it is something the team is doing manually.

### Acceptance Criteria

Having these issues created whenever a new application is added for a meetup group, WordCamp, or other WP Events.

### Priority

High, as we have a lot of experienced contributions wasting several hours on it per week.

**Comment by francescodicandia** [comment]
Would be an awesome upgrade

**Comment by StevenDufresne** [comment]
I'm curious as to why GitHub tickets are being created for WordCamps. Why wouldn't these be managed in central.wordpress.org? What features are missing or not working well enough for that purpose?

**Comment by dd32** [comment]
> I'm curious as to why GitHub tickets are being created for WordCamps. 

This handbook entry kinda covers some of it: 
https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/using-github/

IIRC the intention was to make it both more accessible, and use public tracking tools rather than requiring that everyone had complete site access (even though I think that's ultimately required anyway)
