### ISSUE TITLE
Check badge tables are setup

### ISSUE THREAD

**Issue by pkevan** [WordPress/wordcamp.org#1434]
### Describe the bug

Follow-up to #1428 - it seems like the tables needed to properly perform badge functionality aren't loaded on wordcamp sites, and you end up with a DB error, particularly when checking the existence of badges (which seems to stop removals).

The error returned mentions the table not being available:

```
XXX_XXX_groups_members' doesn't exist
```

Given our profile API code (https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/mu-plugins/pub/profile-helpers.php) relying on tables being available we should check the config to make sure it's working as expected.

**Comment by dd32** [comment]
This is because WordCamp is using a partial w.org HyperDB config, and doesn't have access to the BuddyPress tables.

I agree, either it should gracefully handle the direct-db reliance being unavailable, or make it available.

I'm tending to lean towards just fixing the HyperDB situation, but it'd be reasonable to fix the db reliance issue too.

**Comment by pkevan** [comment]
> This is because WordCamp is using a partial w.org HyperDB config, and doesn't have access to the BuddyPress tables.

> I agree, either it should gracefully handle the direct-db reliance being unavailable, or make it available.

> I'm tending to lean towards just fixing the HyperDB situation, but it'd be reasonable to fix the db reliance issue too.

Yes, I spotted that, but wanted to note it for myself (so I didn't forget), and see if there was a reason for it.

I'm in favour of fixing it, since [this](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/mu-plugins/pub/profile-helpers.php#L42) always return false at the moment.

**Comment by pkevan** [comment]
Config updated on production.
