### ISSUE TITLE
Please force status to close for do_action Evanston

### ISSUE THREAD

**Issue by peiraisotta** [WordPress/wordcamp.org#1436]
The event took place on June 13, 2024, but we were never able to schedule it or mark it as closed: https://central.wordcamp.org/wp-admin/post.php?post=5750801&action=edit.

Could you please force the status update and mark it as closed?

**Comment by pkevan** [comment]
doaction events aren't really compatible with this part of the site - I wonder if they should be added to event.wp.org instead?

**Comment by pkevan** [comment]
should be marked closed - had to use WP CLI to force the post status.

**Comment by peiraisotta** [comment]
Yes, it should and it has been done for the[ following do_actions](https://central.wordcamp.org/wp-admin/edit.php?s=action&post_status=all&post_type=wordcamp&action=-1&m=0&paged=1&action2=-1) but this one was somehow left behind. Thank you, @pkevan !
