### ISSUE TITLE
Var definitions in remote CSS are deleted

### ISSUE THREAD

**Issue by CarlosLongarela** [WordPress/wordcamp.org#1441]
## When we use vars in remote CSS in WordCamp Europe, all defined vars are deleted in the final imported CSS

In WordCamp Europe 2025 we need to use CSS variables to avoid errors and code repetitions. We can use the variables defined in the theme, but we need to define variables in our remote CSS file hosted on GitHub like this:

```
:root {
  	--width__blend-element: clamp( 40px, calc(-320px + 30vw), 400px ); screen size: 1200 - 2400
}
```
But the final CSS imported to WordCamp website has `--width__blend-element var deleted.

### To reproduce

Steps to reproduce the behaviour:
1. Go to WordCamp remote CSS and enable it
2. Go to the remote CSS file and define some vars.
3. Reload remote CSS from WordCamp website.
4. Check the imported remote CSS imported to check that vars are deleted.

### Expected behaviour
Expected behaviour is to have vars available in the CSS imported from remote CSS.

### WordCamp

This behaviour happens on all WordCamp websites.

Thanks in advance.

Kind regards.

**Comment by ryelle** [comment]
This is a known issue, see https://github.com/WordPress/wordcamp.org/issues/574 — the code that WordCamp uses to sanitize CSS comes from Jetpack, and it strips out custom properties.

For a workaround, the Site Editor CSS interface does allow custom properties, so you could define the values here.

<img width="685" alt="Image" src="https://github.com/user-attachments/assets/6afc62e5-2c22-4484-af01-1637d16e0725" />
