### ISSUE TITLE
JS Code Standards: Alignment of variable declarations & import statements

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#149]
_This is one of a few issues/PRs dealing with code standards, created after a discussion in slack._

Currently we align `import` statements on `from` and variable declarations on `=`, when there are multiple lines of code, so that this is considered correct.

```js
const { BaseControl, Button, ButtonGroup, PanelBody, PanelRow, RangeControl, ToggleControl, Toolbar } = wp.components;
const { Component, Fragment }                                                                         = wp.element;
const { __ }                                                                                          = wp.i18n;
```

```js
import { PlaceholderSpecificMode } from '../../components/block-controls';
import { getOptionLabel }          from '../../components/item-select';
import { BlockContent }            from './block-content';
import { ContentSelect }           from './content-select';
```

While core does not have a documented code standard around this alignment, it does enforce the `no-multi-spaces` rule in eslint.

As a WordPress community project, we should be following the core coding standards so that anyone involved in a core project can jump into our codebase without needing to learn a new style. This would facilitate community contributions due to faster onboarding. Also, we aren't consistent with this rule, because the tools can't currently automate finding these issues. If we use the suggested style, we can run `eslint --fix` to automatically fix these style issues and not have multiple styles throughout the same file.

The suggestion is to remove the override on `no-multi-spaces`, so that this would be the correct style of the above:

```js
const { BaseControl, Button, ButtonGroup, PanelBody, PanelRow, RangeControl, ToggleControl, Toolbar } = wp.components;
const { Component, Fragment } = wp.element;
const { __ } = wp.i18n;
```

```js
import { PlaceholderSpecificMode } from '../../components/block-controls';
import { getOptionLabel } from '../../components/item-select';
import { BlockContent } from './block-content';
import { ContentSelect } from './content-select';
```

**Comment by iandunn** [comment]
I think https://github.com/WordPress/wordcamp.org/issues/148#issuecomment-516585693 covers my feelings on this as well.

**Comment by iandunn** [comment]
Given that we're moving forward with #148, it probably makes sense to move forward with this too, assuming that @coreymckrill has similar feelings about this one.
