### ISSUE TITLE
Blocks: Set up a convention for class names

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#184]
We use `wordcamp__` and `wordcamp-block__` somewhat inconsistently across the different components & blocks, and in general it would be good to standardize. I suggest using `wordcamp-[folder]`, ignoring the top-level `/blocks/` and `/components/`. Pulling from #96, I think this is a good way to think of this

> For us the block/ and component/ folders are just transparent organizational devices for the filesystem, rather than part of the actual component hierarchy in the DOM.

So for example, the blocks would all use the following (they are already, I believe)…

- organizers: `.wordcamp-organizers__`
- sessions: `.wordcamp-sessions__`
- speakers: `.wordcamp-speakers__`
- sponsors: `.wordcamp-sponsors__`

Anything that wants to have a more general class name should probably be using a shared component. For example, rather than `Placeholder` with `wordcamp__edit-placeholder has-no-mode` classes, it should use a wrapper component that adds the shared classes, and optionally passes through `wordcamp-organizers__edit-placeholder` etc.

For the shared components, let's try this…

- block-controls -> Rename this folder to something more obvious. Since it only contains the placeholder, we could call it `placeholder`, which would make the classname easier to figure out: `wordcamp-placeholder__`
- image: `wordcamp-image__`, with `wordcamp-image__avatar-` & `wordcamp-image__featured-image-` as it is currently 👍🏻
- item-select: `wordcamp-item-select__` as it is currently 👍🏻
- post-list: `wordcamp-post-list__` as it is currently, but remove `wordcamp-block` – I don't think this is a useful utility class.
- block-content -> maybe rename to `post/` or `item/` since each component is a helper related to posts/items, and we can use `wordcamp-post__` as the prefix?

Another idea could be to merge `block-content` and `post-list` into just `components/posts` and have that be all the post-related components.

**We should also standardize on `post` vs `item` in class names & in component names.** Ideally files, components, and classes would all be related. So if we want to use `ItemTitle`, it should use the class `wordcamp-block__item-title`, or be renamed to `PostTitle`.

These will also need to be updated in the PHP files too, so that the editor & front end stay in sync.

**Comment by coreymckrill** [comment]
I agree with these suggestions. On the question of `post` vs `item`, I think I would lean towards `item`, because it's more flexible. While I think that currently all of our "items" are in fact WP posts, we could eventually have a situation where we want to display titles, content, etc. from entities that aren't official WP post objects.

**Comment by iandunn** [comment]
WFM
