### ISSUE TITLE
PWA: Investigate "feeling slow" on mid-level phone

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#198]
> what's the cause? big images? too much markup to parse? server slow ttfb?
> maybe just needs to have better perceived speed rather than better actual speed? like transitions between screens
> maybe new default theme that's a SPA and has a subtle transition animation when fetching new page content from API

**Comment by westonruter** [comment]
Is it any slower than with the PWA plugin disabled?

Perhaps the answer here is rather to implement prefetching, like as provided by [Quicklink](https://github.com/GoogleChromeLabs/quicklink). There's also a [WordPress plugin](https://wordpress.org/plugins/quicklink/) for it.

**Comment by iandunn** [comment]
IIRC it did feel significantly slower than loading a regular WordCamp site, but there could have been a lot of reasons for that, not necessarily caused by the PWA plugin.

**Comment by ryelle** [comment]
Since it sounds like we're not sure if this is caused by the PWA, I'm going to close the issue. Images & CSS are better cached now, so it's possible this is already fixed. If we get more reports of slowness on PWA-enabled sites we can revisit.
