### ISSUE TITLE
PWA Discussion: Caching strategy for navigation (pages a user navigates too)

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#202]
From [comment](https://github.com/WordPress/wordcamp.org/blob/b58e7e1847564765f3427cf622f0ea844a5891a3/public_html/wp-content/mu-plugins/service-worker-caching.php#L88)

Currently we cache pages a user navigates to automatically, up to 50 pages. We're using the `NetworkFirst` caching strategy which means it hits the network, and if it can't load from the network it loads the cached page.

An alternate would be `StaleWhileRevalidate`, which would serve up the cached page while running the network request in the background. Faster for initial view, still makes network request. If the page is then loaded via network, the cache is updated. Either way, you make a network request. If the user is offline, they'd only hit the cache.

The only downside I see to `StaleWhileRevalidate` is that it's a little strange for the browser to "reload" when the network request comes back.

**Comment by westonruter** [comment]
> The only downside I see to `StaleWhileRevalidate` is that it's a little strange for the browser to "reload" when the network request comes back.

Something to consider here would be to show a message like “A new version of the page is available” if an update happened in the background. See Workbox docs on that: https://developers.google.com/web/tools/workbox/modules/workbox-broadcast-cache-update

**Comment by iandunn** [comment]
I like the idea of showing a notice instead of trying to refresh automatically. If that's more trouble than it's worth for the beta release, though, then I don't think it's a high priority.

**Comment by westonruter** [comment]
The `NetworkFirst` strategy is the safest option, at the price of some additional latency. But you'll never get a stale page if you are truly connected to the internet. If you aren't connected to the internet, then you'll likely get served the cached page quickly. The biggest painpoint would be users with very-slow connectivity where they are technically connected but timeouts cause more latency than ideal to then fallback to the cached page.

**Comment by ryelle** [comment]
Yeah, the idea is that we're optimizing for folks who are probably on slow conference wifi or maybe poor data connections - which is why I went with `StaleWhileRevalidate` in #246.

**Comment by ryelle** [comment]
Closed with #246.
