### ISSUE TITLE
PWA: Add caching for uploaded files

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#203]
File uploads are loaded from the `/files/` directory, while the service working is only caching `wp-content` or `wp-includes` assets.

Example URLs:

https://2019.europe.wordcamp.org/files/2019/06/blog-2-1024x512.jpg
https://2019.annarbor.wordcamp.org/files/2018/08/woocommerce_logo.png

Sites can also opt into Jetpack's CDN, so these might not be cached - I think it depends on CORS + cache settings? Needs more investigation.

**Comment by westonruter** [comment]
Photon URLs should be cacheable. To enable caching them, the only thing needed is to ensure the pattern matches the host in addition to the path. See docs here: https://developers.google.com/web/tools/workbox/modules/workbox-routing#how_to_register_a_regular_expression_route
