### ISSUE TITLE
Offline Template: Test with all themes

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#205]
Our supported themes are:

- [x] CampSite 2017
- [x] Twenty Thirteen
- [x] Twenty Sixteen
- [x] Twenty Seventeen
- [x] Twenty Nineteen
- [x] WordCamp Base

We should also test with custom CSS, and with remote CSS.

There's a note about testing with child themes, but WCs can't have child themes, so do we need to do this?

---

The rest we don't test with, but will fix issues on

- Twenty Ten
- Twenty Eleven
- Twenty Twelve
- Twenty Fourteen
- Twenty Fifteen
- WordCamp Base Redux

**Comment by westonruter** [comment]
See also https://github.com/xwp/pwa-wp/issues/199 where the PWA plugin could bundle offline templates for the core themes.

**Comment by ryelle** [comment]
We would still want to inject our own, so we can show the schedule and other info related to the WordCamp.

**Comment by westonruter** [comment]
Good point. At least we could share the same base, or the PWA templates could trigger an action for the WordCamp sites to inject the content. Nevertheless, the content could also be injected via script.

**Comment by westonruter** [comment]
The need to inject content into the offline template is also something that PWA plugin isn't properly facilitating. Right now there is a [`wp_service_worker_error_message_placeholder()`](https://github.com/xwp/pwa-wp/blob/092902c4a2c335053b076956493d987fdc5b5f1b/wp-includes/template.php#L163-L168) function that the `offline.php` template is expected to include. Perhaps this function should do an action as well? 

Perhaps `wp.hooks` could also be incorporated into the service worker to allow filtering the offline template response prior to sending to the browser, which would better enable dynamically-populating the template with content (e.g. list of pages available offline https://github.com/WordPress/wordcamp.org/issues/201#issuecomment-519274408): https://github.com/xwp/pwa-wp/issues/142 

See also https://github.com/xwp/pwa-wp/issues/211

**Comment by ryelle** [comment]
I think the specifics would have to depend on how the the template itself works, we might still want to override the whole thing. For more "average user" cases, an action before & after `wp_service_worker_error_message_placeholder` sounds good (as does the wp.hooks suggestion, though I personally haven't used it as much).
