### ISSUE TITLE
Coming Soon: <title> tag is added twice

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#239]
The Coming Soon template has the title tag hard-coded in the [document head](https://github.com/WordPress/wordcamp.org/blob/production/public_html/wp-content/plugins/wordcamp-coming-soon-page/views/template-coming-soon.php#L6):

```
<title><?php echo esc_html( get_bloginfo( 'name' ) ); ?></title>
```

But WordPress also adds the title tag via an action hooked to `wp_head`. This results in two title tags on the page when Coming Soon Mode is active.

**Comment by terriann** [comment]
A solution discussed with @coreymckrill at WCUS 2019 contributor day is to use [get_theme_support( 'title-tag' )](https://developer.wordpress.org/reference/functions/get_theme_support/) to see if the activated theme does not support `title-tag`, in which case the plugin should output the title HTML tag.
