### ISSUE TITLE
Add security policy

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#247]
[Adding an GitHub-recognized policy](https://help.github.com/en/articles/adding-a-security-policy-to-your-repository) would help make it more obvious and standardized for reporters.

I think it should go in the `.github` folder to avoid cluttering the root. That'll be added by #194, but could be added first here as well.

I think we should leave the existing `Security` section in `/readme.md`, just for added emphasis.

**Comment by timiwahalahti** [comment]
On the same go, we should add [security.txt](https://securitytxt.org/) for all sites.

**Comment by timiwahalahti** [comment]
There's a Slack discussion about `security.txt` since it sounds like it should be available already on wordcamp.org but not working for some reason https://wordpress.slack.com/archives/C02QB8GMM/p1695306901981199

**Comment by iandunn** [comment]
Thanks!

Enabled `security.txt` in `r4578-wordcamp`
