### ISSUE TITLE
Network: Use site meta for flagging sites as beta or testing

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#287]
I saw the improvements to [the network sites screen in 5.3,](https://make.wordpress.org/core/2019/10/15/enhancements-to-the-network-sites-screen-in-wordpress-5-3/) which lead me to [this addition of site meta in 5.1…](https://make.wordpress.org/core/2019/01/28/multisite-support-for-site-metadata-in-5-1/) which all got me thinking about how we flag testing & beta sites. Right now we use functions with lists of sites, like [`get_excluded_site_ids`](https://github.com/WordPress/wordcamp.org/blob/8cc71f2a5c3037b55e0daebf57454645fb8fecaa/public_html/wp-content/plugins/wordcamp-reports/index.php#L355),  [`$blocks_test_sites`](https://github.com/WordPress/wordcamp.org/blob/dbacdfb5f452d74034fb7875aa9e507d16fbc3dd/public_html/wp-content/mu-plugins/blocks/blocks.php#L36) etc. This requires keeping multiple lists of site IDs, and knowing that you need to edit these if you create a new site.

What if instead, we add site meta to each test site, and use that to get the excluded sites? We can use those 5.3 filters add a "test" label to each test site, so we'll be sure which sites are excluded or not. This would probably still be something we set via CLI, but _could_ be a UI setting if needed. Thinking a boolean `is_test` or something.

For beta sites, we could do the same, but also add a UI for organizers to opt in to beta features themselves (or maybe not - I can see arguments for & against this).

**Comment by coreymckrill** [comment]
I think this idea is worth exploring. There are a lot of possibilities for us with site meta. For example, we could also sync values from the WordCamp posts' postmeta on WC Central (e.g. `Start Date`) to the site meta for the site, and then we could eliminate a bunch of lines of code where we have to use `switch_to_blog` to go to Central and retrieve certain data.

**Comment by coreymckrill** [comment]
> also add a UI for organizers to opt in to beta features themselves

I think I would prefer to skip the UI for now. When someone wants to opt in to a beta, we can just add the appropriate blogmeta value via wp-cli.

If we have a feature that we want to be broadly available but we're still calling it a beta, that's when I think we might build a UI for opting in. But then again, assuming it's a new plugin, we could just make the plugin available to organizers for activation and add `(Beta)` to the plugin title.

**Comment by ryelle** [comment]
I wasn't thinking anything fancy, just a list of checkboxes like [the gutenberg experiments page.](https://2017.testing.wordcamp.org/wp-admin/admin.php?page=gutenberg-experiments)

When I suggested it, it seemed like we'd be beta-ing more things, but now it seems like only the schedule block fits into that framework (since SFT is a regular plugin).

**Comment by coreymckrill** [comment]
@ryelle with #449 merged, can I close this issue, or would you prefer to leave it open until Beta flags and/or UI are figured out?

**Comment by ryelle** [comment]
I don't think we need a UI to consider this closed, but we do need a different beta solution — like for the schedule block, we might want to put that on WCUS, which wouldn't be a "test site".

**Comment by coreymckrill** [comment]
So for that case, I think we could add a blogmeta key to WCUS, something like `wordcamp_beta_schedule-block`, and then just use a conditional like

```php
if ( get_site_meta( get_current_blog_id(), 'wordcamp_beta_schedule-block', true ) ) {
    // Activate Schedule block...
}
```

Or we could add another helper function similar to `is_wordcamp_test_site`, maybe something like:

```php
/**
 * Check if a WordCamp site is participating in a beta test of a feature.
 *
 * Currently `wordcamp_beta_` blogmeta keys need to be set manually via wp-cli.
 *
 * @param string $beta The slug ID of the beta feature.
 * @param int|null $blog_id Optional. The blog ID to check. Defaults to current blog ID.
 *
 * @return bool
 */
function is_wordcamp_beta( $beta, $blog_id = null ) {
	if ( is_null( $blog_id ) ) {
		$blog_id = get_current_blog_id();
	}

	return wp_validate_boolean( get_site_meta( $blog_id, 'wordcamp_beta_' . $beta, true ) );
}
```

Thoughts?

**Comment by ryelle** [comment]
I like the helper function approach 👍
