### ISSUE TITLE
Show in Attendance UI If it's Speaker, Volunteer or Assistance

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/wordcamp.org#289]
Nice feature Attendance UI, but it would be very helpful to see which kind of attendance is. Sometimes Speakers and Volunteers have different Swag.

Thanks!

**Comment by ryelle** [comment]
If you use "Admin Flags" for marking these groups, that will show up on the attendance UI page. For example, you can see my ticket is marked as "Organizer" here:

<img width="301" alt="Screen Shot 2019-11-26 at 11 46 17 AM" src="https://user-images.githubusercontent.com/541093/69654330-97452b00-1042-11ea-94c3-43aea4693f76.png">

You can find the Admin Flags settings in Tickets > Setup > Admin Flags (tab). Once you set up the flags, you need to add them to each attendee.

Let me know if that works for you, or if you're having trouble with this.

**Comment by davidperezgar** [comment]
Hello @ryelle !
I think in our WordCamp Granada we have everything set, but it does not show. I don't know if it something is missing...

![IMG_4434](https://user-images.githubusercontent.com/10096360/69719705-5bc56200-1111-11ea-920b-54c3badd566f.PNG)

**Comment by ryelle** [comment]
Hi @davidperezgar – Did this end up working for your WordCamp? I see it was last weekend, I hope it went well!

**Comment by davidperezgar** [comment]
Hello @ryelle ! Everything was fine! The attendance UI works smoothly and it showed the admin flags! Thanks!
