### ISSUE TITLE
Enable order by Coupon in Attendee admin

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/wordcamp.org#290]
In order to use admin flags, is useful to use the column coupon to sort them and then clic to admin flags.

In WordCamps the most of coupons are useful to use admin flags. For example: volunteer, speaker, sponsor or student.

I mean in this url: /wp-admin/edit.php?post_type=tix_attendee

Thanks!

**Comment by ryelle** [comment]
@davidperezgar You can click the coupon name in the Coupon column to only show you people who used that coupon, or you can search the attendees by coupon name. Is there a reason that sorting would be more helpful?

![Screen Shot 2019-12-02 at 12 57 05 PM](https://user-images.githubusercontent.com/541093/69982862-6e6ddb80-1503-11ea-98ef-6a369253715b.png)

**Comment by davidperezgar** [comment]
Ok! Thanks!
