### ISSUE TITLE
TwentyTwenty SmoothScrolling issue with CampTix

### ISSUE THREAD

**Issue by mauteri** [WordPress/wordcamp.org#293]
Posted this in #meta-wordcamp and in Trac https://core.trac.wordpress.org/ticket/48763#comment:17

Issue related to SmoothScrolling... I noticed this with our WordCamp site using the new Twenty Twenty theme with CampTix plugin.

When you sign up and receive your WordCamp ticket, you are sent an email with "Edit Information" from what you provided. That link looks something like this...

https://2020.WORDCAMP.wordcamp.org/tickets/?tix_action=access_tickets&tix_access_token=TOKEN#tix

Since it's the same URL and ends with a hash, the JS code for SmoothScrolling takes over so you cannot actually load the link to edit your information. In addition to checking that the URL is the same, you should also check for different URL parameters for cases like this.

Using Twenty Twenty theme, this bug prevents anyone from updating their information after buying a ticket. I can't write any JavaScript to fix the issue. Curious if WordCamp Central is able to patch this issue while the core-theme fixes it in the theme. Is there a process for issues like this? Thanks!

**Comment by mauteri** [comment]
This looks like it will be fixed in this trac ticket. The patch is moving smooth scrolling from JS to CSS. https://core.trac.wordpress.org/ticket/48763

**Comment by ryelle** [comment]
I've added the `do-not-scroll` class to these edit links in https://github.com/WordPress/wordcamp.org/commit/3644a9689466fbdf4f58ee74b85df40a3936d0ee — this creates a work-around so that these links work now, and can be removed once the theme itself is fixed.

I'm going to leave this issue open so we remember to remove the workaround when we can.

**Comment by mauteri** [comment]
Confirmed working. Thanks Ryelle!
