### ISSUE TITLE
WordCamp Central: Add global sponsors widget to homepage

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#306]
Replace the Latest Tweets widget on the WordCamp Central homepage with a Global Sponsors widget that shows Gold global sponsor logos. Two different ideas for presentation:

* An auto-advancing slider (every 3-5 seconds) 
* Either a random single sponsor logo or a randomized list of three every time the page is reloaded.

More info:
https://make.wordpress.org/community/2020-wordpress-global-community-sponsorship-program/

Screenshot of location for the widget:
![central_hp](https://user-images.githubusercontent.com/916023/71861027-ba371600-30a9-11ea-9d22-d3df5f26d69e.jpg)

**Comment by coreymckrill** [comment]
My preference would be to go with second option for presentation ([because.](http://shouldiuseacarousel.com/))

Regardless of which presentation we go with, we'll need to randomize the list of Gold sponsors for fairness, and we'll need to do it in a way that doesn't run afoul of caching. Seems like we could take a similar approach to [how Five for the Future pledges are randomized](https://github.com/WordPress/five-for-the-future/blob/a70212bc2275240ff5f317ee5d6f9b9d47d04f3a/plugins/wporg-5ftf/includes/pledge.php#L444-L447).

**Comment by coreymckrill** [comment]
@melchoyce Do you have the bandwidth right now to whip up a quick design for this sponsors widget (and also chime in on slider vs single logo vs list?)

**Comment by melchoyce** [comment]
I just moved teams, but I talked to @karmatosed and she has some time to look into this :)

**Comment by karmatosed** [comment]
I would agree about this:

> Either a random single sponsor logo or a randomized list of three every time the page is reloaded.

I don't think a slider would look as good and the impact would be a lot. My recommendation would be to have 3 but 1 could also visually work.

![image](https://user-images.githubusercontent.com/253067/72100483-9fb7a380-331a-11ea-9d87-ac75edf29734.png)

**Comment by coreymckrill** [comment]
Thanks @karmatosed 

Do you think the sponsor items should just be the logo, or should they include, e.g. name, URL?

If it's just the logo, perhaps it would be best to just have one at a time, and make the width fit the column width. Thoughts?

Edit: See the pull request #314

**Comment by karmatosed** [comment]
> Do you think the sponsor items should just be the logo, or should they include, e.g. name, URL?

I think if you have more information you could also consider distilling back to just one. Having URL and name does avoid problems of logos not being representative.
