### ISSUE TITLE
Camptix: 2 fuzzy translations about "Coupon applied" string

### ISSUE THREAD

**Issue by imath** [WordPress/wordcamp.org#307]
**Describe the bug**

Hi,

These strings are no more translated on WordCamp.org sites.
- https://github.com/WordPress/wordcamp.org/blob/production/public_html/wp-content/plugins/camptix/camptix.php#L5361
- https://github.com/WordPress/wordcamp.org/blob/production/public_html/wp-content/plugins/camptix/camptix.php#L5530

I believe this is due to the fact the l10n placeholders have been edited in the code and probably not updated into the language pack.

Before these strings used to use the `%s` placeholder (See: https://github.com/WordPress/wordcamp.org/blob/production/public_html/wp-content/plugins/camptix/languages/camptix.pot#L1603). There are now using the `%1$s` and `%2$s` placeholders.

**To reproduce**
Just try to apply a coupon on any non 'en_US' WordCamp Site.

**Expected behavior**

Strings should be translated into the site's locale

**Screenshots**

![bug-camptix](https://user-images.githubusercontent.com/1834524/71887540-9f62b100-313e-11ea-889c-ec4abc9daea6.png)

**WordCamp**

https://2020.paris.wordcamp.org/billetterie/ (so far published in private)

**System (please complete the following information):**

 - Device: laptop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79.0.3945.79

**Security Issues**

To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by fxbenard** [comment]
@imath Good catch.
It should be nice to add some translator comments as well now to explain those 2 placeholders.
Thanks.

**Comment by ryelle** [comment]
These new strings [have been translated,](https://translate.wordpress.org/projects/meta/wordcamp/fr/default/?filters%5Bterm%5D=Coupon+Applied&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) it looks like we need to update the translations on WordCamp.org.

**Comment by ryelle** [comment]
Translations have been updated, so this is should be correct now. Thanks for reporting this!

**Comment by imath** [comment]
Hi @ryelle thanks a lot for the fix. I confirm it's now translated on https://2020.paris.wordcamp.org/billetterie/ 💪
