### ISSUE TITLE
Schedule Block: Add support for favorite sessions

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#311]
Need to incorporate the same personalized-schedule-building tool that the shortcode supports.

Check if there are any bc-breaking changes that would be helpful, since this would be a good time to do those. The tool should still work on the shortcode, though, but we might build a slightly different interface for the block, or something.

**Comment by ryelle** [comment]
If we're looking at any UX changes, it would be good to get a designer's feedback too.

This would be a good time to improve [the a11y issues of the print/share modal,](https://meta.trac.wordpress.org/ticket/4247) copying over the relevant comment:

> - The mail/print/share option should be activated by a `<button>`, not an `<a>`
> - The div with the mail/print/share option should be an accessible dialog modal
> - The tab interface inside is not keyboard accessible
>
> The color contrast of the star itself is also still too low (hasn't changed), but considering we don't know what theme/background someone will be using, this might need some thought. Good contrast against the default BG of Twenty Twenty would be a good start.

**Comment by iandunn** [comment]
Done in 0141ba45e06ddd135690f6a12495a6ae1177bd30.

There weren't any UX/design changes, it's just some minor tweaks so that the code can support both the block and the shortcode.

**Comment by ryelle** [comment]
Can this stay open to track the accessibility issues? or can you open a followup issue?

**Comment by iandunn** [comment]
Aren't they already being tracked in https://meta.trac.wordpress.org/ticket/4247 ?

**Comment by ryelle** [comment]
yeah, I suppose that'll get moved over when we migrate all the tickets.
