### ISSUE TITLE
Wildcard Certificate is Expired (since April 2018)

### ISSUE THREAD

**Issue by jrchamp** [WordPress/wordcamp.org#318]
**Describe the bug**

An expired wildcard certificate is being offered for "unknown" domains.

**To reproduce**

1. Go to https://example.wordcamp.org/
2. See browser error

**Expected behavior**

I would expect a friendly error message from wordcamp.org

**Comment by iandunn** [comment]
This is also -- maybe more often? -- a problem with 4th-level domains, like 2020.seattle.wordcamp.org. `2019` exists, but the site for `2020` hasn't been created yet.

It looks like [Let's Encrypt supports wildcard domains now](https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579) 🎉 

We'll need to wait until after we upgrade to ACME v2, though.

**Comment by jrchamp** [comment]
Thanks @iandunn - indeed, I did notice this while trying to plan ahead for a - currently non-existing - 2020 event.

**Comment by coreymckrill** [comment]
We have now upgraded to ACME v2. I just tried the example URL and did not see an SSL error. It just redirects to central.wordcamp.org.

I'm going to call this one closed, but please reopen if you think there's still an issue here.
