### ISSUE TITLE
Application tracker: validate wordpress.org username before save

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/wordcamp.org#320]
Right now application tracker validates the existance of wordpress.org username when saving the post and thowrs an `wp_die` if username does not exist.

Given that the applicants do fill invalid usernames _all the time_. `wp_die` slows down the vetting process. Escpecially if you have written a note to application, because that dissapears when going back and you need to re-write the note.

Username should be validated already when rendeding the application details and add warning or some visual reference that the saving process will die.

**Comment by ryelle** [comment]
Looks like the code that added this was  https://github.com/WordPress/wordcamp.org/commit/8fb0610b11e86996e3a34f2f04f7a0b786d48193 (cc @iandunn) — additionally, it only checks the username fields used on Meetups, so I tested this for about 10min on WordCamps wondering why I couldn't trigger the validation. However this is fixed, the same validation should happen on both Meetup & WordCamp applications.

**Comment by timiwahalahti** [comment]
Closing as this is not valid anymore after we started requiring WordPress.org login before submitting an application on #523
