### ISSUE TITLE
Speaker sumbission form WordPress.org login not kicking in

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/wordcamp.org#332]
**Describe the bug**

Looks like the `wordcamp-forms-to-drafts` plugin isn't requiring WordPress.org login and filling the username field automatically anymore. At least this is the case on a fresh site inside the docker development environment.

It's because the Call for Speakers post is nowadays created as a Gutenberg post and the functionality that adds the login wall seeks for the shortcode to wrap.

**To reproduce**

1. Create a fresh WordCamp site
2. Activate Jetpack forms
3. Publish "Call for Speakers" post
4. Open the post in private browsing
5. You are able to submit the form without wordpress.org login

**Expected behavior**

The form should have a layer on top of it asking to login with WordPress.org before being able to fill the form and submit it.

Somewhat related to #321, where asked to add the login layer to Meetup application form.

**Comment by timiwahalahti** [comment]
I'd like to have someone confirming this before moving on with fixing and submitting PR. Thanks!

**Comment by ryelle** [comment]
This is also letting spam submissions through, so fixing it should be a higher priority.
