### ISSUE TITLE
Speaker Feedback: Create an API endpoint for feedback-comments

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#337]
We can't use the core `/comments` endpoint, because it doesn't support custom comment types. We'll need to create our own - though we can use comments `WP_REST_Comments_Controller` as a base.

This endpoint only needs to create comments, since we don't have a view for editing or deleting existing feedback (from the frontend).

Comments will have meta, this should also be registered with this endpoint:

- The star rating, integer 1-5
- The question answers, an array of objects `[ { question, answer }, … ]` where `question` & `answer` are strings.
- Anything else TBD?

Make sure it still uses whatever hooks are necessary for Akismet to check the content (and meta).

**Comment by coreymckrill** [comment]
> The question answers, an array of objects

I was thinking each question/answer pair would be a separate entry in comment meta. That seems like it would reduce the complexity when, e.g., querying for all the answers to one particular question.

**Comment by ryelle** [comment]
My initial thought was still separate entries in comment meta, but for all the same key (hence the array). But still, this made more sense when there was the possibility of changing the question text, so answers would be stored with the correct question content.

I still think storing the question text will be important, but maybe we can figure out another way to do that.
