### ISSUE TITLE
Speaker Feedback: Create custom comment type

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#338]
Create the custom comment type for saving feedback data. This will be attached to the session post type.

**Comment by coreymckrill** [comment]
There isn't actually a way to register a custom comment type, though it appears that this 4-year-old Core issue has been getting some traction lately:

https://core.trac.wordpress.org/ticket/35214

My thought is to create an abstraction layer via some functions for CRUD operations involving our custom comment type. That way it's easy to adapt if/when custom comment types make their way into Core.
