### ISSUE TITLE
Speaker Feedback: Display feedback in wp-admin, using comments screen

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#339]
WordCamp organizers should be able to view feedback in wp-admin, using the comments screen. The meta should be combined on the fly to render a human-friendly view of feedback:

![Speaker Feedback](https://user-images.githubusercontent.com/541093/73205988-0d800f80-4110-11ea-9819-d3d52ffd9f94.png)

Organizers can spam feedback from this view.

**Comment by coreymckrill** [comment]
Related: #340

**Comment by coreymckrill** [comment]
Checking some assumptions here:

The way I'm reading the description of this issue, it sounds like the idea is that feedback comments would appear mixed in with other types of comments on the **wp-admin/edit-comments.php** screen. And then perhaps the comment meta for feedback would be injected into the list table rows via JS.

I think this would be pretty challenging to pull off in a non-hacky way:

* The comments screen and the comments in the list table are viewable by roles as far down as Contributor (though the comments can only be modified by Editor and above). My understanding is that we only want Admins (and maybe Editors) to even see feedback comments.
* The mockup shows different columns/headers for feedback than for normal comments. I'm not sure how we would do that if they are mixed together.
* The header labels in the Comments list table are not filterable, so even if we just had the feedback comments be accessible via the Comment Types select filter, we'd have to update the headers via JS.

An alternative that I have been considering is preventing feedback comments from appearing in the normal Comments list table at all, and instead creating a separate sub page (potentially under Sessions) that contains a list table that is _extending_ the Comments list table class, but with customizations. It might be a bit more work, but then we could avoid gotchas from assumptions that Core is making with the normal Comments screen.

Thoughts, @ryelle ?

**Comment by ryelle** [comment]
I had a few vague thoughts, nothing too researched, and I'm not tied to any of it, but for argument's sake, this is what I'd been thinking:

We'd filter feedbacks out of the general comments screen somehow, and only show them when showing a single session's replies, `/edit-comments.php?p=43` where 43 is a session ID… maybe figure out some other query param to show all feedbacks. This idea of "anyone can see comments" is part of what fixing #340 is meant to address.

I think the heading labels are pretty flexible, so I wouldn't worry as much about replacing those. It would just be adding a new column for rating.

> And then perhaps the comment meta for feedback would be injected into the list table rows via JS.

Not by JS, but with the `comment_text` filter… we'd probably do most of our "work" in this filter, showing the feedback meta, adding it 'helpful/unhelpful' actions, etc.

--------------

That said, I think maybe your alternative Comments screen for Session -> Feedback is a good idea, though I'm not sure it would really get away from core assumptions, it would be worth experimenting.
