### ISSUE TITLE
Speaker Feedback: UI for speakers to review their feedback

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#347]
The [scoping document](https://make.wordpress.org/community/2020/01/27/speaker-feedback-tool-final-outline/) says:

> An option will be added to allow this feedback view to be shared with the speaker. Speakers can be sent an email with a unique URL that can be used to view the feedback. We could also allow speakers to access the feedback directly if we have their WordPress.org username, and they are logged into the site.

And:

> Speakers will receive a link from the organisers to view their feedback. We can add a “Was this feedback useful?” question for the speaker to submit as a way of tracking the value of the feedback.

But this still leaves some questions:

* Will this view live on the frontend of the site, or the backend?
  * If the frontend, where would the content be displayed? How would it be styled?
    * A dedicated page that shows feedback for whichever wporg user is currently logged in?
    * On the session page, in a section that is only visible to the speaker, via login or access key query parameter?
  * If the backend, speakers would probably need to be added as users on the WordCamp site and be logged in in order to access their feedback.

---

### Update

After discussion on this issue, the current plan is:

* Speakers can view feedback on their session by going to the same URL where attendees go to leave feedback, i.e. `2020.city.wordcamp.org/my-cool-session/feedback`.
* They must be logged into the WordPress network. Then we can detect that the current user is one of the speakers on the current session, and replace the feedback form with a list of the feedback that has been moderated and approved by the organizers.
* This could also show the speaker if there is feedback that _hasn't_ been moderated yet, so that they can bug organizers about it.
* This is also where speakers would be able to mark specific feedback comments as "helpful" (see #342)

For a live example of the current feedback page, see [2017.testing.wordcamp.org/session/demo/feedback/](https://2017.testing.wordcamp.org/session/demo/feedback/)

**Comment by ryelle** [comment]
I was under the impression this would be the backend, hence why we're doing #340 — the "UI for speakers to review feedback" is just the "my feedback" view of the comments list table in wp-admin. (340 is the issue I created to cover this bullet point from the scope doc)

> If the backend, speakers would probably need to be added as users on the WordCamp site and be logged in in order to access their feedback.

Yeah, I think that's part of #340 — working out the permissions to make this work. I thought we said somewhere that it would be OK that this is requiring a wporg login, since we technically "require" that of speakers already.

_I'm removing needs design until we come to a decision, just so no designers pick this up while we're still figuring it out._

**Comment by hlashbrooke** [comment]
I think backend makes more sense because feedback will be viewable in there anyway. I was thinking some kind of tokenised link could work where the token checks their username and allows them access to view, but you would probably still need to add them as a user to the site (even if they're just in the `contributor` user role).

**Comment by coreymckrill** [comment]
My biggest concern with the backend is the need to add each speaker as a user on the site. It should be possible to do this programmatically when the speaker's wporg username is added to the speaker post, but we still can't _depend_ on those users being there when it's time to notify them about their feedback. There are lots of reasons a user could get removed.

So I guess we will just need to ensure that none of the code assumes that the user will exist on the site, and possibly also provide some UI around user existence. Maybe in the metabox on the Speaker post type where you add the wporg username, if the field is filled but there is no corresponding user on the site, show a warning and a button to quickly re-add them?

**Comment by hlashbrooke** [comment]
> Maybe in the metabox on the Speaker post type where you add the wporg username, if the field is filled but there is no corresponding user on the site, show a warning and a button to quickly re-add them?

I think that would be a big help yeah.

The other option would be to show the feedback on the frontend as comments on the session post, but make them only visible if the speaker is logged in to wp.org. The downside there is that the speaker could easily see the feedback before the organisers have been able to moderate it, but it would mean we don't need to worry about users and wp-admin permissions.

**Comment by coreymckrill** [comment]
> The downside there is that the speaker could easily see the feedback before the organisers have been able to moderate it, but it would mean we don't need to worry about users and wp-admin permissions.

So, comments have two built in statuses that could help us here. "Hold" and "Approved". We could have new feedback submissions default to "Hold" instead of "Approve", and then only showed approved ones to speakers. So the comments would have to be moderated by organizers first.

We could even show a message to speakers like "This session has feedback that hasn't been moderated yet" or something, so they know to go bug the organizers.

**Comment by hlashbrooke** [comment]
That sounds like a good solution.

I guess my only concern with having to moderate every comment (and this isn't specific to this issue about where to display the feedback) is that it's a big ask for organisers to moderate every piece of feedback, especially for larger camps like WCEU, etc. I don't think we can work around that though, as one of the guidelines in the handbook is to not allow speakers to see unmoderated feedback. We might need to add a bulk approve button for each session's feedback to make things less onerous for organisers.

**Comment by coreymckrill** [comment]
As of 69d9e1f0647c9ac6f5c258dd20fa6414ba3ecb16, bulk moderation of feedback comments by site admins/editors is possible. I can't tell if we actually made a decision on this issue (so I guess that means no!) My preference would be to show _approved_ feedback comments to the logged in speaker when they view the front end single session post (possibly with another custom endpoint tacked on the URL, similar to the one for accessing the feedback form), plus a notice of how many _unapproved_ comments are still waiting. This way we wouldn't have to deal with adding each speaker to the site and giving them appropriate access to the back end.

**Comment by coreymckrill** [comment]
Related: #342

**Comment by coreymckrill** [comment]
> possibly with another custom endpoint tacked on the URL, similar to the one for accessing the feedback form

Taking this a step further. Speakers aren't going to leave feedback for themselves. Could we use the same endpoint, but if the logged in user is a speaker for the session, it shows them the UI for viewing their feedback instead of the form to leave feedback?

**Comment by ryelle** [comment]
So, a logged-in speaker would go to `some.wordcamp.org/sessions/my-session/feedback`, and (assuming everything's hooked up), we know they're the speaker for that session, so we can show them the "comments list" of feedback in place of the form? I think that's a good solution 👍 

We'll probably want a designer's input on this, before building anything if possible, but definitely on the PR.

**Comment by coreymckrill** [comment]
Yep, that's what I'm envisioning.

> We'll probably want a designer's input on this

Agreed. If this is on the front end, it might not make sense to use the List Table UI for this, so we definitely need some design help.

**Comment by ryelle** [comment]
My first thought about what this could be, very hacked-together: a straight list of feedback using a similar layout to regular comments. Still needs ratings added, and maybe an aggregate rating at the top (across from feedback?) Sharing as a jumping-off point, but all this could be changed if necessary 🙂 

![Screen Shot 2020-04-06 at 1 25 38 PM](https://user-images.githubusercontent.com/541093/78586900-2b51ab00-780a-11ea-9846-81a195bae6c0.png)

**Comment by coreymckrill** [comment]
Oh interesting. In this case, maybe we could use `wp_list_comments` with a custom walker class to include the meta data in the output, and then the theme would handle some/most of the styling.

**Comment by enriquesanchez** [comment]
Here's a mockup iteraring on @ryelle's initial idea:

<img width="768" alt="Frame 1" src="https://user-images.githubusercontent.com/3276087/78601947-382aca80-781b-11ea-81a7-e03ee3603860.png">

Please let know what y'all think. Happy to make any necessary changes.

I'm listing under the speaker and session names the number of approved and pending reviews. I think this text could be a bit more clear. If you have any suggestions please do.

**Comment by enriquesanchez** [comment]
I'm thinking it may also be a good idea to show the date of the talk/session somewhere on this page. I think those could be particularly useful when a speaker gives the same talk at different events/dates.

**Comment by ryelle** [comment]
Thanks for the quick turnaround, I really like this! I'm about to have a bunch of nitpicks though.

So, ideally the top part of the session page wouldn't change, since we're trying to stay within the current session template. Using WCUS last year as a "real example", this is what we're working with:

![Screen Shot 2020-04-06 at 4 41 38 PM](https://user-images.githubusercontent.com/541093/78603759-ade86380-7826-11ea-8f88-ecaf9d183165.png)

There can also be multiple speakers per session (like a panel), but feedback is left on the session level, for everyone. So the header you've got wouldn't work in that case, I think.

👍  for the "X approved, X pending review" text — we could add something like "get in touch with the organizer to approve them" if there are pending… that can be iterated on.

We aren't marking feedback as not helpful, but we could probably just drop the  👎  button.

Each feedback also has a 1-5 star rating value— I'm not sure if we want to show speakers each individual rating, or just an average, or both.

**Comment by enriquesanchez** [comment]
@ryelle thanks for the clarification. I'll work on these changes.

**Comment by enriquesanchez** [comment]
Hi @ryelle 

Here's an iteration based on your feedback:

<img width="940" alt="Frame 2" src="https://user-images.githubusercontent.com/3276087/78607465-b8096280-7824-11ea-9f4f-7dcef5b53938.png">

>There can also be multiple speakers per session (like a panel), but feedback is left on the session level, for everyone. So the header you've got wouldn't work in that case, I think.

I'm now using the WC2019 website layout and style. Let me know if this works better.

>We aren't marking feedback as not helpful, but we could probably just drop the 👎 button.

I've updated this and kept the theme's style. Let me know how this feels to you.

>Each feedback also has a 1-5 star rating value— I'm not sure if we want to show speakers each individual rating, or just an average, or both.

I added both to the mockup, I think it works well but I'll let others decide. I'm using emoji for the stars, but we can also use any other icon we want. I don't think these have enough contrast.

**Comment by enriquesanchez** [comment]
How many feedback submissions are we expecting to have shown here? I'm wondering if we should be thinking about cases where there are too many. Should show a few and collapse the rest, for example, show 5 and then a "View 23 more" link that expands them?

**Comment by coreymckrill** [comment]
> How many feedback submissions are we expecting to have shown here?

Really no idea how many a session will typically get, but I imagine at larger events there could be 50+ feedback comments for one session. In that case, I'm hoping we can either use pagination or something like you're describing, with a Load More button that loads the next batch.

**Comment by coreymckrill** [comment]
I wonder if it would be worth having filtering and sorting options here as well. I could see speakers wanting to filter to only show comments they've marked as "Helpful", or sort by the rating.

**Comment by enriquesanchez** [comment]
Did some overall tightening of spacing and colors. Also updated the user's name to be a link that directs to their profile. Are we using profiles?

<img width="409" alt="Screen Shot 2020-04-06 at 18 00 57" src="https://user-images.githubusercontent.com/3276087/78613180-bd6caa00-7830-11ea-9dfb-36b08da73a42.png">

**Comment by enriquesanchez** [comment]
>I wonder if it would be worth having filtering and sorting options here as well

@coreymckrill I think this is a great idea. I'll work on this tomorrow 👍

**Comment by enriquesanchez** [comment]
@coreymckrill @ryelle here's a little update showing sorting/filtering options. I feel we should keep these as simple and basic as possible. I'm thinking the the 'Sort by' dropdown, we could include a few options such as `Oldest first`, `Newest first`, `Highest rated first`, etc. What do you think?

<img width="966" alt="Screen Shot 2020-04-07 at 15 05 24" src="https://user-images.githubusercontent.com/3276087/78714312-46dbb500-78e1-11ea-87ec-f6c931d74cd8.png">
