### ISSUE TITLE
SVG are stripped out of social block in speakers list block

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/wordcamp.org#349]
There’s a problem with the speakers list block. The SVGs aren’t being loaded within the social links. They’re created in the individual speaker content, where they’re showing correctly. https://2020.geneve.wordcamp.org/orateurs-trices/

**Comment by ryelle** [comment]
The link above has been updated with a workaround, so this is a screenshot of the issue:

![Screen Shot 2020-01-31 at 2 28 21 PM](https://user-images.githubusercontent.com/541093/73568319-2e10d800-4436-11ea-93e2-e5461b204ba1.png)

The Social Links block lets you add social info to a post, which seems really useful for a speaker— but the icons are [rendered dynamically as SVGs.](https://github.com/WordPress/gutenberg/blob/6aa99448790033f46808a9d8357f712d79d44b97/packages/block-library/src/social-link/index.php#L15-L27) Our `wp_kses_post`s strip out the SVGs, leaving just an empty `a` (which is still styled & has the backgroud color, hence the empty blue space). I imagine we don't want to add all the `svg` values to `allowed_html`, and removing the sanitization is probably also out.

I tried adding a social links block to a post, then used the Latest Posts block to see how core handles this. It doesn't render dynamic blocks at all — no mystery blue circle, but also nothing else. I'm not sure if I'd consider that the "expected" failure, or if outputting at least some of it is better.

@iandunn @coreymckrill Any ideas?

----

For reference, latest posts uses this to output post content:
```php
wp_kses_post( html_entity_decode( $post->post_content, ENT_QUOTES, get_option( 'blog_charset' ) ) )
```

**Comment by coreymckrill** [comment]
I don't have any good ideas yet, but just noting that `wp_kses` is causing other problems in this context as well. For example, it strips out `srcset` and `sizes` attributes on image tags.

**Comment by iandunn** [comment]
I think Kelly's on the right track. It seems best to either not render dynamic blocks at all, or do the sanitization _before_ dynamic blocks get rendered.

I'm leaning towards the latter, since the sanitization is only intended to sanitize _user_ input.
