### ISSUE TITLE
Blocks: FeaturedImage component

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#36]
Here are remaining issues I see with this component, including some based on unresolved discussions from #33:

- [x] The options for the size dropdown are still hard-coded and seemingly arbitrary. There are a few unresolved discussions that mention this ([#](https://github.com/WordPress/wordcamp.org/pull/33#issuecomment-471054545), [#](https://github.com/WordPress/wordcamp.org/pull/33#issuecomment-474642728), [#](https://github.com/WordPress/wordcamp.org/pull/33#pullrequestreview-216908295), [#](https://github.com/WordPress/wordcamp.org/pull/33#pullrequestreview-216909004)). I think we should either populate with the site settings for media sizes, or consider switching the size controls over to the same UI used for avatars (see AvatarSize component).
- [x] Images shouldn't be scaled up beyond their actual dimensions. If the width option is set to 600 but the full size of an image (via details from the REST API) is only 394, the width attribute for that image should be 394, not 600.
- [x] The HTML markup, especially class names, should be consistent between the front end and the back end. (Edit: Being fixed in #66 )
- [x] Consider moving `render_featured_image` to **includes/shared.php** ([#](https://github.com/WordPress/wordcamp.org/pull/33#discussion_r266133019))  (Edit: Being fixed in #66 )

**Comment by coreymckrill** [comment]
The more I think about it, the more I think we should use the same UI for the size that we do for avatars. What do you think of that, @vedanshujain? Maybe we could abstract the AvatarSize component and rename it so that it could work for both scenarios.

That would only affect the stuff in the Inspector panel, not the actual FeaturedImage component.

**Comment by vedanshujain** [comment]
>  Images shouldn't be scaled up beyond their actual dimensions. If the width option is set to 600 but the full size of an image (via details from the REST API) is only 394, the width attribute for that image should be 394, not 600.

I wonder if that's a good idea, because it seems to go against WYSIWYG.

**Comment by coreymckrill** [comment]
> because it seems to go against WYSIWYG

🤔 I guess either way, the image doesn't look great in the context of the other featured images that do have the right width and resolution. @melchoyce any thoughts here on expected behavior?

To clarify, if we're setting the width of the featured images for a group of sponsor posts, should images that have a lower original width than our setting be displayed at their maximum width, or at the width we set, and be pixelated?

**Comment by melchoyce** [comment]
Left a note about this on #62.

**Comment by vedanshujain** [comment]
Most of this is fixed. Some discussion in https://github.com/WordPress/wordcamp.org/issues/62 . Closing this one.
