### ISSUE TITLE
Event Applications: Review fields & metabox display for usefulness

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#372]
WordCamp & Meetup applications create new posts in wp-admin when the form is submitted. These posts expose some of the application fields as inputs in the editor, but not all of them. For example, partial screenshots:

**WordCamp**
![Screen Shot 2020-02-18 at 5 46 53 PM](https://user-images.githubusercontent.com/541093/74784801-bdabe880-5276-11ea-9d65-3dffd1a7992c.png)

**Meetup**
![Screen Shot 2020-02-18 at 5 47 58 PM](https://user-images.githubusercontent.com/541093/74784841-d61c0300-5276-11ea-9bf3-53973628fa1d.png)

But application reviewers know this is is a subset of data, so they use the "Original Application" data dump:
 
![Screen Shot 2020-02-18 at 5 50 55 PM](https://user-images.githubusercontent.com/541093/74785020-488ce300-5277-11ea-9fa2-50978e58ba18.png)

We could make this a nicer experience:

- Better formatting of the data dump?
- Updating the fields in the other metaboxes to show all the full set of application data?

Would need to know which fields are not currently used, which fields should be populating from the application, and which fields are missing (in the application data, but not currently in the form UI).

**Comment by timiwahalahti** [comment]
> Updating the fields in the other metaboxes to show all the full set of application data?

Most of the data in applications aren't needed anywhere else than in the vetting process, so it does not really make sense to fill other metaboxes with one-use-only fields.

> Better formatting of the data dump?

👍👍👍

> Would need to know which fields are not currently used, which fields should be populating from the application, and which fields are missing (in the application data, but not currently in the form UI).

I can make a list of these for Community Team deputies to review and share their opinions. After we have agreed about fields, I could also work on PR.

**Comment by ryelle** [comment]
> I can make a list of these for Community Team deputies to review and share their opinions

That would be great!

**Comment by timiwahalahti** [comment]
Fixed in #536 so closing.
