### ISSUE TITLE
Tagregator: Determine how many WordCamps are actually using it

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#373]
This issue is for followup on [a Slack discussion](https://wordpress.slack.com/archives/C08M59V3P/p1582222389267700) in #meta-wordcamp. It would be useful to find out how many camps are actually making it through the process of setting up Tagregator with API keys for various social media platforms and using the functionality.

This could probably be done by writing a script that cycles through all the sites in the WordCamp.org network and tallying which ones have A) filled in API key values in the settings, and B) changed the hashtag in the shortcode, or otherwise customized the associated page from the default stub content.

**Comment by timiwahalahti** [comment]
Not sure if this is still valid after the decision made in #847

**Comment by iandunn** [comment]
👍🏻
