### ISSUE TITLE
CampTix Badge Generator: Gravatar Hovercards should be disabled

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/wordcamp.org#375]
_This ticket was moved from [Trac](https://meta.trac.wordpress.org/ticket/2145)_

They get in the way and don't add any value.

**Comment by timiwahalahti** [comment]
Couldn't reproduce this anymore. If someone can check and confirm before closing the ticket, would be much appreciated :)

**Comment by ryelle** [comment]
I also can't reproduce this, so I think it can be closed.
