### ISSUE TITLE
Send email about GPL vetting after first call has been published

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/wordcamp.org#377]
There have been some discussions on tracking when each WordCamp has their calls (sponsors, speakers, volunteers) open.

After this feature has been made and pushed out, it would be awesome to send an automated email outlining the importance of GPL vetting and practical instructions for that after the first call has been opened.

The email could be sent to lead organizer, sponsors wrangler and speakers wrangler after the first call has been opened. We don't want to send the email right after the creation of the site because then happens already enough.

There hasn't been a P2 discussion yet, I'm opening this ticket to log the idea. When we can actually track the call situation, the P2 proposal will be posted.

**Comment by coreymckrill** [comment]
> an automated email

It sounds like this would be a good candidate for the Organizer Reminders functionality we have on WordCamp Central. It's probable that we wouldn't even need to write any code for this, the existing functionality would probably be sufficient.
