### ISSUE TITLE
Comma in Select option treated a separator and creates new option

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/wordcamp.org#418]
**Describe the bug**
When a comma is used in a Form's Select option, the portion of the option after the comma is treated as a new option.

**To reproduce**
1. Create a page with a Form and a Select block
2. Add three options as seen below in my screenshot.

**Expected behavior**
Three options

**Screenshots**
Editor View:
![image](https://user-images.githubusercontent.com/3489003/78272837-a564f580-74d3-11ea-952a-40d93d0486b8.png)

Page View: 
![image](https://user-images.githubusercontent.com/3489003/78272960-caf1ff00-74d3-11ea-87bb-fb583c57983f.png)

Source: 
![image](https://user-images.githubusercontent.com/3489003/78272971-cf1e1c80-74d3-11ea-8811-84edf4480df2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 80

**Additional context**
WordPress: Version 5.3.3-alpha-47419

Originally reported as https://github.com/WordPress/gutenberg/issues/21356

**Comment by ryelle** [comment]
It looks like this is actually an issue in Jetpack— https://github.com/Automattic/jetpack/issues/7633, and goes back to the shortcode https://github.com/Automattic/jetpack/issues/2917 . If you can work around it by not using commas, that's probably your best bet.

**Comment by CdrMarks** [comment]
Yes, we were able to remove the comma from the value to workaround this.  

Thank you for reporting this on the Jetpack repo.  I knew Forms were part of Jetpack and should have looked there first.

**Comment by coreymckrill** [comment]
Closing this in favor of the upstream issues.
