### ISSUE TITLE
Speaker Feedback: Allow logged-in speakers with no role on a site to view their feedback

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#425]
Speakers who are logged into the WordCamp.org network should be able to view their feedback on a WordCamp site without the organizer needing to add them as a user. Right now our meta capabilities mapping specifies that if the current user is a speaker for the current session, the only capability they need is `read`, but this still implies that they have been added as a user on the site.

A couple of potential ways to fix this:

* Map to some universal capability instead of `read` (not sure if this actually exists)
* Assign a custom capability to the speaker at the same time that we map it.

**Comment by ryelle** [comment]
Another issue I noticed today is that site admins can view speaker feedback too— I haven't tested enough to see if this is just a super-admin power, though. We'll want to make sure organizers see the form, not the feedback list.

**Comment by coreymckrill** [comment]
🤔 Organizers have to see the feedback list so they can approve each comment before it's shown to speakers...

**Comment by ryelle** [comment]
In wp-admin, right— but on the frontend (in the PR I haven't pushed yet 🤦🏼‍♀️) I'm checking `if ( current_user_can( 'read_post_' . COMMENT_TYPE, $post->ID ) ) {` to decide whether to show the feedback form or the feedback list. Maybe I should just check the speaker IDs agains the session directly?

**Comment by coreymckrill** [comment]
Oh, gotcha. Yeah, I would just check against the session directly. All the meta caps assume that site admins can see stuff too.
