### ISSUE TITLE
Make block icons consistent across all blocks.

### ISSUE THREAD

**Issue by vedanshujain** [WordPress/wordcamp.org#43]
`[MUST]` - @vedanshujain , what's the reason that this is done differently than Speakers? Here it's hardcoded instead of pulling in the `icon` from `this.props`.

It seems like it'd be better to have it DRY like Speakers, but the larger issue is the inconsistency. I think in these cases we need to discuss the two approaches, come to a consensus on the best one, and update all the blocks to use it, so that everything is consistent.

In cases where something is clearly better and it's unlikely that there'd be any disagreement, it's also totally fine to just go ahead and adopt it (since we can always revert if there is a disagreement and we change our minds), but it's still important to update the other components to be consistent, and then give everyone a heads up.

In this case, I'm working on updating the icons per https://github.com/WordPress/wordcamp.org/pull/33#discussion_r267058114, so I'm gonna go ahead and change this to be consistent w/ the others. If there's a reason to change them all to this approach, though, we can definitely start a discussion about that.

_Originally posted by @iandunn in https://github.com/WordPress/wordcamp.org/pull/33_

**Comment by iandunn** [comment]
Doh, I should have created new issues for these, good idea!

**Comment by iandunn** [comment]
Fixed in 59cdcb645cd6dd62397ae527f2eaab5e53fdf104.
