### ISSUE TITLE
Camptix: Require a selection in the country dropdown field

### ISSUE THREAD

**Issue by NobNob** [WordPress/wordcamp.org#434]
In our team we've detected a problem with the country selection dropdown field when registering a ticket. Since "Afghanistan" appears as the first option, even though users don't select any country, they submit the form with that country selected, and that isn't really their country. This could be solved by adding as first option something like "--Select a country--", and that this option cannot be selected. As it's a required field, then they cannot submit the form until they select their real country.

Live example: https://2020.spain.wordcamp.org/entradas/?tix_action=attendee_info#tix

Thanks!
![screenshot](https://user-images.githubusercontent.com/9569965/79319858-2dea8980-7f09-11ea-90ed-8dc434d7e515.png)

**Comment by hamdan-Deb** [comment]
same here:-  https://europe.wordcamp.org/2022/tickets/?tix_action=checkout#tix
