### ISSUE TITLE
Migrate skip feature flag data from each site's options table to the blogmeta table

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#448]
Currently we add skip feature flags to an array that lives at the `wordcamp_skip_features` key in a site's options table. Then we use `wcorg_skip_feature( $flag )` as a conditional in the context of the current site that the function is executing on to determine whether or not to skip a particular chunk of code. This works fine for the purpose actually skipping a feature on a specific site, but it makes it really hard to see the forest for the trees if you want to know which sites in the network have a particular flag. You have to run a separate query on each site to check its options table for the value.

I propose that we move these arrays of flags to the blogmeta table. This location is just as accessible from within a site as the options table (using the confusingly named `get_site_meta()` function, which gets values from the blogmeta table instead of the sitemeta table). Further, I think we should consider storing each flag as a separate meta value instead of storing all of them as one array. They would still end up being in an array when you retrieved them with `get_site_meta()` as long as the `$single` parameter is set to `false`.

The improvement from these two changes would be that we could efficiently query for a particular flag and get a list of all the sites that have it--or don't have it. Admittedly that's not something we have to do very often, but it would be one less place where we have to iterate through a 1000+ item array of blog IDs and `switch_to_blog()` / `restore_current_blog()` for each one.

_There are lots of other things we could move to the blogmeta table as well, but I'm currently thinking about this in the context of #370._

**Comment by ryelle** [comment]
Related (but broader scope): https://github.com/WordPress/wordcamp.org/issues/287

Overall agree, I think this is a good idea 👍

**Comment by ryelle** [comment]
There was also [this ticket (closed)](https://meta.trac.wordpress.org/ticket/1403) that mentioned updating the places we check against min site IDs, if feature flags are being updated maybe updating these checks could also get rolled in? It could be a good devex thing to clean up.

From ticket:

> I think this is a complete list of the old filters:
>
>```
> wcpt_require_complete_meta_min_site_id
> wcpt_speaker_post_avatar_min_site_id
> wcpt_session_post_speaker_info_min_site_id
> wcpt_speaker_post_session_info_min_site_id
> wcb_back_compat_max_site_id
> wcb_back_compat_site_id_exceptions
>```
