### ISSUE TITLE
Speaker Feedback: Daily notification for organizers when there's unapproved feedback?

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#454]
Similar to the [daily notification to speakers](https://github.com/WordPress/wordcamp.org/pull/441) when there's new feedback, what if we had a daily notification get sent to the WordCamp's Speaker Organizer's email, with a fallback to the main `city@wordcamp.org` address, that just tells how many unapproved feedback comments there are with a link? (And obviously don't send the email when there aren't any.)

Currently the only notification that organizers will get is a [one-time notification](https://github.com/WordPress/wordcamp.org/issues/411) from WC Central two weeks after the event has ended. This would be a way to prompt organizers to moderate feedback sooner, so speakers can get it sooner, without deluging anyone with notifications (one per day seems reasonable).

cc @dd32 who reminded me about this idea

**Comment by andreamiddleton** [comment]
Oof, *daily* sounds really spammy to me. Is the annoyance of daily reminder emails worth the reward there? I would worry about people marking those reminders spam after a while?

**Comment by coreymckrill** [comment]
Here's a rough idea for the wording of the notification:

```
Subject:
There are X speaker feedback submissions awaiting moderation on WordCamp Z

Message:
Feedback is most effective when it is timely. The speakers from your event won't see
this feedback until it has been approved. You can manage feedback submissions here:

[URL to feedback list table]

Currently there are:

* X unapproved feedback submissions.
* Y feedback submissions that have already been approved.
* Z feedback submissions that have been marked as spam.
```

**Comment by coreymckrill** [comment]
> Oof, daily sounds really spammy to me.

Perhaps it _sounds_ spammy, but it is only the _possibility_ of getting an email daily. If the organizers stay on top of the queue, it probably wouldn't be every day after the first two or three days, because the email would only send when there is feedback waiting.

If the goal is to help speakers improve, and (as mentioned in my suggested text above) feedback is most effective when it's timely, I think nudging organizers to moderate new submissions once per day is totally reasonable.

**Comment by harishankerr** [comment]
I think this would be a lovely idea, as it would help the speaker wranglers stay on top of the speaker feedback queued. I see how useful it might be on a feedback point of view, especially if the speaker requests are not approved.

However, I'm not sure if this would be useful in the format you suggested might seem a little spammy, as @andreamiddleton had suggested. Perhaps we could tweak the timing a bit, from daily notifications to weekly notifications or so? 

If we decide to implement this, I'd suggest adding controls within the speaker feedback tool, or on the WordCamp.org website for the user to control these notifications. These notifications would include options like:

* Enable instantaneous notifications for speakers
* A daily `notification digest`
* A weekly `notification digest`. 

What do you think, @coreymckrill? (I realize how adding settings might result in more overhead, and additional UI/UX work, but I think some users might want to disable these notifications/tweak their frequency if we enable them).

**Comment by dd32** [comment]
Something worth noting here, is that the proposed email would be going to city@wordcamp not to individual organisers (AFAIK), so I don't think it being marked as spam or it being overwhelming would be a problem.

It'd be more like a task to be assigned to someone rather than a spammy nag.
I also assume some email clients would probably nest follow-on notifications under the first - at least I think gmail would.

Most of the feedback I would expect to be submitted within a few hours/days of an event, so it's not like they're going to be bombarded with an email forever.

**Comment by coreymckrill** [comment]
@harishankerr @andreamiddleton I understand that getting the same email notification a few days in a row is kind of annoying, but in this case, I think it's a feature, not a bug. We've created a system where the organizers must be gatekeepers for feedback before speakers get to see it. Moderating the feedback in a timely fashion should not be considered optional. That would be unfair to the intended recipients of the feedback and to the people who took the time to submit it in the first place.

I don't think a weekly notification is sufficient. One email is easy to ignore, and then it's a week later and the event is already fading from people's minds. A daily email is a more effective nudge to ensure that the issue gets addressed. And, as @dd32 mentions, most of the feedback will probably be submitted within the first few days of the event (with a deadline of two weeks after the event), so this email will not keep appearing in the organizers' inbox forever. Unless they actively refuse to deal with the feedback moderation queue.

_Also worth noting: an organizing team that is really on top of the feedback queue won't get any emails at all, because they'll already have it all approved before the daily cron job runs._

In this proposal there is a simple way to turn off the email notifications. It's to _go in and moderate all the feedback_. If organizers aren't willing to get a daily reminder that they need to do this important thing, or they don't want to take the time to moderate feedback at all, do they really meet our expectations for a WordCamp organizer? And/or, should we consider making the entire plugin optional to begin with?

**Comment by andreamiddleton** [comment]
You make some good points. Let’s try it your way and see what kind of feedback we get. We can reassess in 6 months or sooner, if complaints start piling up. 

>
