### ISSUE TITLE
Speaker Feedback: Revise the wording of the feedback form questions

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#456]
The current wording is:

> What's one good thing you'd keep in this presentation?
>
> What's one thing you'd tweak to improve the presentation?
>
> What's one unhelpful thing you'd delete from the presentation?

Several people have noted that this wording may cause a negative skewing of submitted feedback. @0aveRyan had some suggested improvements [here](https://make.wordpress.org/community/2020/01/27/speaker-feedback-tool-final-outline/#comment-27756).

@andreamiddleton suggested this simplified wording:

> What was great in this session?
>
> What needed improvement in this session?
>
> Do you have any additional feedback?

**Comment by 0aveRyan** [comment]
@coreymckrill @andreamiddleton I definitely think those are improved! 

I'd still recommend tweaking the 2nd question, as I think an even more neutral phrasing could invite a wider spectrum of feedback.

> What could have improved this session?

`Needed` prescribes something went _wrong_, was _below standard_, was an _error of omission_, etc. "Needed improvement" still leads the question with a (slightly) negative skew.

Maybe nothing _needed_ improvement but of course everything _could_ improve.

`Could` would allow for that same feedback, while perhaps inviting a broader spectrum of suggestion.
* _"I'd love if you touched even more on [topic] -- it was really interesting!"_
* _"If you had a slide on how [topic] is affected by a11y, that'd be helpful context!"_
* _"I loved your energy, but next time maybe ask folks to leave their questions until the end, those sidebars made things harder to follow."_

**Comment by andreamiddleton** [comment]
>   What could have improved this session?

I agree, that's even more neutral and is an improvement on my suggestion!

**Comment by coreymckrill** [comment]
cc @mrwweb who also had [some suggestions](https://make.wordpress.org/community/2019/10/22/proposal-update-speaker-feedback-tool/#comment-27468) about the wording.

**Comment by coreymckrill** [comment]
So, updating Andrea's revised questions with Dave's suggestion, we have:

> What was great in this session?
>
> What could have improved this session?
>
> Do you have any additional feedback?

**Comment by hlashbrooke** [comment]
I really like the simple questions that Andrea suggests there - they're short and direct, which makes them easier to parse and answer.

**Comment by mrwweb** [comment]
This seems like a fabulous evolution of the questions. :)

I almost wonder if the first two questions remove the need for the third question, but having a catch-all at the end is often a good safety valve. If we got reports of a lot of ranting in it, maybe that would be worth revisiting, but I'd say go with these 3!
