### ISSUE TITLE
Speaker Feedback: Allow organizers to access the feedback view on the front end as well as the form

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#457]
Currently only speakers can access the front end view of approved feedback comments, and only for their own sessions. Organizers (i.e. site admins) just see the feedback submission form like everyone else, because they may want to submit feedback as well.

Suggestion from @dd32:

> My experience is that organisers need to see something before they send the link / direct speakers to a page, if they can’t see what it looks like, they can’t trust it. Also styling it is a challenge if they can’t view it.

So perhaps we should let organizers see _both_ the feedback form and the approved comments. Maybe just append the comments below the form? (I still think only speakers should be able to mark a feedback as "helpful" though.)

**Comment by dd32** [comment]
> So perhaps we should let organizers see both the feedback form and the approved comments. Maybe just append the comments below the form? 

That seems reasonable to me.

> I still think only speakers should be able to mark a feedback as "helpful" though.

Agreed.
