### ISSUE TITLE
Speaker Feedback: Finding the right session in the dropdown is difficult when there are more than a few sessions

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#458]
From @iandunn:

> large camps will have lots of sessions, so that dropdown could get painful, especially if you don’t remember the exact title.

One solution might be to use Select2, which would allow the user to search through the list. We already use it in other parts of the WordCamp codebase, although I've heard that it has some a11y issues.

**Comment by iandunn** [comment]
SelectWoo is a drop-in replacement that solves the a11y issues.
