### ISSUE TITLE
Jetpack: Don't delete old contact form "spam" until a camp is over 

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/wordcamp.org#464]
_[Original ticket in Trac](https://meta.trac.wordpress.org/ticket/3524)_

 Jetpack contact forms use Akismet to catch spam, and then delete the spam periodically. Sometimes there are false positives, though, which can mean that sponsor requests, etc get deleted before the organizers manually check the spam folder.

We could solve that by adding something to the jetpack-tweaks mu-plugin that would check if the camp has happened yet (via get_wordcamp_post()->meta['Start Date (YYYY-MM-DD']), and if it hasn't, then unhook grunion_delete_old_spam.

**Comment by coreymckrill** [comment]
I like this idea. It could also be used to avoid deleting spammed speaker feedback comments for some amount of time after the event is over so organizers have a chance to go through it looking for false positives.
