### ISSUE TITLE
Blocks: Simplify folder structure

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#47]
It feels like the `assets` folder adds an unnecessary lever of depth to the tree structure, since there's nothing else inside it except `src` and the build files. If anything, it feels like the build files should be in a subfolder (or separate folder), since we don't need to access them frequently, but there's only 2 of them, so that also feels like overkill. Putting the `src` files deeper makes them more inconvenient to access.

`assets` also isn't very descriptive, and doesn't seem to make sense in a component architecture where CSS, images, etc would go into the folders of their respective components, rather than being separated into folders based on file type.

The `src` folder name isn't very descriptive, and I personally hate abbreviations in most cases. What about a root-level `components` or `javascript` folder instead?

`view/` should probably be plural since it contains multiple views.

What do y'all think about something like this:

```
blocks/
      components/
            organizers/
            shared/
            ...
            blocks.js
            blocks.min.js
            blocks.min.css
      includes/
      views/
      blocks.php
      ...
```

**Comment by coreymckrill** [comment]
I agree this should be simplified somehow. It seems like there are some conventions that have been widely adopted in other projects that we might look to. For example, what about putting the built files in a separate root-level folder called `dist` or `build`? That might make it easier to have VCS's ignore those files in certain environments, especially if we eventually have more than the two current files.

**Comment by iandunn** [comment]
That WFM. I'd lean towards `build` since it's not abbreviated 😄

**Comment by iandunn** [comment]
We should wait to do this until #44, etc are done, to minimize the merge conflicts.

**Comment by iandunn** [comment]
We might want to use `src/index.js` and `build/index.js`, to watch the convetions that `@wordpress/scripts` uses.

https://make.wordpress.org/core/2019/03/25/building-javascript/

That'd make sense if we want to switch to that instead of our custom webpack/babel configs too.

**Comment by iandunn** [comment]
I wonder if it'd be good to have separate folders for blocks and components, the way G does.

```
blocks/
      src/
            components/
                  avatar/
                  grid-layout/
                  ...            
            blocks/
                  organizers/
                  speakers/
                  ...
            index.js
      build/
            index.min.js
            index.min.css
      includes/
      views/
      blocks.php
      ...
```

**Comment by coreymckrill** [comment]
Yeah, that works for me. We could also include an **index.js** file in each of those folders that just re-exports all of the components that are in the subfolders. That way we could do something like:

```
import { AvatarImage, GridContentLayout } from '../components';
```

...instead of having to do separate imports for each subfolder.

**Comment by coreymckrill** [comment]
Fixed via https://meta.trac.wordpress.org/changeset/8779
