### ISSUE TITLE
Speaker Feedback: Jetpack's "Feedback" menu item for contact form submissions is a naming collision, creates confusion

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#478]
If an organizer is trying to find the speaker feedback submissions screen, the first thing they will see in the Dashboard is a top-level item in the left menu called "Feedback" That is the natural place to go, but it's actually submissions from Jetpack's Contact Form module, not the speaker feedback tool.

The actual list table for speaker feedback is buried under the Sessions item in the left menu. I believe this is the right place for it, especially since we may eventually want to accept feedback submissions on other post types. Each supporting post type will have its own feedback screen. Also, I'm not excited about adding yet another top-level menu item, because clutter.

To mitigate this problem here are a couple of ideas:

* Use a filter to rename Jetpack's menu item to something more accurate, like "Contact Forms" or just "Forms"
* Add a red badge with the count of unapproved feedbacks to the Sessions menu item, so that organizers will know that something there needs their attention.

**Comment by ryelle** [comment]
I like the red badge idea — renaming Jetpack's menu item would probably cause more trouble for support requests than it's worth
