### ISSUE TITLE
Speaker Feedback: Add help text blurb to front end feedback view for speakers

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#480]
When speakers click the link in the notification email to see their approved feedback comments, they may not understand what they're seeing. It would be nice to provide them with a blurb that explains some or all of the following:

* This is a list of feedback submitted by people who watched your talk, and reviewed/approved by the event organizers
* Only you and the organizers can see this
* Marking comments as "helpful" is optional, but you can use it to filter out ones you want to come back to later, and it also helps the WordCamp program track the helpfulness of the feedback tool as a whole. The feedback submitters are not notified if you mark their comment as helpful.

**Comment by varlese** [comment]
Here's a blurb with some suggested language here. Happy to tweak further if it needs to be shorter (or any other changes)!

> This feedback is visible only to you and the event organizers. It was submitted by attendees who watched your talk and has been reviewed and approved by the event organizers. While marking feedback as "helpful" is optional, you can use this to filter messages that you would like to come back to later, and it helps the WordCamp program track the overall helpfulness of the feedback tool. Please note that commenters will not be able to see if you mark their comment as helpful.
