### ISSUE TITLE
Central: About wordcamps page in logo section not showing properly on small screen

### ISSUE THREAD

**Issue by pravinparmar2404** [WordPress/wordcamp.org#501]
In About WordCamps page in logos section not showing properly. It is due to added width in (#content .logos).

![wordcamp-logo-section-not-showing-properly-on-small-screen](https://user-images.githubusercontent.com/37802271/82050905-8d89af80-96d6-11ea-8ab8-aad650bd464b.png)

**Comment by coreymckrill** [comment]
Thanks for the report @pravinparmar2404

**Comment by pravinparmar2404** [comment]
Thank you @coreymckrill for reviewing it. Here's the I have submitted PR.

https://github.com/WordPress/wordcamp.org/pull/503
