### ISSUE TITLE
Sponsors Block: Add link to sponsor on each featured image

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#54]
Currently, if you turn off the Name display in the Sponsors block, you also loose the link to the sponsor page. It would be great if the sponsor image could also be a link - specifically for WCUS, we'd like to have a list of logos that link to each sponsor page (example https://github.com/wcus/wcus-2019/issues/7).

**Comment by iandunn** [comment]
Good point, thanks!

**Comment by coreymckrill** [comment]
Fixed with:

* https://meta.trac.wordpress.org/changeset/8570
* https://meta.trac.wordpress.org/changeset/8572
