### ISSUE TITLE
Blocks: add wide & full alignment support

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#55]
The wide & full alignments are useful for single-column sites, and would be especially nice for the grid displays. It's also easy to add, mostly built-in already:

```js
registerBlockType( 'your-block', {
	…
	supports: {
		align: [ 'wide', 'full' ],
	},
}
```

Themes would need to specify support for wide alignments, so I've also [added a ticket + patch for CampSite support](https://meta.trac.wordpress.org/ticket/4348) 😁

**Comment by iandunn** [comment]
Great point, thanks! `#4348-meta` is merged now.

**Comment by coreymckrill** [comment]
Completed with https://meta.trac.wordpress.org/changeset/8627
