### ISSUE TITLE
Profile badges for WordCamp volunteers

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/wordcamp.org#550]
As per the conclusion of [this proposal on Community Team P2](https://make.wordpress.org/community/2020/07/03/proposal-recognition-for-event-volunteers-and-attendees-in-wordpress-org-profile/), Community Team would like to start handing out badges for volunteers at WordCamp.

Technical aspects are still wide open and need consideration about what is the best approach for this. From a dev time point of view, re-using speaker/organizer Custom Post Type and profile notify functionality build for those would probably be the best solution. But that's not the easiest one for organisers thought, especially for large events with tens of volunteers.

Could it work if we add a setting where organisers can define the discount code and/or ticket reservation pool handed out to volunteers. When registration is done from the pool or with the code draft gets added in "Volunteers" CPT with pre-filled information. Then organisers would just need to publish the post when volunteer is confirmed. This would allow also manually adding the volunteers if organisers decide so or for some reason don't use Camptix at all for them.

This would need asking the WordPress.org username (not mandatory) while purchasing the ticket, but I don't think that's a bad idea in general. That would allow multiple possible things in future, like linking to attendees WordPress.org profile on attendees page etc. Of course, this would need its own decision by Community Team - let's ask it if the approach that requires WordPress.org username during registration sounds like best way to help to achieve volunteer badges.

**Comment by iandunn** [comment]
🤔 those are good questions.

If we use CampTix, we could maybe have some conditional logic where it would only ask for their username if they're using a volunteer coupon code.

Another approach would be to have a Call for Volunteers page, similar to speakers. Submitting that form could automatically create drafts of a Volunteers CPT.

**Comment by timiwahalahti** [comment]
Call for Volunteers page 🙌

IIRC we actually have one already, but it's not asking WordPress.org username nor (clearly) prefilling any CPT. I'm actually unsure how many camps do use the form in that page or are they replacing it with something other. To determine this, would it be easy to run a query that checks how many 2019 events have "WordCamp Volunteer Application" feedback?

If most of the camps are already using the form provided, extending the functionality sounds like the best approach. _I'm also starting to dream about tool based on Volunteers CPT where shifts and tasks can be planned 😅_

**Comment by CdrMarks** [comment]
I do like both of these suggestions:
> If we use CampTix, we could maybe have some conditional logic where it would only ask for their username if they're using a volunteer coupon code.

> Another approach would be to have a Call for Volunteers page, similar to speakers. Submitting that form could automatically create drafts of a Volunteers CPT.

I can think of a few scenarios where a CampTix solution alone may not address the following:
* volunteers who may volunteer after a ticket has been purchased and will not want a refund or will not want to go through the hassle of having their ticket refunded and registering again using a coupon code. 
* volunteers who don't want the perk of a discounted ticket.  
* volunteers who are also speakers that already have a ticket.
* volunteers that are recruited the day of the event and ticket sales are already closed.

Could the Volunteer CPT also allow an Organizer to create a Volunteer, without using the Call for Volunteers form, and fill in the volunteer's WordPress.org username?  I could see where the Volunteer CPT could be useful to also create a public facing page to thank Volunteers.

**Comment by sebastienserre** [comment]
I'm just coming back home from the wonderfull WCEU2023 in Athens... and one more time, I really think all volunteer should have a new "WordCamp Volunteer" badge because they once again done a wonderfull job!

**Comment by chaion07** [comment]
> I'm just coming back home from the wonderfull WCEU2023 in Athens... and one more time, I really think all volunteer should have a new "WordCamp Volunteer" badge because they once again done a wonderfull job!

Just echoing with @sebastienserre on what resurfaced at [WCEU 2023](https://youtu.be/VzKiKRodHQ0?t=2703). Thanks!

**Comment by iandunn** [comment]
#895 added the post type. We'll stiil need to create the new badge, add the automation code, etc.

**Comment by jaz-on** [comment]
Finally! Wup wup kudos @iandunn!
Now we're going to have to write documentation about it and check how it works, but it's a great step forward!

**Comment by timiwahalahti** [comment]
@iandunn I'm interested in contributing to make this happen.

From the discussions on #887, we have the CPT, and the application form generates drafts. I plan on using that new form and CPT for WordCamp Finland, which opens the call in the coming days.

From the same discussion, I gathered the next things that still need to be done:

1. Add new CPT to wordcamp-participation-notifier on wordcamp.org
2. Add new log message on wordpress.org closed source handler
3. Come up with the badge [dashicon](https://developer.wordpress.org/resource/dashicons) with the Community team
4. Add new badge on wordpress.org closed source handler and add that to [handbook](https://make.wordpress.org/meta/handbook/tutorials-guides/profile-badges/)
6. Ticket or coupon code generation
7. Document everything on the Community handbook and do an announcement post
8. New report type to get data about volunteers, most importantly if they were new or returning ones
9. #903

1-6 items are necessary to get the buy-in from organisers and make the CPT valuable. After those things have been implemented and the first data starts to come in, reports should be put together soon-ish.

Did I miss something? I guess most of those need their own issue, but I wanted to pull this list together before jumping into action and reach out in case help is welcome :)

**Comment by iandunn** [comment]
That sounds great! 👍🏻 


> Add new badge on wordpress.org closed source handler 

The data would be added in the association handler, and the visual badge would be added in the Profiles theme.

> Ticket or coupon code generation

Do you mean automatically generating a ticket coupon when someone is accepted as a volunteer? I like that idea, but IMO it'd be better as a 2nd PR, to keep scope manageable. It may need a p2 discussion first too, since I've seen some teams prefer to make volunteers pay for tickets, then reimburse them if they fulfill their commitment.

> New report type to get data about volunteers

I think @renintw is currently working on this in https://github.com/WordPress/wordcamp.org/issues/888

**Comment by chaion07** [comment]
+1 for starting a P2 discussion. Thanks!

**Comment by patriciabt** [comment]
any news on this? we would love the ~150 volunteers at WCEU2024 to have that in their profile
if you need manual data entry, I can do that

**Comment by pkevan** [comment]
> Come up with the badge [dashicon](https://developer.wordpress.org/resource/dashicons) with the Community team

it doesn't look like a badge has been created yet, so we'd need that done first, since any manual work would be reliant on it existing.

**Comment by patriciabt** [comment]
thank you for your reply @pkevan 
there is a dashicon chosen, as it is displayed in the backend (the icon with the hammer)
![image](https://github.com/WordPress/wordcamp.org/assets/1843660/0d9f6340-f396-44a7-bc65-ab8d468a3f89)

what are the next steps? 
choose a color and have it added [there](https://make.wordpress.org/meta/handbook/tutorials-guides/profile-badges/)? 

and about the association handler?  that when we add volunteers to an event CPT with their .org usernames, they get an entry on their profile and the badge like organizers and speakers?

I know there is a lot of work on meta and that some people left, so do you need people to contribute their time to the meta-wordcamp team? (we can find that), just point me in the right direction for the above question.

Thanks a lot

**Comment by pkevan** [comment]
The badge has been created (along with the relevant group), an example is on my profile: https://profiles.wordpress.org/paulkevan/

**Comment by patriciabt** [comment]
Thank you so much @pkevan 
As per our conversation on Slack, I think #f7ad43 is the color for event related badges

**Comment by ePascalC** [comment]
@pkevan @iandunn Just a quick check on this one as we are kicking off WCEU2025. It looks like the badge is ready and just the automatic assignment is missing. Any plans for that? (Not sure how difficult it is). Thanks.

**Comment by patriciabt** [comment]
oh btw, I never sent you the list of 2024 volunteers for adding manually. I will do that in the next days! thanks @pkevan

**Comment by itsnotevann** [comment]
@pkevan @iandunn Hey! We're wrapping up WordCamp Larissa 2024 and wanted to check in for an update on this. Is there a way to add the badge to our volunteers' profiles, even if it needs to be done manually? Thanks!

**Comment by pkevan** [comment]
Given that the profile badge is created without any automation lets close this issue as it isn't the place to ask for it to be added to profiles.

Anyone coming across this issue in the future, feel free to ask for this to be added via #meta-wordcamp in Slack - you'll need to provide a list of wp.org usernames in a text file (one per line) so that someone can add them in bulk.

**Comment by timiwahalahti** [comment]
Not sure if this should be closed since there's no new issue about automatically assigning that badge. It would be nice to have that, so no manual labour would not be needed.

**Comment by pkevan** [comment]
Missed this from my previous message, but no plans on creating automation for this.

**Comment by ePascalC** [comment]
I agree with @timiwahalahti that it's strange to close this ticket. The automation should be 95% equal to the one for WordCamp organisers with the work already done so far. It seems strange to me that every week someone will have to import a list for the different WordCamps that are being organised.
Anyway, you can expect the WCEU 2024 and 2023 list soon. Thanks.

**Comment by sebastienserre** [comment]
Same here, This issue is not solved so it should be reopened.
