### ISSUE TITLE
Meetup organizer application prompt to login is confusing

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/wordcamp.org#561]
**Describe the bug**

It's not clear that the `wcorg-login-message` has clickable links in the message.
![image](https://user-images.githubusercontent.com/3489003/91104732-ef41aa00-e633-11ea-9e37-31a557b618bf.png)

This was reported during [Community Team office hours in Slack](https://wordpress.slack.com/archives/C02RQC7RN/p1598307873034600) today.

**To reproduce**
1. Log out of your wordpress.org account
2. Browse to https://central.wordcamp.org/meetup-organizer-application/

**Expected behavior**

Other links on this page are a different color than the body text.  The `font-weight: 600` doesn't seem to be enough.  

**Possible resolution**
Could the following style be added?

`#wcorg-login-message > p > a
{
     text-decoration: underline;
}`

**Comment by CdrMarks** [comment]
Relates #321.

**Comment by timiwahalahti** [comment]
Taking a look at this soon.
