### ISSUE TITLE
Sessions in schedule block overlap when viewing from certain locations/timezones

### ISSUE THREAD

**Issue by jorgeatorres** [WordPress/wordcamp.org#562]
**Describe the bug**

This might be related to #559. When visiting [our WC site](https://colombia.wordcamp.org/2020/agenda/) from certain locations (for instance, London (UK) or Barcelona (Spain)), some sessions start to overlap making the whole thing unreadable.
These sessions seem to be the ones that fall near the time the day changes (in that timezone), but I'm not sure if that's the real reason.

It is worth mentioning that to work around #559, our site's timezone was changed to UTC (from the previously set "America / Bogota" or UTC-5). I can confirm that the sessions look fine when in UTC-5 or UTC-3, so maybe the the problem only affects UTC+something timezones?

Is there a something we can do from our side besides manually creating a schedule page (not using the block)? Thanks!

**To reproduce**

1. Set time zone to "Bogotá - Colombia" or "Buenos Aires - Argentina".
   On macOS: Go to System Preferences > Date & Time > Time Zone.
1. Go to https://colombia.wordcamp.org/2020/agenda/.
1. Confirm that the whole schedule looks fine.
1. Change time zone to "London - United Kingdom" (British Summer Time) or "Barcelona - Spain" (Central European Summer Time).
1. Go to https://colombia.wordcamp.org/2020/agenda/.
1. See how some session items look wrong, either overlapping or times being displayed over borders. See screenshots below for examples.

**Expected behavior**

Schedule should look correct in all timezones.

**Screenshots**

<img width="892" alt="Screen Shot 2020-08-25 at 16 01 26" src="https://user-images.githubusercontent.com/184724/91200789-fe793400-e6d5-11ea-9394-8ca3dceb8b41.png">
<img width="881" alt="Screen Shot 2020-08-25 at 18 07 24" src="https://user-images.githubusercontent.com/184724/91200801-01742480-e6d6-11ea-8428-c5dbec487d4f.png">

**WordCamp**

https://2020.colombia.wordcamp.org/

**System (please complete the following information):**

 - Device: Laptop
 - OS: macOS 10.15.6
 - Browser: Chrome
 - Version: 84.0.4147.135

**Comment by iandunn** [comment]
Note to self: another way to test the time zone is with `TZ="Europe/London" open /Applications/FirefoxDeveloperEdition.app` in terminal, and verify with `Intl.DateTimeFormat().resolvedOptions().timeZone` and `wp.date.format('P')` in browser console. That might avoid unintended side-effects from changing the OS timezone.

**Comment by iandunn** [comment]
> Is there a something we can do from our side besides manually creating a schedule page (not using the block)?

I'm hoping to have this fixed soon, but in the mean time you can switch to the block's `Single Column Layout` style.

**Comment by iandunn** [comment]
@jorgeatorres, it looks like we might need to wait for https://github.com/WordPress/gutenberg/issues/25078 and https://github.com/WordPress/gutenberg/issues/22193 to be fixed & released before we can fix this.

The next Gutenberg released isn't scheduled until after Colombia is over, so I'd recommend switching to the `Single Column Layout` block style in the meantime. That should prevent the overlap problem.

**Comment by iandunn** [comment]
It looks like the above 2 PRs will solve this, but only when using _string_ timezones 😆 🤷🏻 .

Keeping open until we upgrade to v9 (or possibly later if https://github.com/WordPress/gutenberg/pull/25083 is in a later version).
