### ISSUE TITLE
Clone another WordCamp doesn't work

### ISSUE THREAD

**Issue by Glorialchemica** [WordPress/wordcamp.org#563]
**Describe the bug**
We are customizing the theme for WordCamp Italia. From _Administration screens > Apparence > Customize > Clone another WordCamp_ the cloning button appears disabled, preventing the cloning of styles.
We have tried with several browsers, but the problem remains.

**Screenshots**

![image](https://imgur.com/DT0XpnT.png)

**WordCamp**

https://2020.italia.wordcamp.org/

**Comment by ryelle** [comment]
Thanks for reporting this, @Glorialchemica! There was a bug with the site list request. It should be fixed now.
