### ISSUE TITLE
Add start/end Unix timestamps to `wordcamp` API endpoint

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#567]
### Background

meta:#4480 is updating `api.w.org/events` to include a true Unix timestamp for meetups. Once that's done, core:#51130 will update the Events Widget to display them in the user's local time.

That's mostly for learn.w.org discussion groups, but it'd be confusing if the Events Widget displayed some events in the user's local timezone, and others in the venue timezone.

So, we should probably add true Unix timestamps to https://central.wordcamp.org/wp-json/wp/v2/wordcamps.

### Implementation Ideas

For online events, we can simply use UTC. For in-person events, though, it's not as straight forward. 

The site timezone is an option, but people option don't think to change it, so it gets left in UTC even if the event is half a world away.

The venue address in the WordCamp post type is probably the most accurate indicator, and we already have the lat/long coordinates of that. There are [many ways to convert coordinates to timezones](https://stackoverflow.com/a/16086964/450127).

The Events API uses the GeoNames database for IP geolocation, so we could update that import script to also save TZ info. We're also already using Google's Geocoding API for the map on Central, though, so it seems simpler to use that here too.

Another option is the timezone-boundary-builder, but that seems like it'd be much more work.

### Start Times

We don't collect start times of WordCamps, but we can reuse the `session_start_time` callback. If that's `0`, maybe we fallback to `9:00am` (local time), since camps typically start around then. That feels safer than using `00:00`, since that's close to a date boundary, and may result in the wrong date being shown to the user after conversion.

**Comment by CdrMarks** [comment]
Regarding WordCamp start times, could we look for the earliest session on the first day of the WordCamp in case the organizers happened to include an event on their schedule on the night before the first day.  It's possible, though, the event start day and time should include this night before event.

**Comment by iandunn** [comment]
> The venue address in the WordCamp post type is probably the most accurate indicator, and we already have the lat/long coordinates of that. There are many ways to convert coordinates to timezones.

Er, I was overthinking that. It'd be much simpler to just add a `wp_timezone_choice()` dropdown to the `wordcamp` post type, and make it a required field before moving to any public statuses. We should also add SelectWoo to it, since core:#31696 is still stalled.

We could also use that to set the site tz when during site creation.

**Comment by iandunn** [comment]
> could we look for the earliest session on the first day of the WordCamp

🤔 , that's a good question. I don't feel too strongly either way. It might be simplest to start with the earliest session (on any day). We can always add checks to restrict it to the `wordcamp` post's start day if needed.

**Comment by iandunn** [comment]
For reusing `session_start_time`, we'll probably need to adjust the early return in the callback. Maybe leave it as-is for this field, but remove it for the new field. We could modularize the `get_posts()` part into a reusable function that both fields call, but the individual fields can wrap it with whatever specific logic they need.

**Comment by CdrMarks** [comment]
> make it a required field before moving to any public statuses.

I like this approach.  Some in-person WordCamps will still livestream and having a good representation of the time will be important.

**Comment by iandunn** [comment]
I ended up adding the timezone to the API, instead of a Unix timestamp, since the Events API database expects a WP timestamp + UTC offset. Receiving a Unix timestamp would mean that `parse_wordcamp_events()` would have to do extra steps.

**Comment by iandunn** [comment]
> It might be simplest to start with the earliest session (on any day). We can always add checks to restrict it to the wordcamp post's start day if needed.

Er, nevermind, [we're already doing that check](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/official-wordpress-events/official-wordpress-events.php?rev=10244&marks=416-433#L412) :)
