### ISSUE TITLE
Open-Source WordCamp.org

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#576]
Imported from https://meta.trac.wordpress.org/ticket/221 
Created by @iandunn:

We should move as many components of WordCamp.org as possible into the Meta repo, so that it's open to the community to contribute.

Before each piece can be moved, it will need to be audited for any security vulnerabilities or sensitive information.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/221#comment:1) by @iandunn:
 * Status set to `assigned`
 * Owner set to @iandunn

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/221#comment:2) by @iandunn:

In [\[115\]](http://meta.trac.wordpress.org/changeset/115):
```
WordCamp Calendar: Move from private WordCamp repo. See https://meta.trac.wordpress.org/ticket/221.
```

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/221#comment:3) by @iandunn:

In [\[116\]](http://meta.trac.wordpress.org/changeset/116):
```
WordCamp Canonical Years: Move from private WordCamp repo. See https://meta.trac.wordpress.org/ticket/221.
```

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/221#comment:4) by @iandunn:

In [\[117\]](http://meta.trac.wordpress.org/changeset/117):
```
WordCamp Fonts: Move from private WordCamp repo. See https://meta.trac.wordpress.org/ticket/221.
```

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/221#comment:6) by @iandunn:

In [\[171\]](http://meta.trac.wordpress.org/changeset/171):
```
WCPT: Move from private repository. See https://meta.trac.wordpress.org/ticket/221.
```

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/221#comment:8) by @iandunn:

We should also open-source the mu-plugins so things like https://meta.trac.wordpress.org/ticket/502 can be contributed to by the community.

Subversion only supports `svn:external`'ing files from within the same repo, so I'll migrate the few that need to remain private to a new `mu-plugins-private` directory and then move the public ones to meta.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/221#comment:9) by [@obenland](https://profiles.wordpress.org/obenland/):

@iandunn Do you know what's left to do on this ticket? How far away is this from being closable?

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/221#comment:10) by @iandunn:

Almost everything is done. The two things left are the `camptix-extras` and `wordcamp-shortcodes` plugins. Most of `camptix-extras` has already been opened, and a few of the remaining parts will need to stay closed. 

Neither are a high priority, since they're not important or commonly used features. I'm trying to focus my time on the things that will make the biggest impact, so I imagine it'll be a long time before I'm able to close this out.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/221#comment:11) by [@obenland](https://profiles.wordpress.org/obenland/):

How much time do you think it'll take to complete this?

If I learned anything over the last two weeks, it's that finishing things and crossing them off sometimes take a surprisingly short time but it gives you a great sense of accomplishment and peace of mind.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/221#comment:12) by @iandunn:

__If__ things go smoothly, I'd guess that it'd take roughly 2 hours to clean up formatting, review the code for potential security issues and private data, test any changes, migrate it, deploy it, and re-test on production.

That'd have a very small impact though, and time is very limited. Saying "yes" to this means saying "no" to other things. Since there are so many things that will make a bigger impact, to me it feels like time spent here would essentially be wasted in comparison. 

Even if this ticket is closed, there'll always be hundreds of other open ones that we don't have time to get to. I think that's just the nature of a large open source project (and, to some extent, any software project, or any project of any type). I think prioritizing the things that will make the biggest impact, and then focusing on those few things, is the best way to serve the project.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/221#comment:13) by @iandunn:

In [\[6714\]](http://meta.trac.wordpress.org/changeset/6714):
```
CampTix Tweaks: Open source functions from `camptix-extras`.

With this, there's nothing left in `camptix-extras`, so it's being removed.

See https://meta.trac.wordpress.org/ticket/221
```

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/221#comment:14) by @iandunn:

In [\[6730\]](http://meta.trac.wordpress.org/changeset/6730):
```
WordCamp Miscellaneous: Open source the map of active groups.

See https://meta.trac.wordpress.org/ticket/221
```

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/221#comment:15) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by ryelle. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1579198977045100)._

**Comment by timiwahalahti** [comment]
@iandunn do you think we could close this issue? It seems like almost everything that can be open sources has been, or is tracked in separate issues.

**Comment by iandunn** [comment]
Yeah, I think that's right 👍🏻
