### ISSUE TITLE
Automate Tagregator settings

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#589]
Imported from https://meta.trac.wordpress.org/ticket/1933 
Created by @hlashbrooke:

The Tagregator settings (API keys) for each WordCamp site always need to be filled in by the organisers each year. My assumption is that there is no need to generate new keys every year and, in many cases, I'm sure this is something that organisers forget to do as there are so many more pressing things to take care of when organising a WordCamp.

While Tagregator is perhaps a more minor feature, we could do a lot to improve the flow of it. There are two options here I think:

1. Organisers generate and add their API keys for the first camp in their city and then subsequent years automatically copy the previous year's keys as the site is created.
2. We generate API keys for each service that are linked to the WordCamp Central and auto-populate all future WordCamp sites with them.

Option 1 would be a quick win (I think), but option 2 would be even better if we could do it. The main issue that would probably come up are the usage limits for each API key, so we would need to research those for each service before we could go with option 2.

If we don't do any of this, then we could at least try to improve the oAuth flow for organisers to make this whole thing a lot simpler.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/1933#comment:1) by @iandunn:
 * Keywords set to `Needs Patch` `Good First Bug`
 * Status set to `assigned`
 * Owner set to @iandunn

I think we should try setting up a set of default keys that all sites can use, but let them override it if they want.

We'll need to double-check the API limits, but my rough worst-case calculations are that we'd have at most `14,400` requests per day in the short term, and `24,000` per day in the longish term.

```
2 requests per min * 6 active sites  = 12 every minute = 14,400 per day
2 requests per min * 10 active sites = 20 every minute = 24,000 per day
```

Twitter's API allows `180` requests every 15 minutes, so we'd be fine there. (That's only for the Search endpoint; the others are `15` every 15 minutes, but we don't use those).

I'm assuming the other services have similar limits, but we should check. We could adjust the update interval if it's close enough.

Worst case, if we did run into problems, organizers could always create their own keys to override the default ones.

Also worth noting: Pinterest disable the API keys if the account connected to them doesn't use the app periodically, which is annoying and will bite us here. Maybe we just don't setup a default key for Pinterest, since it's break all the time anyway.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/1933#comment:2) by @iandunn:
 * Owner cleared

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/1933#comment:3) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by coreymckrill. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1582222389267700)._

**Comment by timiwahalahti** [comment]
Not sure if this is still valid after the decision made in #847

**Comment by iandunn** [comment]
Yeah, I think we can close it 👍🏻
