### ISSUE TITLE
Gmail adds different emails from contact forms in the same thread

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#595]
Imported from https://meta.trac.wordpress.org/ticket/3259 
Created by @ePascalC:

When creating a contact form on a wordcamp site and forwarding the form content to a gmail address, gmail is grouping different forms together in the same thread, making it difficult to work on the inbox. All emails have the same subject ( [aH6FlOBO] WordCamp Contact Request ) except for the unique ID in between the brackets.

Looking around for explanations, the best one I found was :

```
Gmail joins messages into conversations based entirely and only on the subject content.
It sometimes does not join messages together if there are time gaps between them.

It never joins messages together in a conversation if the subject line is different except when the subject begins with a phrase within square brackets!!
Gmail ignores the square bracketed part to assist in the handling of messages from Google groups.
```

So as the unique ID between the brackets is skipped, the subject is the same and multiple email are going together in the same thread in gmail.

**Comment by ghost** [comment]
Comment by @ePascalC:
 * [3259.diff](https://meta.trac.wordpress.org/attachment/ticket/3259/3259.diff) added

Remove brackets in the subject

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:1) by @ePascalC:
 * Keywords set to `Has Patch`

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:2) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by casiepa. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1510177429000177)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:3) by [@mrwweb](https://profiles.wordpress.org/mrwweb/):

As I [mentioned on Slack](https://wordpress.slack.com/archives/C08M59V3P/p1510161534000619?thread_ts=1510160580.000137&cid=C08M59V3P):

> I selectively did this for a few of our forms with Seattle and it did seem to helwork. For instance, the speaker application subject was "[asdfasdf] WordCamp Speaker Application: {title}, {name}"

I didn't know the Gmail issue with brackets. That definitely sounds like it'll fix the technical problem.

From a pure email management perspective, I'd suggest we update the default subject lines to include at least the sender/submitter/applicant/purchaser name for easier reference and searching. That may require a different change to the default content, but I thought I'd mention it here in case it's appropriate to make both changes at once.

In the same vein, could the random string appear at the end of the subject so it doesn't distract from the part intended for humans?

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:4) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by iandunn. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1510243561000099)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:5) by @iandunn:

That's a good point to bring up, Mark. I think adding something like `{name}` and `{title}` would be more user-friendly than a random string.

We'd probably need to check if those fields exist in the form, though, and also that they weren't already added manually. If either of those fail, then maybe we fall back to a random string? It'd also be good to check for variations like `{first_name}`, etc.

I think it'd be nice to have the random string be something like `(id:f3Jfmsad)` rather than just the number, to make it a little more less confusing for users. The parenthesis help visually separate it and make it feel like a distinct part, and the `id` explains a little bit about why it's there. We'd need to make sure that Gmail (and other clients) don't ignore things in parenthesis either, though. If they do, we could maybe do it like ` -- id:f3Jfmsad` instead.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:6) by @ePascalC:

I already moved it to the end in my attached patch (space dash space and then the unique ID)

I will look into those extra fields to add as a quick win, great find!

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:7) by @ePascalC:

I tried the following and it worked perfectly:

[contact-form to='hello[@whatever](https://profiles.wordpress.org/whatever/).org,myself[@gmail](https://profiles.wordpress.org/gmail/).com' subject='VISA Application Form **- {Last Name} {Given Name}**'][contact-field **label='Last Name**' type='text' required='1'/][contact-field **label='Given Name**' type='text' required='1'/][contact-field label='Date of Birth (dd/mm/yyyy)' type='text' required='1'/][contact-field label='Home Address' type='textarea' required='1'/][contact-field label='Passport Number' type='text' required='1'/][/contact-form]

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:8) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by coreymckrill. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1511293646000449)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:9) by @coreymckrill:
 * Status set to `assigned`
 * Owner set to @ePascalC

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:10) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by casiepa. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1513712719000290)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:11) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by iandunn. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1540397204000100)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:12) by @iandunn:

The patch needs some minor work based on Slack discussion linked above.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:13) by @iandunn:
 * Keywords set to `Needs Patch`

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:14) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by iandunn. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1585849766063200)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:15) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by casiepa. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1591768219401800)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3259#comment:16) by @dd32:

Is this still an issue? Gmail updated in early 2019 to require the `References:` or `In-Reply-To:` headers to be set in order for threading to kick in: https://gsuiteupdates.googleblog.com/2019/03/threading-changes-in-gmail-conversation-view.html (That references GSuite, but every article I can find says it's "gmail")

**Comment by timiwahalahti** [comment]
It looks like this is not an issue anymore, confirmed with few latest contact request emails.
