### ISSUE TITLE
defect: Some CTP list views have wide whitespace on narrow screen

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#604]
Imported from https://meta.trac.wordpress.org/ticket/3835 
Created by [@Nao](https://profiles.wordpress.org/Nao/):

On local WordCamp sites, the list view for speakers, sessions, and organizers have very wide unwanted whitespace when you are on a narrow screen.

How to reproduce: 

1. Open one of the list view pages (e.g. https://2018.xxxx.wordcamp.org/wp-admin/edit.php?post_type=wcb_speaker )
2. Make the screen narrower to the point where the hamburger menu shows up on the top left.
3. Very wide whitespace appears to the right of names/titles.

I've only tested this with Japanese WC sites (Tokyo 2017, 2018, and Osaka 2018), but the same issue appeared with English names/titles too.

**Comment by ghost** [comment]
Comment by [@Nao](https://profiles.wordpress.org/Nao/):
 * [session-cpt-list-ng.png](https://meta.trac.wordpress.org/attachment/ticket/3835/session-cpt-list-ng.png) added

Session list view with a wide whitespace

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3835#comment:1) by @iandunn:
 * Keywords set to `Needs Patch` `Good First Bug`
 * Status set to `assigned`

You're right, thanks for reporting this :)

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3835#comment:2) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by iandunn. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1588268592231700)._

**Comment by timiwahalahti** [comment]
Cannot reproduce anymore.
