### ISSUE TITLE
Changes to WordCamp attendee life-threatening allergy and special accommodations notifications

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#605]
Imported from https://meta.trac.wordpress.org/ticket/3862 
Created by [@francina](https://profiles.wordpress.org/francina/):

[As discussed in the Community P2](https://make.wordpress.org/community/2018/05/28/should-wordcamp-attendee-life-threatening-allergy-and-special-accommodations-notifications-be-changed/#comment-25660), we are sending out quite a few email notifications to the organisers inbox when the allergy/special accommodations workflow is triggered.
Some WordCamps create a Gmail account to receive emails and emails get collated in threads: this makes it more difficult to read them all.
Instead of sending two emails would it be possible to have one email and one notification in the WordCamp website dashboard?

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3862#comment:1) by @timiwahalahti:

Big +1 for this.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3862#comment:2) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by coreymckrill. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1590686331326000)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3862#comment:3) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by sippis. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1590739467355700)._

**Comment by ryelle** [comment]
I've read through the community p2 feedback, and it sounds like the followup email is still valuable, specifically

> These emails could have easily been lost in my inbox (I get A LOT of email) and I would hate for someone to not have their needs met because of this. Yes, the second send is inconvenient, but to me, the inconvenience doesn’t outweigh the trouble it could cause for an attendee. 

I'm going to close this issue in favor of #508, because I think the cron/batch email suggestion there is probably a better solution - and further discussion can happen on that issue.
