### ISSUE TITLE
WordCamp.org: WordCamps with non-public statuses are exposed in REST API

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#610]
Imported from https://meta.trac.wordpress.org/ticket/4048 
Created by @timiwahalahti:

WordCamp REST API base (https://central.wordcamp.org/wp-json/wp/v2/wordcamps) exposes only WordCamps with public statuses. If you happen to know or guess post ID, you can still query singular camps that do have non-public statuses.

I guess we really shouldn't expose WordCamps in REST API, in favor of following the same practice as WordCamp REST API base.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4048#comment:1) by @iandunn:

Hmm, I'm curious why they're available by ID but not in the main list. Is there something in the code where we're explicitly removing them from the main list, and we just accidentally left them in the individual responses? Or were they accidentally removed from the main response as a side-effect of having custom statuses?

Similar to https://meta.trac.wordpress.org/ticket/4047, I personally prefer to err on the side of transparency unless there's a tangible privacy or security reason to make the data private.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4048#comment:2) by @timiwahalahti:

Looks like WordCamps with private statuses are removed purposely from the main list, see changeset [\[4804\]](http://meta.trac.wordpress.org/changeset/4804). In that changeset, Corey did set the main list to contain only public statuses and restricted fully private status listings (eg https://central.wordcamp.org/wp-json/wp/v2/wordcamps?status=wcpt-mtp-rejected).

Replying to @iandunn:
> Similar to https://meta.trac.wordpress.org/ticket/4047, I personally prefer to err on the side of transparency unless there's a tangible privacy or security reason to make the data private.

In my opinion, in this case, there might be a privacy reason. Unlike in meetup endpoint, WordCamp endpoint has custom fields added to the response. Those fields contain applicants name and w.org usernames, for example. Yeah, public application status report page does contain that information also but only for a limited period - public status reports don't.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4048#comment:3) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by iandunn. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1547746862139000)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4048#comment:4) by @iandunn:
 * Keywords set to `Needs Patch` `Good First Bug`

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4048#comment:5) by @iandunn:

Several contributors discussed this in Slack (see above) and agreed it would be a good idea :)

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4048#comment:6) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by sippis. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1556046058094000)._

**Comment by ghost** [comment]
Comment by @timiwahalahti:
 * [4048.diff](https://meta.trac.wordpress.org/attachment/ticket/4048/4048.diff) added

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4048#comment:7) by @timiwahalahti:
 * Keywords set to `Good First Bug` `Has Patch` `Needs Testing`

Patch add our own `check_read_permission` function to our custom `WordCamp_REST_WordCamps_Controller` class. Our custom functionality checks the post status against `WordCamp_Loader::get_public_post_statuses()` list added with `wcpt-cancelled` status and fallbacks to default `WP_REST_Posts_Controller::check_read_permission` when post status is readbale.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4048#comment:8) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by coreymckrill. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1563473261297900)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4048#comment:9) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by iandunn. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1590688592350600)._

**Comment by ryelle** [comment]
Related to https://github.com/WordPress/wordcamp.org/issues/661 (Meetups exposed in API). Possibly both could be fixed at once?
