### ISSUE TITLE
Central: harmonize trailing slash for WordCamp website URL

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#618]
Imported from https://meta.trac.wordpress.org/ticket/4351 
Created by @ePascalC:

Using https://central.wordcamp.org/wp-json/wp/v2/wordcamps?per_page=100 it seems that the URLs sometimes have a trailing slash and sometimes not.
Remove trailing slash for all (or set it, whatever is the current standard) would be preferred to harmonize:

"URL":"https:\/\/2018.islamabad.wordcamp.org\/"
"URL":"https:\/\/2019.boise.wordcamp.org"

Probably not only in the API, but better directly in the backend of Central.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4351#comment:1) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by ryelle. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1593106995494200)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4351#comment:2) by @iandunn:

[3ea4ae7a](https://github.com/WordPress/wordcamp.org/commit/3ea4ae7a6465efd9f33af88f6003e3d0b0b23df2) fixes this for new sites, but old sites would still need to be changed.

**Comment by ryelle** [comment]
I spot-checked a number of WordCamps, and it looks like the URL restructure fixed this. Now all sites use the format `city.wordcamp.org/year/` (and the few that don't still have a trailing slash).
