### ISSUE TITLE
Central API : wordpress.org username not exposed

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#619]
Imported from https://meta.trac.wordpress.org/ticket/4353 
Created by @ePascalC:

When adding a speaker for a WordCamp, the w.org username can be added in the backend. However the username is not exposed in the API on e.g. https://2019.europe.wordcamp.org/wp-json/wp/v2/speakers

Please add the meta field in the API.

**Comment by ghost** [comment]
Comment by @ePascalC:
 * [Capture.PNG](https://meta.trac.wordpress.org/attachment/ticket/4353/Capture.PNG) added

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4353#comment:1) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by casiepa. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1576779240010200)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4353#comment:2) by @ePascalC:

The reason for getting the w.org username exposed is also to be able to find more easy the twitter account of the speaker on the profile so they can get a tweet with the video gets published.
As per slack discussion on https://wordpress.slack.com/archives/C08M59V3P/p1576779620014700 , @iandunn indicated that it might be possible by using the gravatar hash.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4353#comment:3) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by ryelle. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1593107276497300)._

**Comment by ryelle** [comment]
This is now available in the API via `meta._wcpt_user_name`. It was added with https://github.com/WordPress/wordcamp.org/commit/e5964b4dc8fef5dda27f8b28ee93046d4aef95b4.
