### ISSUE TITLE
Automatically disable Attendance UI after event ends

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#620]
Imported from https://meta.trac.wordpress.org/ticket/4374 
Created by @iandunn:

CampTix's Attendance UI tool asks organizers to remember to disable it after the event is over, but that could be done automatically, to ensure it gets done.

Sometimes camps will enter data after the event, though, so the job should probably run 2 weeks after the camp is over.

The dates of the camp can be gotten via `get_wordcamp_post()->meta`.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4374#comment:description.1) by @timiwahalahti:

+1 for automatic disable.

Replying to [ticket:4374 iandunn]:
> Sometimes camps will enter data after the event, though, so the job should probably run 2 weeks after the camp is over.

I'd be curious to know how many WordCamps really use Attendance UI to enter data after the event, rather than just doing it from dashboard which feels a lot easier for batch marking at least for me.

Attendance UI should IMO be only enabled for the few event days, before there is a concern about the link leaking.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4374#comment:2) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by iandunn. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1594314115047600)._

**Comment by timiwahalahti** [comment]
With the cron job, I see two possible approaches:

1. Schedule a single event on the WordCamp site when UI is turned on
2. Schedule daily event on Central that goes thru WordCamps with public status and without a meta flag that UI is turned off

The latter one sounds a bit too heavy for the purpose. With a single event, we trust that nothing accidentally removes the job from the queue.

I think that the best, easiest approach to this would be modifying the secret link to expire after two weeks of creation. That should be fairly easy and the change would also break existing secret links, thus effectively disabling the UI. This approach leaves the enabled setting on, but I think that's not a big problem.

Opinions?

**Comment by pkevan** [comment]
> I'd be curious to know how many WordCamps really use Attendance UI to enter data after the event

It's definitely not every WordCamp, but how are we using that data for tracking attendance? If we aren't looking at that data, it might not be something we need to worry about.
