### ISSUE TITLE
Register custom block styles on WordCamp sites

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#622]
Imported from https://meta.trac.wordpress.org/ticket/4389 
Created by [@melchoyce](https://profiles.wordpress.org/melchoyce/):

It would be really nice if we could figure out a way for WordCamp sites to be able to register custom block styles — even if it’s like, a UI where you enter a name for the  style and then assign it to a CSS class (h/t @ryelle for the idea).

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4389#comment:1) by @iandunn:

Do you mean something like the Customizer's Additional CSS panel, but for `editor-styles.css` ?

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4389#comment:2) by [@melchoyce](https://profiles.wordpress.org/melchoyce/):

No, but that would also be awesome — both for WordCamps and, honestly, any theme using Custom CSS.

I'm talking about block styles. I'll add a screenshot :)

**Comment by ghost** [comment]
Comment by [@melchoyce](https://profiles.wordpress.org/melchoyce/):
 * [Screen Shot 2019-04-16 at 12.07.25 PM.png](https://meta.trac.wordpress.org/attachment/ticket/4389/Screen%20Shot%202019-04-16%20at%2012.07.25%20PM.png) added

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4389#comment:3) by @iandunn:

Ah, ok, I hadn't heard of those before.

https://themeshaper.com/2019/02/15/customizing-gutenberg-blocks-with-block-styles/

I wonder if it'd be better to have a curated collection of block styles for the entire network, so that people don't have to reinvent the wheel?

That would introduce barriers to creating them, though. Maybe we could have both? Let people build custom ones on their individual sites, but then also periodically add the best/most reusable ones to a group that's available on the whole network?

It might be best to discuss this on the p2 first, to get a broader set of input and feedback than we'll get here.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4389#comment:4) by [@melchoyce](https://profiles.wordpress.org/melchoyce/):

Getting feedback from WordCamps working with Gutenberg would be great!

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4389#comment:5) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by ryelle. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1555609730047500)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4389#comment:6) by @coreymckrill:
 * Status set to `assigned`

The `register_block_style` PHP function introduced in WP 5.3 should make this easier:
https://make.wordpress.org/core/2019/09/24/new-block-apis-in-wordpress-5-3/

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4389#comment:7) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by iandunn. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1594314493052900)._

**Comment by ryelle** [comment]
I think using Global Styles to customize the existing blocks would cover some of the root issue here (IIRC, this was about setting up some custom styles on WCUS blocks). There's also [an issue in gutenberg](https://github.com/WordPress/gutenberg/issues/33232) (not sure how active) to add style control to `theme.json`, which would be the first step to getting a UI in the Global Styles panel.

I'm inclined to close this here, and let the solution happen in Gutenberg.
