### ISSUE TITLE
Add a way to declare a custom color palette in Gutenberg

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#624]
Imported from https://meta.trac.wordpress.org/ticket/4392 
Created by [@melchoyce](https://profiles.wordpress.org/melchoyce/):

There's no way to overwrite the default color palette in Gutenberg on a WordCamp site. Can we find a way to allow this? Would make it much easier for designers and content creators to coordinate.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4392#comment:1) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by ryelle. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1555609730047500)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4392#comment:2) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by coreymckrill. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1561053112078700)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4392#comment:3) by @coreymckrill:
 * Keywords set to `Needs Patch` `Needs Design`
 * Status set to `assigned`

In today's bug scrub, we discussed adding a WordCamp settings sidebar to the block editor UI where a custom color palette (and perhaps other things like in https://meta.trac.wordpress.org/ticket/4389) could be defined by the organizers. Similar to @ryelle's comment [here](https://wordpress.slack.com/archives/C08M59V3P/p1555611110080100?thread_ts=1555610462.064200&cid=C08M59V3P).

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4392#comment:4) by @ryelle:

I have a prototype for this, after WCEU I can clean it up. I tried the gutenberg sidebar way first, but unfortunately the way GB sets up the colors means that we can't seamlessly update without a page reload (because GB reads the colors from a variable set on the page) - you can see this almost working [on the prototype](https://github.com/ryelle/wc-custom-styles/tree/add/custom-colors) (not a stable prototype, and if you download it you'll need to `npm install` and `npm run build` to test it), but the colors reset when you update/publish a post.

The other direction I started going was the options page, so you set up your colors in a new page, then they're set as the editor colors when the editor initializes. [There's an even less finished prototype here.](https://github.com/ryelle/wc-custom-styles/tree/try/custom-colors-screen)

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4392#comment:5) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by iandunn. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1594315314068300)._

**Comment by ryelle** [comment]
This is now possible in core, for block-based themes (currently just Twenty Twenty-Two). You can add "custom" colors to the available options:

<img width="306" alt="Screen Shot 2022-03-29 at 2 47 41 PM" src="https://user-images.githubusercontent.com/541093/160683544-9a83094e-acdf-4995-a26f-22b58d531ca5.png">
