### ISSUE TITLE
WordCamps: Render session information in page template

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#634]
Imported from https://meta.trac.wordpress.org/ticket/4568 
Created by [@melchoyce](https://profiles.wordpress.org/melchoyce/):

While we input session details (time, location, category, etc.) to session pages, that information doesn't get output in the session page itself. If you're linking someone to your session page, they'd still need to go and look at the schedule just to see when you're speaking. Can we render this information below the session description?

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4568#comment:1) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by coreymckrill. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1596734229132500)._

**Comment by ryelle** [comment]
Duplicate of #651, which has a bit more activity.
