### ISSUE TITLE
Remove global sponsor details from flagship event sites

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#636]
Imported from https://meta.trac.wordpress.org/ticket/4636 
Created by @hlashbrooke:

Currently, all WordCamp sites explicitly thank all of the global sponsors on the ticket page after purchase, as well as in the footer of all ticket purchase emails.

According to [our global sponsorship program](https://make.wordpress.org/community/2019-wordpress-global-community-sponsorship-program/), however, the global sponsorship funds do not apply to flagship events, but the thank you text is displayed for them too.

We should remove the global sponsor text from events that don't make use of global sponsor funds - currently, that includes WordCamp Europe, US and Asia and they all have their "Multi-Event Sponsor Region" setting set to "Excluded". It should be relatively straightforward to choose not to show the global sponsor thanks based on that field.

I don't currently have a local dev environment setup, but it looks like we should be able to do that in the `camptix-tweaks.php` file here: https://meta.trac.wordpress.org/browser/sites/trunk/wordcamp.org/public_html/wp-content/mu-plugins/camptix-tweaks/camptix-tweaks.php#L907

I think this should do the trick:

```
if( 436028 == $region_id ) {
  break;
}
```

(`436028` is the ID for the 'Excluded' region).

Am I perhaps underestimating the amount of work here?

This change would do a lot to remove the confusion that these messages create for attendees.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4636#comment:1) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by hlashbrooke. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1564402927032400)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4636#comment:2) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by coreymckrill. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1596734578136200)._

**Comment by timiwahalahti** [comment]
Asked for team feedback https://wordpress.slack.com/archives/C01U5R67F55/p1690603498407459

**Comment by timiwahalahti** [comment]
The current Global Sponsorship working group feels that global sponsors can be included in the tickets page and emails. Closing the issue. If opinions change on this, let's reopen or create a new issue.
