### ISSUE TITLE
Profile activity: WordCamp year shown twice

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#638]
Imported from https://meta.trac.wordpress.org/ticket/4675 
Created by @ePascalC:

As per picture, there is no need to add the WordCamp year if it is already present in the name.

**Comment by ghost** [comment]
Comment by @ePascalC:
 * [Capture.PNG](https://meta.trac.wordpress.org/attachment/ticket/4675/Capture.PNG) added

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4675#comment:1) by [@coffee2code](https://profiles.wordpress.org/coffee2code/):

I believe this falls on the WordCamp side of things and may've just been a temporary situation based on WordCamp naming that has since been corrected (though that wouldn't "fix" the activity entries that had already been created).

The activity log strings for WordCamp speakers (as cited in ticket's screenshot) is constructed [within the Profiles activity handler](https://meta.trac.wordpress.org/browser/sites/trunk/profiles.wordpress.org/public_html/wp-content/plugins/wporg-profiles-activity-handler/wporg-profiles-activity-handler.php?rev=3915#L507). It directly uses the `wordcamp_name` value as sent in the data payload from WordCamp.org. Which means "WordCamp Moscow 2018 2018" was what was sent to Profiles.

WordCamp [sends](https://meta.trac.wordpress.org/browser/sites/trunk/wordcamp.org/public_html/wp-content/plugins/wordcamp-participation-notifier/wordcamp-participation-notifier.php?rev=8908#L359) as the `wordcamp_name` payload the return value of `get_wordcamp_name()`. That function does [append a year](https://meta.trac.wordpress.org/browser/sites/trunk/wordcamp.org/public_html/wp-content/mu-plugins/4-helpers-wcpt.php?rev=8980#L126) to the WordCamp name provided in the corresponding post.

The function description says:

```
The results of bloginfo( 'name' ) don't always contain the year, but the title of the site's
corresponding `wordcamp` post is usually named 'WordCamp [Location]', so we can get
a consistent name most of the time by using that and adding the year (if available).
```

The code does not check to see if the post title already contains a year, so the convention probably is to not include the year there. WordCamp Moscow 2018 probably put the year in there. As speakers were confirmed, `get_wordcamp_name()` tacked on the year, resulting in "WordCamp Moscow 2018 2018". The activity entries would require a manual update of database fields to remove the duplicate year since they are stored as strings.

On the WordCamp side of things, `get_wordcamp_name()` should probably account for the possibility of a year in the post title and not append one if already present.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4675#comment:2) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by coreymckrill. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1596734833139100)._

**Comment by dd32** [comment]
Another WordCamp ran into it: https://wordpress.slack.com/archives/C08M59V3P/p1643867141915899
