### ISSUE TITLE
Add id to organizer block

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#642]
Imported from https://meta.trac.wordpress.org/ticket/4893 
Created by @ePascalC:

WordCamps create an organizer page (e.g. [but from some others pages it's nice to be able to link directly to an organizer (e.g. [https://2020.europe.wordcamp.org/organisers#org-pascal-casier](https://2020.europe.wordcamp.org/organisers/]),)) 

Proposal is to change
```<div class="wordcamp-organizer wordcamp-organizers__post slug-pascal-casier"```
to
```<div class="wordcamp-organizer wordcamp-organizers__post slug-pascal-casier" id="org-pascal-casier"```
or similar

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4893#comment:1) by [@vdwijngaert](https://profiles.wordpress.org/vdwijngaert/):
 * Keywords set to `Has Patch`

Well, seems simple enough, and it sure has its uses. I created a pull request in the WordCamp Github repository: https://github.com/WordPress/wordcamp.org/pull/294. 

Apologies if this isn't the normal way of things, just trying to help out :)

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4893#comment:2) by @ryelle:

Hi [@vdwijngaert](https://profiles.wordpress.org/vdwijngaert/) & @ePascalC — since the blocks can be used multiple times on a page, having IDs on the block content can cause invalid HTML. See [\[779\]](http://meta.trac.wordpress.org/changeset/779), when speaker IDs were deprecated.

You could use anchor links on each heading, and link to the organizer's team, like `https://2020.europe.wordcamp.org/organisers/#attendee-services`, would that work?

We could also look at allowing single Organizer pages, like `https://2020.europe.wordcamp.org/organisers/pascal-casier`, but I think we'll want to have more input on that before committing to it.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4893#comment:3) by @ePascalC:

Hi @ryelle 

I had first checked indeed if there were any archive/single pages for organisers but it seems those are not active. That might be the best way to go as pointing to the teams is not what we wanted to do AND not all WordCamps are probably creating teams.

So if the single pages can be activated, that would be great!

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4893#comment:4) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by iandunn. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1597943158005200)._

**Comment by ryelle** [comment]
Closing this issue as single organizer pages are available, see https://europe.wordcamp.org/2020/organizer/pascal-casier/

Fixed in https://github.com/WordPress/wordcamp.org/commit/3cafe4a9425c84a62c4bb2e19d75a3973cf36fca
