### ISSUE TITLE
WordCamp Sessions: Default sort order for Manage Sessions should be "Time"

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#646]
Imported from https://meta.trac.wordpress.org/ticket/24 
Created by [@danielbachhuber](https://profiles.wordpress.org/danielbachhuber/):

Because Sessions are closely tied to a schedule, the default sort order in the Manage Sessions view should be whatever post meta field is associated with "Time". ASC would work just fine.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/24#comment:2) by @iandunn:
 * Status set to `assigned`
 * Owner set to @iandunn

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/24#comment:3) by @iandunn:
 * Keywords set to `Good First Bug`

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/24#comment:4) by @iandunn:
 * Status set to `accepted`

**Comment by ghost** [comment]
Comment by [@WPStagecoach](https://profiles.wordpress.org/WPStagecoach/):
 * [24.diff](https://meta.trac.wordpress.org/attachment/ticket/24/24.diff) added

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/24#comment:5) by [@WPStagecoach](https://profiles.wordpress.org/WPStagecoach/):

I uploaded a patch that causes the Sessions to be listed by date in the admin panel.

**Comment by ghost** [comment]
Comment by [@WPStagecoach](https://profiles.wordpress.org/WPStagecoach/):
 * [24.2.diff](https://meta.trac.wordpress.org/attachment/ticket/24/24.2.diff) added

This is the patch to apply!

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/24#comment:6) by [@WPStagecoach](https://profiles.wordpress.org/WPStagecoach/):

Sorry--after I submitted the first patch, I found that someone already had start to implement this, so I used their function, and modified the logic a bit so that the default (blank) 'orderby' is set to ascend the time field.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/24#comment:7) by @iandunn:

This looks good, thanks Jonathan :)

A few small tweaks I'd suggest:

1. Add the date to the `Time` column, because when there are sessions from multiple days it can be confusing to see the times appear to be out of order.
1. Rename the column to `Session Date / Time` because it now includes the date, but we don't want it confused with the post's `Date` column. Another idea would be to just remove the Core `Date` column, since it's not that useful in this situation.
1. There are a few [coding standards](https://make.wordpress.org/core/handbook/coding-standards/php/) issues around whitespace usage.

A good follow-up patch would be to remove the old "voodoo" workaround because wordpress:#23268 is fixed now.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/24#comment:8) by @coreymckrill:
 * Keywords set to `Good First Bug` `Needs Refresh` `Needs Patch`

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/24#comment:9) by @iandunn:
 * Status set to `assigned`
 * Owner cleared

**Comment by ryelle** [comment]
This was added in https://github.com/WordPress/wordcamp.org/commit/6baf59fa8dd017c6a207391145e0d60dcfbae0ab & https://github.com/WordPress/wordcamp.org/commit/aaf4d733882c35dbd4e8c99e0d53c17941505f2f. Thanks for the initial patch, @WPStagecoach!
