### ISSUE TITLE
Replace apiFetch with withSelect 

### ISSUE THREAD

**Issue by vedanshujain** [WordPress/wordcamp.org#65]
`withSelect` could cache response across multiple blocks, so we should consider replacing `apiFetch` with it.

**Comment by vedanshujain** [comment]
@iandunn @coreymckrill Just an update here: I am working on having a common store for all our blocks. This will be helpful given that blocks are going to share data, (egs. Session<->Speakers, Schedule<->Sessions etc). I should have something ready soon, will update here then.

**Comment by coreymckrill** [comment]
Related: #69

**Comment by vedanshujain** [comment]
Closing in favor of #69.
