### ISSUE TITLE
De-List Default CoC Content

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#650]
Imported from https://meta.trac.wordpress.org/ticket/1845 
Created by [@melchoyce](https://profiles.wordpress.org/melchoyce/):

By default, the CoC included on each WordCamp site is contained in a list. The list also seems to come with a bunch of ```nbsp;```'s, which make the styling a bit wonky. 

Is there a reason the CoC needs to be in a list? Could this just be regular text? It would improve the display on many of WordCamp sites I've seen it on.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/1845#comment:2) by @iandunn:
 * Keywords set to `Needs Patch` `Good First Bug`
 * Status set to `accepted`
 * Owner set to @iandunn

It's just that way because we copied it from http://opensourcebridge.org/about/code-of-conduct/, but I agree it'd look better without the extra list formatting.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/1845#comment:3) by @iandunn:
 * Status set to `assigned`
 * Owner cleared

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/1845#comment:4) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by coreymckrill. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1582222066263100)._

**Comment by ryelle** [comment]
This was done in https://github.com/WordPress/wordcamp.org/pull/531 🎉
