### ISSUE TITLE
Add notification about combaining reimbursement requests

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#658]
Imported from https://meta.trac.wordpress.org/ticket/3286 
Created by @timiwahalahti:

In WordCamp organizers handbook it states that

 ... we urge all organizing teams to submit one reimbursement request per out-of pocket purchaser.

This can easily forgotten or not even noticed if team member has not read handbook deeply. We could and should show friendly notice about this always when organizer is on dashboard page which is related to reimbursements.

Easiest way to achieve this is check 'wcb_reimbursement' === $GET['post_type'] which applies on reimbursements listing and creating new one. Edit view already has reminder about this on "Payment Information" meta box, but it does not hurt to state it bigger when creating new, does it?

I'll make patch in few days.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3286#comment:1) by @coreymckrill:
 * Status set to `assigned`
 * Owner set to @timiwahalahti

**Comment by ghost** [comment]
Comment by @timiwahalahti:
 * [3286.diff](https://meta.trac.wordpress.org/attachment/ticket/3286/3286.diff) added

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3286#comment:2) by @timiwahalahti:
 * Keywords set to `Has Patch`

3286.diff contains patch for this. Notice is displayed when viewing listing of reimbursement requests or creating new. Message is same as in "Payment Information" meta box, notice level is warning.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3286#comment:3) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by sippis. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1540399572000100)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3286#comment:4) by @timiwahalahti:
 * Keywords set to `Has Patch` `2nd Opinion`

In WC bug scrub today we discussed this ticket a little.

Ian was hesitant to make it a notice, since it's not an urgent thing, and I worry that over-using them leads to notice-fatigue, where people just stop looking at them at all. It'd definitely be good to have a note on the page, though, at the very least. But maybe not with the notice colors/etc.

Corey suggested that notice could be `info` instead of `warning` and that we should also add `is-dismissable`. Maybe also a small piece of javascript to have it remember the user setting and not show it again.

I also started to think, that the notice should be shown only when submitting a new reimbursement request. Not in reimbursement request list. 

How much we get reimbursement requests that are not combined as we ask? How much pain does it cause? Would this notice fill some real-life need?

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3286#comment:5) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #community-team by sippis. [View the logs](https://wordpress.slack.com/archives/community-team/p1540405838000100)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3286#comment:6) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #community-team by sippis. [View the logs](https://wordpress.slack.com/archives/community-team/p1546530100095700)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/3286#comment:7) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by iandunn. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1587057246134900)._

**Comment by ryelle** [comment]
It looks like we've asked for user feedback on this issue twice with no responses (Oct 2018 & Jan 2019) — maybe this isn't an issue that needs a technical solution?

**Comment by timiwahalahti** [comment]
Yeah, closing this for reasons ryelle mentioned above.
