### ISSUE TITLE
Paginated states of the WordCamp homepage should 301 to the site root

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#664]
Imported from https://meta.trac.wordpress.org/ticket/4564 
Created by @jono-alderson:

E.g., https://central.wordcamp.org/page/5/ should 301 to https://central.wordcamp.org/

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4564#comment:1) by @iandunn:

That looks like the normal Core behavior when the homepage is setup to display a page. Seems like this should be a Core ticket instead?

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4564#comment:2) by @braders:

The canonical on this page seems to be confusing things further - it is pointing to the current page without the "/page/" segment. So e.g. the canonical on  https://central.wordcamp.org/page/5/ is https://central.wordcamp.org/5/.

Due to WordPress's redirect guessing, https://central.wordcamp.org/5/ is redirecting the the "5-reasons-you-should-attend-wordcamp-nyc" post, due the the presence of the "5" in the page title. 

I don't know if this is likely to be making matters worse from an SEO perspective?

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4564#comment:3) by @jono-alderson:

Yep, that's gonna be hurtin'.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4564#comment:2.4) by @braders:

Replying to [@braders](https://profiles.wordpress.org/braders/):
> The canonical on this page seems to be confusing things further - it is pointing to the current page without the "/page/" segment. So e.g. the canonical on  https://central.wordcamp.org/page/5/ is https://central.wordcamp.org/5/.
> 
> Due to WordPress's redirect guessing, https://central.wordcamp.org/5/ is redirecting the the "5-reasons-you-should-attend-wordcamp-nyc" post, due the the presence of the "5" in the page title. 
> 
> I don't know if this is likely to be making matters worse from an SEO perspective?

I have opened a core ticket to address the faulty canonical URL which is being produced on  central.wordcamp.org: [#WP49220](http://core.trac.wordpress.org/ticket/49220)

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4564#comment:5) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by coreymckrill. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1596733574123800)._

**Comment by ryelle** [comment]
It looks like the canonical link on central is working correctly now. I think the lack of 301 redirect on `/page/*` links is a core issue (I can reproduce it on other sites). I'm going to close this issue, but please comment or open a new issue if there's still a problem with Central.
