### ISSUE TITLE
Text rendering issues in "Favorite sessions" emails when special characters are present

### ISSUE THREAD

**Issue by marcochiesi** [WordPress/wordcamp.org#665]
Hi there,
I am a member of the organizing team for the upcoming WordCamp Italy. We have discovered an issue regarding the "Favorite sessions" feature.
In the "Favorite sessions" emails, there's a text rendering issue occurring when session titles contain special characters like `'`, `-`, `&` because they are translated to the corresponding HTML entities and look ugly and unreadable in the (plain-text) emails.

**To reproduce**

1. Create a session that includes special character like `'`, `-`, `&`
2. In the frontend schedule page select the session and request to receive the list via email
3. Check the email received. The characters were converted to HTML entities, but since the email is in plain text format, they are not rendered.

**Expected behavior**

Any special character should be converted back to plain text since these emails are plain text and not HTML.

**Suggested solution**

An easy fix could be to use the `htmlspecialchars_decode` function when printing the session title.
Alternatively, it would be possible to avoid the application of the `the_title` filter to the session title in the function `generate_plaintext_fav_sessions`.
At the moment we adopted the workaround of avoiding such characters whenever possible to prevent the replacement made by `wptexturize` via the `the_title` filter (i.e. using `’` in place of `'`), but it's not ideal.

**Screenshots**

![image](https://user-images.githubusercontent.com/2298248/95494555-6641c080-099e-11eb-8657-5a4a514a7d65.png)

**WordCamp**

This seems to be a general issue. Our page is here https://2020.italia.wordcamp.org/schedule (not yet published).

**System (please complete the following information):**

 - Device: any
 - OS: any
 - Browser: any
 - Version: any

**Comment by iandunn** [comment]
That all makes sense, thanks for catching that 👍🏻
