### ISSUE TITLE
`wordcamp-speaker-sessions-list` styles don't match mockups

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#67]
- [x] The class name in JSX is singular, but in CSS it's plural, so the styles aren't being applied. This doesn't fix the issue, though.
- [x] The session title and dates are on the same line b/c JSX strips out whitespace & newlines in some situations, and because of the default styles of the `a` and `span` elements.
- [x] The `ul` also inherits a `left`- and `bottom-margin`.
- [x] The session info isn't showing up in the PHP view for me either.

**Comment by iandunn** [comment]
cc @melchoyce as an FYI

**Comment by iandunn** [comment]
Related to #62

**Comment by vedanshujain** [comment]
@iandunn @coreymckrill should we break this into multiple issues?

**Comment by iandunn** [comment]
Personally it feels like pre-emptive overkill to create an issue just to rename a class from singular to plural, etc, but there's probably a blurry line there.

Creating a separate issue/card/etc for a bunch of little things feels like a lot of extra overhead work, and then more work to organize them, keep them updated, etc.

That's just my personal preference, though. If you feel like it'd be easier for you to work on your cards if they were broken up into smaller ones, then you should definitely feel free to do that.

Or if the discussion on an issue grows beyond what's manageable, then it'd also be good to break it off into smaller cards.

**Comment by coreymckrill** [comment]
Related: #94

**Comment by coreymckrill** [comment]
> The session info isn't showing up in the PHP view

Fixed with https://meta.trac.wordpress.org/changeset/8630

**Comment by coreymckrill** [comment]
> The class name in JSX is singular, but in CSS it's plural
> The session title and dates are on the same line b/c JSX strips out whitespace & newlines in some situations
> The ul also inherits a left- and bottom-margin.

Fixed with https://meta.trac.wordpress.org/changeset/8631
