### ISSUE TITLE
Custom CSS outputting HTML entities instead of correct characters

### ISSUE THREAD

**Issue by megmorsie** [WordPress/wordcamp.org#678]
**Describe the bug**

I compared to a fresh WordPress install to verify, it seems like it's only happening on WordCamp sites. The `>` symbol is being output as `&gt;` in the customizer CSS output.

**To reproduce**

1. Log into a WordCamp site with admin access.
2. Click on Customize > Custom CSS.
3. Enter CSS with `>` selector. 
My example uses:
`#subscribe-submit > button {
	background: gray;
}` 
4. Notice preview updates.
5. Publish & look at Customizer output in inspector, `>` is replaced with `&gt;`

Might be related to #574?

**Expected behavior**

I would expect the output to have `>` since it's a proper CSS selector. Or if it must be sanitized out, showing an error message or something to indicate that it's not an allowed character would be nice.

**Screenshots**

I made a [screen recording](https://www.loom.com/share/210e3268becf43a7a535659b35b5e9fd) comparing the WordCamp site with a fresh WP install.

**WordCamp**

Noticed on [NEO](https://neo.wordcamp.org/2021/) but I'm guessing other sites have the same issue.

**System (please complete the following information):**

 - Device: MacBook
 - OS: MacOS
 - Browser: Firefox
 - Version: 86.0.1

**Comment by CdrMarks** [comment]
This also affects the make.wordpress.org network ([per Dion](https://wordpress.slack.com/archives/C08M59V3P/p1635732473018000)).

I opened https://github.com/Automattic/jetpack/issues/21603 earlier today.

**Comment by CdrMarks** [comment]
The [Remote CSS Plugin](https://make.wordpress.org/community/2015/11/24/remote-css-plugin-launched-on-wordcamp-org/) can be used as a workaround if needed.  I tested it on [Birmingham 2022](https://birmingham.wordcamp.org/2022/wp-admin/admin-ajax.php?action=wordcamp_remote_css&ver=878) and was able to see `>` show as the symbol.
