### ISSUE TITLE
Using the schedule block will override  Open Graph Tags.

### ISSUE THREAD

**Issue by rocket-martue** [WordPress/wordcamp.org#679]
Using the schedule block will override  Open Graph Tags.
https://japan.wordcamp.org/2021/schedule/

**Comment by iandunn** [comment]
🤔 , it shouldn't.

Which `og:` tag is being overridden? What do you want the value to be, and what does it change to be after you add the Schedule block?

**Comment by rocket-martue** [comment]
All `og:` tags will be overwritten. They will be replaced by the `og:` tags of the session with the earliest posting date.
Without the schedule block, the page's `og:` tags will be output correctly.

**Comment by iandunn** [comment]
Ah, ok, I'm able to reproduce that, thanks!
