### ISSUE TITLE
Rename country "Macedonia" to "North Macedonia" in camptix

### ISSUE THREAD

**Issue by rootjosh** [WordPress/wordcamp.org#683]
Incorrect country naming convention in the WCEU registration list. Specifically, regarding the [long running dispute](https://en.wikipedia.org/wiki/Macedonia_naming_dispute) over the name "Macedonia" between Greece and what was then the country of Macedonia. This dispute was settled in 2019 with the changing of Macedonia to North Macedonia with the signing of the [Prespa Agreement](https://en.wikipedia.org/wiki/Prespa_agreement). Camptix should be updated to reflect this.

**To reproduce**

1. Go to https://europe.wordcamp.org/2021/registration/?tix_action=attendee_info#tix
2. Click on 'country'
3. Scroll down to look for 'North Macedonia'
4. Notice that 'Macedonia' is the only option

**Expected behavior**

See North Macedonia on the country list, not see Macedonia

**Screenshots**

<img width="960" alt="Screen Shot 2021-06-01 at 8 48 23 AM" src="https://user-images.githubusercontent.com/9398055/120357807-b0274000-c2ba-11eb-9ca3-18e02e9f8251.png">

**WordCamp**

https://europe.wordcamp.org/2021/registration/?tix_action=attendee_info#tix

**System (please complete the following information):**

 - Device: laptop, iphone
 - OS: OSX, iOS
 - Browser Firefox, mobile Safari

**Comment by iandunn** [comment]
xref https://github.com/Automattic/wp-cldr/pull/95
