### ISSUE TITLE
Global Sponsorship Pause - Agreement Uploading

### ISSUE THREAD

**Issue by megmorsie** [WordPress/wordcamp.org#684]
Note: I don't expect this to be fixed and it's a really minor issue but wanted to report just for archival purposes or in case related improvements can be made!

**Describe the bug**

At the start of 2021, the global sponsorship program was suspended/paused. The site typically does not allow upload for sponsor agreements for any flagged as global sponsors (because the Community Team handles these). But for the events happening in 2021, we haven't been able to upload the sponsor agreements that we needed to collect for those companies.

**To reproduce**

1. Visit a 2021 WordCamp site's admin 
2. Open a sponsor who _was_ a global sponsor in 2020 ([example](https://neo.wordcamp.org/2021/wp-admin/post.php?post=28&action=edit&classic-editor__forget))
3. Scroll in sidebar to Sponsor Agreement
4. The message "This sponsor has already signed a global sponsorship agreement." shows with no upload button.

**Expected behavior**

Would expect to be able to upload any agreements that WordCamp organizers need to collect.

**Screenshots**

<img width="279" alt="Screen Shot 2021-06-07 at 9 36 45 AM" src="https://user-images.githubusercontent.com/7850664/121026788-6f28a300-c774-11eb-8360-b6b5371cb117.png">

**WordCamp**

Any of the 2021 Camps that have an ex-global sponsor sponsoring them this year.

**System:**

 - Device: macbook pro
 - OS: Big Sur
 - Browser: firefox v 88.0.1

**Comment by timiwahalahti** [comment]
This was exceptional case and global sponsorhip program has resumed.
