### ISSUE TITLE
Session block start time timezone confusion

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/wordcamp.org#689]
**Describe the bug**

I'm in CDT (UTC-06:00).  When setting the start time for a session on a site in another timezone, the time in the date/time chooser is different from the time in the right sidebar.

**To reproduce**

1. Set your local computer's timezone to US/Central.
2. Set the WordCamp site to have the Timezone value of New York (US/Eastern).  
3. Create a new Session
4. In the right sidebar, on the Session panel tab, under Session Info, click the hyperlinked Day & Time.
5. Set the date and time of the event in EDT.
6. Notice the time in the right sidebar is off by one hour.

**Expected behavior**

I expect to see the Day & Time in the right sidebar to match what I selected in step 5 above.

**Screenshots**
![image](https://user-images.githubusercontent.com/3489003/125893882-c9f89eb3-2bbf-4893-b3d6-ea8f4418b046.png)

**WordCamp**

Tested with https://us.wordcamp.org/2021/

**System (please complete the following information):**

 - Device: Laptop
 - OS: Windows 10
 - Browser Chrome
 - Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by ryelle** [comment]
@CdrMarks Do you see this same problem when changing the date on posts (like scheduling a future post)?

**Comment by CdrMarks** [comment]
@ryelle No, I cannot reproduce this on a post to be published in the future.  
![image](https://user-images.githubusercontent.com/3489003/125967826-31fcaaac-f0f6-41eb-98e6-a05344daec01.png)

FYI, my local computer's time is still on CDT.
