### ISSUE TITLE
`selectedPosts is undefined` fatal error in `SponsorBlockContent::render()`

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#70]
`TypeError: "selectedPosts is undefined"  render block-content.js:163`

1. Add new Sponsors block
1. Add an individual sponsor to the block
1. Sort by sponsor level

Let me know if you can't reproduce, there may be some extra conditions that are necessary, which are setup in my environment but not yours.

*(Note to self: I used the `Backup Buddy` post on `2016.misc` to reproduce this)*

**Comment by coreymckrill** [comment]
This will no longer be relevant when #69 gets merged.

**Comment by coreymckrill** [comment]
Fixed by #69.
