### ISSUE TITLE
Sponsor Invoices: Postbox wcbsi_sponsor_invoice default location is sidebar

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/wordcamp.org#707]
**Describe the bug**

The default location for the Sponsor Invoice postbox is in the right sidebar.

**To reproduce**

1. Go to a WordCamp
2. Mouse over Budget in the menu
3. Click on Sponsor Invoices
4. Click the Add New button
5. See the Sponsor Invoices postbox in the right sidebar. It's within the following div:
```
<div id="postbox-container-1" class="postbox-container">
   <div id="side-sortables" class="meta-box-sortables ui-sortable">
   ...
   </div>
</div>
```

**Expected behavior**

The Sponsor Invoice postbox should be in the main portion of the screen.

I believe the `wcbsi_sponsor_invoice` postbox needs to be moved from `postbox-container1`'s `side-sortables` to `postbox-container2`'s `normal-sortables`.

**Screenshots**
![image](https://user-images.githubusercontent.com/3489003/139884950-fb1e5e7e-e507-4c17-89ad-90e69f77eda9.png)

**WordCamp**
I expect this affects all WordCamps.  Was able to confirm on:
* https://birmingham.wordcamp.org/2022
* https://us.wordcamp.org/2021/

**System (please complete the following information):**
 - Device: Laptop
 - OS: MacBook Por
 - Browser Chrome
 - Version 95.0.4638.54 (Official Build) (x86_64)

**Comment by timiwahalahti** [comment]
Cannot reproduce.
