### ISSUE TITLE
Do not allow creating WordCamps in central for other than deputies

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/wordcamp.org#728]
It looks like everyone that has caps to access the WordCamps on the Central site, eg. previous organisers, can use the core "Add new" functionality to add new WordCamp to our tracker tool. Only deputies should be able to do this, as organisers should always submit an application from which the post is automatically generated.

Related: https://secure.helpscout.net/conversation/1768446604/127687/

**Comment by iandunn** [comment]
#734 was a duplicate that has some additional info/conversation.

**Comment by timiwahalahti** [comment]
Reverted in d7ffc3cedf6380b6b95263a8e8120f8d31d48bbb so need to take new look.

**Comment by timiwahalahti** [comment]
https://github.com/WordPress/wordcamp.org/pull/1041 affects this
