### ISSUE TITLE
Attendees list, button "mark as attended" with longer text (another language)

### ISSUE THREAD

**Issue by patriciabt** [WordPress/wordcamp.org#732]
**Describe the bug**

in the WordCamp dashboard, attendee list, this button "Mark as attended" overlaps onto the next column if the text is long (as it is the case in French for inclusive language both words are mentioned by the polyglot team) and I'm sure some other languages must have long texts too.

**To reproduce**

1. Set the WordCamp admin to French in your profile :)
2. See the dashboard attendees list (select "Billets", then "Participants")

**Expected behavior**

It would be great if the button could wrap and have a max width 

**Screenshots**

See attached screenshot below

**WordCamp**
If this is a problem on a specific WordCamp's site, list the site or page URL here.

https://geneve.wordcamp.org/2022/wp-admin/edit.php?post_type=tix_attendee

**System (please complete the following information):**

 - Device: [Lenovo Yoga laptop]
 - OS: [Windows 11]
 - Browser [tested with Chrome and Firefox]
 - Version [latest]

**Security Issues**
N/A

![attendee-list-french](https://user-images.githubusercontent.com/1843660/153917064-2e30b338-0e6c-4af8-9478-682baa6bc950.png)

**Comment by ocean90** [comment]
As suggested in https://meta.trac.wordpress.org/ticket/6013, adding spaces before/after the slash should cause normal word wraps here too.

**Comment by patriciabt** [comment]
Thank you @ocean90. I just suggested on the https://translate.wordpress.org/projects/meta/wordcamp/fr/

**Comment by patriciabt** [comment]
All OK now, the French translation team solved the issue with "Marquer comme participant·e" (inclusive and now standard form). Thanks everyone
