### ISSUE TITLE
Restrict manual WCPT post creation

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#734]
@NewYorkerLaura [reported](https://wordpress.slack.com/archives/C08M59V3P/p1645192555712969) that she can create wordcamp/meetup posts on Central, despite having a `contributor` role.

This looks intentional from the code, but we might want to consider if it's still desired.

https://github.com/WordPress/wordcamp.org/blob/bddaa4eaf5aea877d9f897aa564d677004db7fca/public_html/wp-content/plugins/wcpt/wcpt-wordcamp/wordcamp-loader.php#L114-L128

Do we need manual post creation now that they're automatically created from applications? I'm guessing no, but we need to dig into it more. 

It might be good to still let super admins manually create them, just in case, but maybe not since that would probably result in missing metadata.

**Comment by timiwahalahti** [comment]
Duplicate of #728 

> Do we need manual post creation now that they're automatically created from applications? I'm guessing no, but we need to dig into it more.

Sometimes deputies do need this. For example WCEU, WCUS and for some situations with Meetups. But other than deputies shouldn't be able to create posts. At least few have created post and thought that is the "application" process.

**Comment by iandunn** [comment]
Ah, I missed that issue, thanks!
