### ISSUE TITLE
Convert Multi Event Sponsor post type to Gutenberg

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#735]
It'd be nice to be able to use the new editor. We need to make sure that any custom code is ported, so that all the current functionality is preserved.

**Comment by iandunn** [comment]
Fixed in 6e1e724470997f65327d4904f4bef61482bc77db

**Comment by iandunn** [comment]
FYI @harishankerr, I converted all the published Multi Event Sponsor posts to use blocks.

**Comment by iandunn** [comment]
In the editor, the content will appear a bit different on Central than other sites, because it's partially dependent on which theme is active.

**Comment by harishankerr** [comment]
This is fantastic! I just checked and can confirm that the block editor features are working perfect. Thanks for wrangling this, @iandunn! 👏
