### ISSUE TITLE
CSS Validator goes wrong

### ISSUE THREAD

**Issue by MaximeCulea** [WordPress/wordcamp.org#737]
Hi there 👋 

**Explanations**

We wanted to use the following CSS attribute, but the CSS Validator API is not allowing it, resulting in not adding it to the CSS Stylesheet.
I am talking about the `aspect-ratio` property.
Also note that:
* It is fully accepted in CAN I USE: https://caniuse.com/?search=aspect-ratio
* The online CSS validator accepts it: http://jigsaw.w3.org/css-validator/validator

Steps to reproduce the behaviour:
1. Add the  `aspect-ratio` property on the customizer (additional CSS) or remote css.
2. Even if the property is acceptable, it is wrapped out from the final CSS Stylesheet.

**WordCamp**

This is related to the WordCamp Genève 2022:
- link to the customizer: https://geneve.wordcamp.org/2022/wp-admin/customize.php?return=%2F2022%2Fwp-admin%2Frevision.php%3Frevision%3D5726
- link to the distant CSS: https://github.com/WPSwitzerland/wordcampgeneve2022/blob/main/assets/css/app.css#L387
- link to the website: https://geneve.wordcamp.org/2022/

**Screenshots**

Some screenshots:
* Distant CSS with the property:
![css-distant](https://user-images.githubusercontent.com/5576409/155734088-706d72db-9b8a-4eab-bc68-ab6edb2b2f9b.PNG)

* Customizer CSS with the property:
![css-customizer](https://user-images.githubusercontent.com/5576409/155734090-17d96131-2da4-44ec-bf8c-e0ea2c50d73d.PNG)

* As a result, in frontend side, the property has been deleted:
![css-stylesheet](https://user-images.githubusercontent.com/5576409/155734082-09ffa9bb-ccb7-4eb6-976e-cc72b23e6a0f.PNG)

Many thanks for your help and input.

**Comment by ryelle** [comment]
I think CSSTidy from Jetpack is stripping that property out. It should be safe to use, so it can be added to [the custom safelist](https://github.com/WordPress/wordcamp.org/blob/8e026c850ebeeedfc65856072e424268e60d5c42/public_html/wp-content/mu-plugins/jetpack-tweaks/css-sanitization.php#L183).

**Comment by coreymckrill** [comment]
@MaximeCulea This should be fixed now. I re-synced the stylesheet from your GitHub repo, and `aspect-ratio` is now being applied when I check in my browser.

**Comment by MaximeCulea** [comment]
@coreymckrill yes it is now 
![image](https://user-images.githubusercontent.com/5576409/156068660-df3b0202-68b9-4498-8cca-67c31c2e9162.png)

Many thx @ryelle & @coreymckrill! :D
