### ISSUE TITLE
Make `mode` placeholder value more intuitive

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#74]
Migrated from https://github.com/WordPress/wordcamp.org/pull/33#discussion_r266174514

> This feels like of unintuitive to me, like from the context I expect mode to be a boolean, but then it's name doesn't describe what it is, so I'm left confused.
> 
> I had to look through other parts of the code to realize it's a string that has an empty value until a mode like "all speakers" or "group of speakers" is selected.
> 
> I wonder if the code would be more descriptive/self-documenting/obvious if we gave mode an initial value of placeholder, and then changed things like this to read 'placeholder' !== mode ?

**Comment by ryelle** [comment]
I'm going to close this issue, I don't think we gain much by making this change at this time, but we could think about this for future blocks. Feel free to reopen if you disagree.
