### ISSUE TITLE
Adding session time is one hour ahead

### ISSUE THREAD

**Issue by vertizio** [WordPress/wordcamp.org#748]
**Describe the bug**
When adding a new session the starting time that is submitted in the session info time field is one hour ahead of the session time that is displayed in the sessions list.

**To reproduce**

Steps to reproduce the behaviour:
1. Go to 'Sessions -> Add New'
2. Enter a session title and set a time, eg.  '11:00'

![Selectie_333](https://user-images.githubusercontent.com/2759239/160779680-a3aa15fd-3755-43a1-af63-6e0b95f866c7.png)

3. Publish the session
4. Go to the 'Sessions' list and see the date of the session being '10:00'

![Selectie_332](https://user-images.githubusercontent.com/2759239/160781339-c74f3509-4d3e-4f23-a23b-7fb2bf43ad60.png)

5. The final schedule shows the data as entered in the session info block and not as shown in the session list.

**Expected behaviour**

When submitting '11:00'  as time, it should show '11:00' in the sessions list.
If this is intentional it will confuse volunteers and new organisers.

**WordCamp**

I've seen this in other WordCamp sites too.

**System (please complete the following information):**

 - Device: desktop
 - OS: Linux
 - Browser: FF
 - Version: 98.0.1

**Comment by ryelle** [comment]
@vertizio What timezone is the site set to, and what timezone are you in currently?

**Comment by vertizio** [comment]
@ryelle I'm on CEST and the site is on WEST.

**Comment by ryelle** [comment]
Okay, it sounds like the input has a bug, and it's saving the time in your local timezone rather than the site timezone. Is that correct, that `11:00 CEST` would be `10:00 WEST`?

**Comment by vertizio** [comment]
@ryelle Couldn't it be easier to store the info just the way it is entered? I don't see a reason for converting the times in the backend itself. When we add sessions to the schedule, it should match the time zone of the host city. If you want to convert times it should be done only for the visitor, not for the organiser.

**Comment by ryelle** [comment]
> If you want to convert times it should be done only for the visitor, not for the organiser.

Yes, you _should_ be entering times in the site (event) timezone. In the admin, it should show you the times in the site timezone. The bug here is that despite the screenshot saying you've entering the time in WEST, it's actually saving it from CEST.
