### ISSUE TITLE
Option to choose the display of session times

### ISSUE THREAD

**Issue by vertizio** [WordPress/wordcamp.org#753]
Before 2020 the times for the WordCamp sessions were displayed according to the timezone of the site, or actually the city/country hosting the WordCamp. When we moved over to online events it was decided to display the times for the sessions according to the time settings in the browser of the visitor (correct me if I'm wrong here).

Now that we're returning back to in person events, but also still seeing online events, it would be great to have the organisers of the event choose how the times in the schedule are being displayed: depending on the type event (online or in person) based upon host city/country or based upon browser settings. 
May be just flipping a button in the settings we could offer and satisfy both worlds.

Right now I'm organising WCEU and I want to be able to have my attendees see the times that they will expect to see when they are in Porto, otherwise people may end up too late for registration or a particular session.

**Comment by ryelle** [comment]
Past discussion on session time + timezones: https://github.com/WordPress/wordcamp.org/issues/562, https://github.com/WordPress/wordcamp.org/issues/565, https://github.com/WordPress/wordcamp.org/issues/492, and the PR that added this, https://github.com/WordPress/wordcamp.org/pull/696.

Currently, the schedule block uses the viewer's timezone, and labels it in the grid — for example [the WCUS 2021 schedule](https://us.wordcamp.org/2021/schedule/) shows content starting at 11:45 EDT, then 12:00 EDT, and so on.

<img width="602" alt="" src="https://user-images.githubusercontent.com/541093/162239467-627f944d-f6b1-4068-b23f-13d328e57dfa.png">

Maybe there's a better way to show the timezone, to make it more visible?

> depending on the type event (online or in person) based upon host city/country or based upon browser settings.

I think (hope) we'll still see events live-streaming, even if they're primarily in-person events, so I'm not sure basing it on the type of event would work. Same with having a single setting on the schedule block, but at least in that case organizers can add a note above the schedule explaining the timezone.

There's also the idea of a frontend setting, so the viewer can switch between event timezone & local time… Or maybe a little warning that shows when the viewer is not in the event's timezone?

**Comment by vertizio** [comment]
I'm not a fan of adding a note above or below the schedule. There's a lot of info on that page already and people are poor readers.
My simplest solution is: change the setting in wp-admin. It can be either: display times according to the timezone of the site, or display times according to the browser settings.

**Comment by timiwahalahti** [comment]
WordCamps do have a "virtual event" checkbox on the Central side where we manage events. Maybe this info could be used so that "virtual events" have their session times shown in users timezone and for non-virtual events times would be in a timezone that the site is set to (I think this was the case with the previous shortcode implementation). In addition to times on site timezone on non-virtual events, time could be also shown in users timezone with a smaller font below the local time. This way the block would take into account virtual, non-virtual and also non-virtual + stream events.

**Comment by ryelle** [comment]
I think the fastest fix would be to show both timezones on the schedule, maybe with an option on the block for which to use. Checking based on the type of event could work, but this seems like the kind of thing organizers want to control 🙂
