### ISSUE TITLE
Set the heading level of the speaker's name in the speakers block

### ISSUE THREAD

**Issue by vertizio** [WordPress/wordcamp.org#755]
In the speakers block speaker names get h3 assigned, but when you have a post with only an h1 for the page title followed by a short paragraph and then the speakers block, it will trigger an error for a11y.

The [speakers announcement post](https://europe.wordcamp.org/2022/wceu-speakers-group-2/) on the WCEU site shows the following structure for a11y:
![Screenshot 2022-04-08 at 10 53 53](https://user-images.githubusercontent.com/2759239/162408046-ad45e02b-0b2c-4756-b883-c4820e6b8177.png)

We could solve this by simply adding an h2 line, but often this doesn't make common sense as the speakers block is the most important part of the page.

**Suggested solution**
Let the author pick the heading level for the speaker's name: h2, h3, h4, h5... 
Other solutions are fine too, just as long as they will satisfy a11y checks.

**Comment by ryelle** [comment]
@vertizio Could you use the Query Loop block, and select the Speakers post type? If you use that in combination with speaker groups, it should give you the control you're asking for.

**Comment by vertizio** [comment]
@ryelle Thanks! Exploring it, seems to do the trick.
