### ISSUE TITLE
All: "Select" label margins in placeholders

### ISSUE THREAD

**Issue by melchoyce** [WordPress/wordcamp.org#77]
Add 1em of margin-top on the "select" labels:

![image](https://user-images.githubusercontent.com/2846578/55988187-3a426380-5c71-11e9-916d-b45a851a9c06.png)

**Comment by ryelle** [comment]
@melchoyce I'm not clear on where you want the margin, can you add an arrow where you want more space? Here's an up-to-date screenshot of how the empty content placeholder looks:

![Screen Shot 2019-07-19 at 11 59 43 AM](https://user-images.githubusercontent.com/541093/61548885-be4c7a00-aa1c-11e9-87c9-3606708466d9.png)

**Comment by melchoyce** [comment]
Looks like it was fixed — the dropdown and button were previously stacked instead of inline. 

Any chance we could match the height for both the dropdown and button?

**Comment by ryelle** [comment]
The button height was fixed in #174, so considering this closed.
