### ISSUE TITLE
wordcamp-participation-notifier.php fails to require wporg-mu-plugins/pub/profile-helpers.php

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/wordcamp.org#776]
**Describe the bug**

On a new install of the wordcamp.org evironment via Docker, this error is encountered.

>Warning: require_once(/usr/src/public_html/wp-content/mu-plugins-private/wporg-mu-plugins/pub/profile-helpers.php): failed to open stream: No such file or directory in /usr/src/public_html/wp-content/plugins/wordcamp-participation-notifier/wordcamp-participation-notifier.php on line 29 Fatal error: require_once(): Failed opening required '/usr/src/public_html/wp-content/mu-plugins-private/wporg-mu-plugins/pub/profile-helpers.php' (include_path='.:/usr/local/lib/php') in /usr/src/public_html/wp-content/plugins/wordcamp-participation-notifier/wordcamp-participation-notifier.php on line 29 Notice: Function is_embed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /usr/src/public_html/mu/wp-includes/functions.php on line 5831 Notice: Function is_search was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /usr/src/public_html/mu/wp-includes/functions.php on line 5831 Notice: Function is_offline was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /usr/src/public_html/mu/wp-includes/functions.php on line 5831 Notice: Function is_500 was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /usr/src/public_html/mu/wp-includes/functions.php on line 5831
There has been a critical error on this website.

This line was lasted edited 19 days ago via https://github.com/WordPress/wordcamp.org/commit/89b2afc3797183a642fca60d75b6a8da77589f54

**To reproduce**

1. From a clean install, follow the instructions for https://github.com/WordPress/wordcamp.org/blob/production/.docker/readme.md
2. Complete the `docker compose up` command in step 7
3. Browse to https://central.wordcamp.test/
4. See error (above)

**Expected behavior**

See 
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/3489003/170888179-8d68aa89-d26e-4bbc-ad45-62e1ee2e2972.png">

**Workaround**
Comment line 29 of wordcamp-participation-notifier.php

**WordCamp**

local wordcamp.test

**System (please complete the following information):**

 - Device: Laptop
 - OS: MBP
 - Browser: Chrome
 - Version: 102.0.5005.61 (Official Build) (x86_64)

**Comment by iandunn** [comment]
Related https://github.com/WordPress/wordcamp.org/issues/769

**Comment by iandunn** [comment]
🤔 , does this line not return early for you?

https://github.com/WordPress/wordcamp.org/blob/89b2afc3797183a642fca60d75b6a8da77589f54/public_html/wp-content/plugins/wordcamp-participation-notifier/wordcamp-participation-notifier.php#L13-L20

**Comment by CdrMarks** [comment]
@iandunn, I modified those line to the following as a test:
```
if ( 'local' === wp_get_environment_type() ) {
	return;
} else {
	wp_die( "WP Env:" . wp_get_environment_type() );
}
```
Here is the the output I'm seeing:
> Notice: Function is_embed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /usr/src/public_html/mu/wp-includes/functions.php on line 5831 Notice: Function is_search was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /usr/src/public_html/mu/wp-includes/functions.php on line 5831 Notice: Function is_offline was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /usr/src/public_html/mu/wp-includes/functions.php on line 5831 Notice: Function is_500 was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /usr/src/public_html/mu/wp-includes/functions.php on line 5831
> 
> WP Env:production

My local is running on wordpress.test.

**Comment by iandunn** [comment]
Ah, that's right. We've got `WORDCAMP_ENVIRONMENT === 'local'` that predates environment types in Core, and we haven't migrated yet. There's some inconsistencies between how we you dev/prod and how Core does, IIRC.

The best fix for this case is probably something like

```diff
-if ( 'local' === wp_get_environment_type() ) {
+if ( 'local' === WORDCAMP_ENVIRONMENT ) {
	return;
}
```

**Comment by CdrMarks** [comment]
@iandunn, the suggested code change above resolved the error I was seeing.  Does it makes sense to update the repository with an update to try to correct this for the next person who tries to setup a local environment with Docker?
