### ISSUE TITLE
Unable to create a new WordCamp's site on local via Docker

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/wordcamp.org#778]
**Describe the bug**

[Using Docker for a standalone WordCamp.org installation](https://github.com/WordPress/wordcamp.org/blob/production/.docker/readme.md), I was unable to create a new site for a WordCamp.

**To reproduce**

1. Follow the instructions at [Using Docker for a standalone WordCamp.org installation](https://github.com/WordPress/wordcamp.org/blob/production/.docker/readme.md) in the section under Initial Setup.
2. Browse to https://central.wordcamp.test/wp-admin/  and login if necessary
3. Go to WordCamps > Add New
4. Create a new WordCamp "Ryan 2022"
5. Advance the site through the status to "In Pre-Planning"
6. Enter the site URL https://ryan.wordcamp.test/2022/ and check the box to Create site in network
7. Add the ryan.wordcamp.test host in my hosts file
8. Browse to https://ryan.wordcamp.test/2022/
9. See a "Too many redirects" browser message

**Expected behavior**

I'd see the new site I just created.

**Comment by 2ndkauboy** [comment]
This is connected to #782. After changing it to a subdirs install, I was able to do this by choosing something like `/2022-europe` when creating the new site and then updating it to `http://wordcamp.test/2022-europe/` in the site "Info" settings.

**Comment by iandunn** [comment]
#933 may have fixed this one too, do you mind testing?

**Comment by timiwahalahti** [comment]
I tested creating a new site, and it worked as expected.
