### ISSUE TITLE
Coming soon mode: site tagline visible and can leak details

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/wordcamp.org#779]
When Coming Soon mode is on, the tagline of the site is sent to the browser and thus is visible for visitors and social media shares. In some rare cases, like WordCamp Europe, the site tagline can contain information that should not be visible when CS is on e.g. location or dates of the next event.

**To reproduce**
1. Go to Settings > General
2. Set a tagline
3. Activate Coming Soon mode
4. Open site in private mode
5. Verify from HTML source

**Expected behavior**

When Coming Soon mode is on, the site tagline should not be visible.

Props @vertizio for reporting

**Comment by maximebj** [comment]
Hi Everybody, I would add another bug concerning coming soon. 

I'm lead organizer on the WordCamp Lyon event and someone reported me this. 

When publishing a post on our website, with coming soon mode ON :
- people can’t see the post (neither the website) :white_check_mark:
- people can’t see the post through the REST API :white_check_mark:
- but the RSS feed publishes the post so people following the feed can see the title and the whole content :x:

You can try on [lyon.wordcamp.org/2022/](http://lyon.wordcamp.org/2022/) (The will be published soon though)

**Comment by timiwahalahti** [comment]
It's a bit tricky to prevent published posts from being leaked since the post is sent also to wordpress.org profile activity, where its title and URL can be found. Delaying the activity notification until coming soon mode is disabled might be possible, but probably not worth it due to it needing a bit more coding. Also for similar reasons, RSS currently exposes the posts.

In #546 there's ongoing work to add a notification which makes organisers aware of this.
