### ISSUE TITLE
Unable to access admin for new WordCamp site in Docker local

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/wordcamp.org#782]
**Describe the bug**

After setting up a local environment running using the [Docker](https://github.com/WordPress/wordcamp.org/blob/production/.docker/readme.md) instructions, and creating a new WordCamp and its site, I was unable to browse to the site.

Blocking: #777 

**To reproduce**

1. Setup your local environment using [Docker](https://github.com/WordPress/wordcamp.org/blob/production/.docker/readme.md).
2. Create a new WordCamp at https://central.wordcamp.test/wp-admin/post-new.php?post_type=wordcamp.  Mine was `Ryan 2022`.
3. Advance the WordCamp to a status of "Needs Site" and enter any required information.
4. Fill in the URL field (mine was `https://ryan.wordcamp.test/2022/`), check the box to `Created site in network`, and change the status to `Needs Crowdsignal Account`.
5. Add to my `/etc/hosts` file an entry for my WordCamp.  Mine is
> 127.0.0.1 	wordcamp.test central.wordcamp.test city.wordcamp.test ryan.wordcamp.test
6. Browse to https://wordcamp.test/wp-admin/network/sites.php and see the site.
7. Click on Dashboard under my new site: https://ryan.wordcamp.test/2022/wp-admin/.  See the following error:
> This page isn’t working
ryan.wordcamp.test redirected you too many times.
[Try clearing your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS
8. Clear all cookies following the instructions above.
9. Browse to https://ryan.wordcamp.test/2022/wp-admin/.  Continue to see the error
10. Browse to https://ryan.wordcamp.test/2022/. Can see the new site's public pages without issue.
 
Attached is a zipped .HAR file.
[ryan.wordcamp.test.har.zip](https://github.com/WordPress/wordcamp.org/files/8894554/ryan.wordcamp.test.har.zip)

**Expected behavior**

I would be able to see the /wp-admin interface for the Ryan 2022 WordCamp.

**Screenshots**

<img width="551" alt="image" src="https://user-images.githubusercontent.com/3489003/173447150-fa823b08-dab2-4e68-8860-6ef4cd914c4f.png">

<img width="707" alt="image" src="https://user-images.githubusercontent.com/3489003/173446849-6eaa967d-ac6d-4984-8fff-6668898ae6c3.png">

**System (please complete the following information):**

 - Device: MBP
 - OS: macOS Monterey 12.4
 - Browser Chrome
 - Version 102.0.5005.115 (Official Build) (x86_64)

**Comment by CdrMarks** [comment]
@ryelle in response to your [suggestion in Slack](https://wordpress.slack.com/archives/C08M59V3P/p1655225396546649?thread_ts=1654175618.301549&cid=C08M59V3P) to create the site without the year, I was not able to do this initially.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/3489003/174079615-5516603b-1f81-4906-8c06-6b92ba555e81.png">

I was able to comment the wp_die() line below to get around this.
```
if ( ! self::url_matches_expected_format( $parsed_url['host'], $parsed_url['path'], $wordcamp_id ) ) {
	//wp_die( 'The URL does not match the expected <code>city.wordcamp.org/year/</code> format. Please press the back button and update it.' );
}
```

While I'm unblocked on creating the new site, I still feel there is an issue to be investigated here.

**Comment by dmkjr** [comment]
@CdrMarks Seeing a very similar problem (but not utilizing WordCamp).  Can access the site locally but can not access wp_admin after setting up for proxy.

**Comment by 2ndkauboy** [comment]
This is still an ongoing issue and we really need a fix for this if we want to attract community members to contribute to Meta. We were not able to get the environment running at WCAsia 2023 Contributor Day for various reasons and this issue finally prevented us from onboarding new contributors!

**Comment by iandunn** [comment]
I think #933 may have fixed this. Do you mind testing a fresh install?

**Comment by timiwahalahti** [comment]
Tested with the new data, and worked as expected. I was able to access the admin for existing and new sites.
