### ISSUE TITLE
Tools: Update phpunit tests, github actions runner

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#788]
When running `phpunit` locally, I'm getting the following error:

`Fatal error: Access level to WordCamp\Organizer_Reminders\Tests\Test_WCOR_Mailer::setUp() must be public (as in class WP_UnitTestCase_Base) in /app/public_html/wp-content/plugins/wordcamp-organizer-reminders/tests/test-wcor-mailer.php on line 35`

I think it's related to [this update](https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/)? 

The same error does not happen in github actions, so I think maybe it's out of date here?

**Comment by iandunn** [comment]
It may also be related to 3f80ac8f4a649440e4c37ed6269dbe16c8667853. Have you run `composer update` since that commit?

**Comment by iandunn** [comment]
That post mentions updating to `public function set_up()` rather than `protected function setUp()`, which may also be the problem.

**Comment by ryelle** [comment]
> Have you run composer update since that commit?

Yes… though the docker container installs its own phpunit, and it looks like [that needs to be updated](https://github.com/WordPress/wordcamp.org/blob/941d5f9b16eb1731ab7c2bd5548d56e346b7506f/.docker/Dockerfile.phpunit#L21).
