### ISSUE TITLE
All: Sidebar spacing

### ISSUE THREAD

**Issue by melchoyce** [WordPress/wordcamp.org#79]
Sidebar setting margins don't match core Gutenberg margins, they're too big:

![image](https://user-images.githubusercontent.com/2846578/55988238-56de9b80-5c71-11e9-9e66-b0bb455e33c0.png)

These should exactly match core's margins.

**Comment by iandunn** [comment]
I think part of the reason for this is because we're using `PanelRow`, while the core blocks don't.
