### ISSUE TITLE
[Camptix] show attendee only once in case of multiple registrations

### ISSUE THREAD

**Issue by ethicaladitya** [WordPress/wordcamp.org#793]
This is an improvement feature for the Camptix attendee page. 

In case, somebody is purchasing tickets for their team, they might be using their own email initially. As a result, their Names/photo will be available on the attendees' page for the number of times they purchased tickets. 

The proposal is to display the name/photo only once if multiple tickets are purchased and selected the option to "show on the attendee page". 

Example: https://prnt.sc/70A85bSgMWer

**Comment by ryelle** [comment]
The idea to hide duplicate people has been suggested before, at https://github.com/WordPress/wordcamp.org/issues/623. Closing this as a duplicate.
