### ISSUE TITLE
Schedule: Session times are visible in UTC+/- n instead of written timezone

### ISSUE THREAD

**Issue by nielslange** [WordPress/wordcamp.org#811]
**Describe the bug**

For WordCamp Asia 2023, we're creating two pages for the schedule:
1. https://asia.wordcamp.org/2023/schedule/ → This page shows the session times in the local timezone (Bangkok = ICT)
2. https://asia.wordcamp.org/2023/schedule/livestream/ → This page shows the session times in the timezone of the viewer

When selecting `Use visitor's timezone`, I see the time displayed in the written timezone. As I'm based in Jakarta, I see `WIB`. When I unselect `Use visitor's timezone`, I see `+07`.

**To reproduce**

1. Create at least one session.
1. Create a test page and add the Schedule block to it.
2. Select the Schedule block and select the option `Use visitor's timezone`.
3. See that the session time is visible with the written timezone, e.g. `WIB`.
4. Select the Schedule block and unselect the option `Use visitor's timezone`.
5. See that the session time is visible in numeric, e.g. `+07`.

**Expected behavior**

I expect the timezone to be visible in written for showing the time both in the local and the visitor's timezone, similar to https://us.wordcamp.org/2022/schedule/ and https://us.wordcamp.org/2022/schedule/visitors-timezone/. I also ran a quick test and when temporary switching the timezone of the site from Bangkok to Los Angeles, I do see the written timezone both for the local and visitor's timezone.

I wonder if this is a problem with the Schedule block or if this problem needs to be addressed directly in core. 🤔

**Screenshots**

<img width="2874" alt="Screenshot 2022-12-25 at 10 41 37" src="https://user-images.githubusercontent.com/3323310/209456280-f8c7916c-b2d0-4ddb-82f9-a49f0b6e2c21.png">

**WordCamp**

- https://asia.wordcamp.org/2023/schedule/ → public page
- https://asia.wordcamp.org/2023/schedule/livestream/ → private page

**Comment by ryelle** [comment]
Hi @nielslange - just to be clear, the issue is that it says `+07` instead of `ICT`? or is there another issue with the timezone itself?

I believe the timezone name does come [from core](https://github.com/WordPress/gutenberg/blob/trunk/packages/date/README.md), which in turn gets the abbreviation from the standardized `tz database`. You can see in [this table](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List), the abbreviation for `Asia/Bangkok` is `+07`.

**Comment by nielslange** [comment]
> Hi @nielslange - just to be clear, the issue is that it says +07 instead of ICT? or is there another issue with the timezone itself?

Thanks for your reply, @ryelle. The problem, I meant, was indeed that it says +07 instead of ICT. 

> I believe the timezone name does come [from core](https://github.com/WordPress/gutenberg/blob/trunk/packages/date/README.md), which in turn gets the abbreviation from the standardized tz database. You can see in [this table](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List), the abbreviation for Asia/Bangkok is +07.

This explains it and with this in mind, the session times are visible as expected. Thanks for clarifying this, and sorry for missing checking the timezone settings from core in this case. 🙈
