### ISSUE TITLE
Speakers Sessions block doesn't show any data when used on a custom template when there aren't any published sessions available

### ISSUE THREAD

**Issue by thomasplevy** [WordPress/wordcamp.org#829]
**Describe the bug**

When using the speaker sessions block I noticed this issue. It's trivial to work around and isn't causing any roadblocks for me since it was easy enough to temporarily publish as session to see how the block looks / works. I wanted to report in case this wasn't already noticed by anyone else. I am pretty sure most of the block editor stuff for WordCamp.org is relatively unused.

**To reproduce**

1. Using Twenty Twenty-Three Theme
2. Create a custom Single Item: Speaker Template
3. Add the "Speaker Sessions" block to the template
4. Nothing appears in the editor, you can see the block is there in the outline and modify the settings by selecting it via the outline but there's not visible content in the editor other than the empty "frame" or border.

**Expected behavior**

I'd expect sample data to be displayed in the block, something like "Post Title" in the Post Title block, eg "This is the Title of the Presentation" and "January 1, 2023 at 10:00am" for the title. Sample data.

If I have at least one session published it looks like this isn't a problem as the data from the published session shows up inside the block.

**Screenshots**

![Screenshot from 2023-02-16 17-04-56](https://user-images.githubusercontent.com/1290739/219515686-428035a5-3621-40d1-92bd-8c939d749839.png)

**WordCamp**

If this is a problem on a specific WordCamp's site, list the site or page URL here.

https://phoenix.wordcamp.org/2023/wp-admin/site-editor.php?postType=wp_template&sidebar=%2F&postId=twentytwentythree%2F%2Fsingle-wcb_speaker

**System (please complete the following information):**

 - Device: Laptop
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: 110.0

**Comment by CdrMarks** [comment]
Hi @thomasplevy, we went through this recently with WordCamp Birmingham (our event was almost 3 weeks ago).  From my experience, we had to publish fake sessions and speakers to see how each would be included within the other.  You'll find you'll need to do the same to correctly style your schedule page.

> I am pretty sure most of the block editor stuff for WordCamp.org is relatively unused.

The #meta-worcamp team began work in 2019 [converting the WordCamp Post Types to WordCamp Blocks](https://github.com/WordPress/wordcamp.org/pulls?q=is%3Apr+is%3Aclosed+label%3A%22%5BComponent%5D+Blocks%22).  It's my understanding that Blocks are the preferred way to list Speakers and Sessions on a WordCamp site.

I wonder if there could be a way to allow logged users with the capability [`edit_others_posts`](https://wordpress.org/documentation/article/roles-and-capabilities/#edit_others_posts) to be able to see drafted WordCamp blocks when viewing a the published page.  I suggest this capability since this user should already be able to see the drafted sessions and speakers using the Administration Screens.

**Comment by thomasplevy** [comment]
> I am pretty sure most of the block editor stuff for WordCamp.org is relatively unused.

> > The #meta-worcamp team began work in 2019 [converting the WordCamp Post Types to WordCamp Blocks](https://github.com/WordPress/wordcamp.org/pulls?q=is%3Apr+is%3Aclosed+label%3A%22%5BComponent%5D+Blocks%22). It's my understanding that Blocks are the preferred way to list Speakers and Sessions on a WordCamp site.

Seems I was told some incorrect information! I was told that a lot of the FSE stuff on the WordCamp sites was first used for WCUS last year and I subsequently assumed that A) that was true and B) that it would mean that these blocks were not as battle-hardened as much of the rest of the WC functionality. In any event, my apologies for misunderstanding!

Anyway, I didn't think to publish fake sessions (I just temporarily published a real on for a few moments). I'll keep that in mind as I finish out the build.

If I have some time next week I'll probably start working on a PR for this too (probably) as long as someone else doesn't pick it up first.

**Comment by ryelle** [comment]
If there are no sessions published yet, they wouldn't show up on the frontend either, so it makes sense this would be empty — the editor should reflect the frontend. Likewise, if there was a placeholder, someone might think it would appear on the frontend.

This matches the way the core Query Loop works, for example — if you don't have any posts published, it shows you "No results found" until you publish a post.

![Screen Shot 2023-03-16 at 15 47 05](https://user-images.githubusercontent.com/541093/225736152-275b5810-1737-43b0-8fb6-8b760354f898.png)

> these blocks were not as battle-hardened as much of the rest of the WC functionality

For what it's worth, while these blocks have been around for a few years, this is probably accurate with the lower number of WordCamps we've had. WCUS was also the one of the first to use a block theme, so they probably tested more than others. That said, these blocks should be ready for everyone to use, so I appreciate any feedback or bug reports 🙂

**Comment by ryelle** [comment]
Actually, taking a second look at the screenshot, I see this in the template editor, and the other blocks here do have the placeholder content — I was thinking in the speaker post itself. Having a placeholder in this context _does_ make sense.
