### ISSUE TITLE
All: Image quality issues

### ISSUE THREAD

**Issue by melchoyce** [WordPress/wordcamp.org#83]
Scaling up gravatars or featured images should load larger sized images, instead of blowing up lower quality image.

**Comment by coreymckrill** [comment]
@melchoyce This should already be happening, except in the case when [the full-sized image is smaller than the size setting](https://github.com/WordPress/wordcamp.org/issues/36#issuecomment-480025496). What do you think the behavior should be when the image isn't big enough?

Are you seeing this issue in another context?

**Comment by melchoyce** [comment]
Let me see if I can replicate this one. I remember it looked like a smaller version of the gravatar has been scaled up to fit the larger space.

**Comment by melchoyce** [comment]
Okay, I see what it is — the avatars I saw were already low quality. If I scroll down I see some higher quality images that look totally fine. All set!
