### ISSUE TITLE
Local Docker setup fails at build step

### ISSUE THREAD

**Issue by 2ndkauboy** [WordPress/wordcamp.org#830]
**Describe the bug**

When running the `docker compose build --pull` the build process fails with this error:

```
 => CACHED [ 1/25] FROM docker.io/library/php:7.4-fpm@sha256:3ac7c8c74b2b047c7cb273469d74fc0d59b857aa44043e6ea6a0084372811d5b                                                                      0.0s
 => CANCELED [ 2/25] RUN apt-get update     && apt-get install -y         build-essential         git         less         libicu-dev         libjpeg-dev         libpng-dev         libzip-dev    2.1s
failed to solve: executor failed running [/bin/sh -c apt-get update     && apt-get install -y         nano         vim]: exit code: 127
```

**To reproduce**

1. Follow the instructions from the `README.md`
2. Run `docker compose build --pull`
3. See error

**Expected behavior**

I can't see a reason why it does not work. The compose files look good to me.

Solution: When running `docker-compose up -d` as the first docker command, it installs correctly (see screenshots).

**Screenshots**

`docker compose build --pull` fails

![wordcamp-meta-docker-build-failed](https://user-images.githubusercontent.com/1793177/219571994-91c1dff0-b7c7-43c9-9531-4a897a7c74f5.png)

`docker-compose up -d` works

![wordcamp-meta-docker-compose-up-succeeded](https://user-images.githubusercontent.com/1793177/219572014-edbba1c1-7b3c-4cd4-a510-fe11286c5ae1.png)

**System (please complete the following information):**

 - OS: Manjaro Linux 22.0.2
 - Docker: 20.10.23, build 715524332f
 - Docker-Compose: 2.15.1

**Comment by ryelle** [comment]
The base build for the mysql container has changed OS.

> The the :latest tag changed from Debian Bullseye to Oracle Linux https://github.com/docker-library/mysql/pull/867

Changing the base from `mysql:5.7` to `mysql:5.7-debian` fixes this for me.
