### ISSUE TITLE
Restore `$query_options` for `get_wordcamp_dropdown()`

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#836]
#826 fixed a frustrating memory issue, but it looks like it introduced two smaller problems:

- [ ] `$query_options` argument is no longer included in the query. Most of the the callers just used the default anyway, but [the Sponsorship Payment form](https://central.wordcamp.org/sponsorship-payment/) does pass some custom options:
    https://github.com/WordPress/wordcamp.org/blob/3d63ade7e4f9f0507a1dda6a652bf323cc24d930/public_html/wp-content/plugins/wordcamp-payments/views/sponsor-payment/main.php#L49

    https://github.com/WordPress/wordcamp.org/blob/3d63ade7e4f9f0507a1dda6a652bf323cc24d930/public_html/wp-content/plugins/wordcamp-payments/includes/sponsor-payment-stripe.php#L39

    https://github.com/WordPress/wordcamp.org/blob/3d63ade7e4f9f0507a1dda6a652bf323cc24d930/public_html/wp-content/plugins/wordcamp-payments/includes/sponsor-payment-stripe.php#L113-L126
- [ ] The default arguments from `get_wordcamps()` / `get_posts()` / `WP_Query::get_posts()` are no longer being included in the query. IMO it's fine to drop support for any of them that aren't actually changing anything, but we should restore any that do were being used.

**Comment by pkevan** [comment]
Thanks @iandunn - I'll look at fixing this in some way.

**Comment by pkevan** [comment]
Was there a reference where you discovered the bug?

**Comment by iandunn** [comment]
Thanks! There isn't an additional reference; I just noticed the problem after updating locally, so I created this.
