### ISSUE TITLE
All: Sidebar selects should be full-width

### ISSUE THREAD

**Issue by melchoyce** [WordPress/wordcamp.org#84]
Dropdowns/select boxes within settings should all be full-width. 

This is how they look in core Gutenberg:
![image](https://user-images.githubusercontent.com/2846578/55988537-1df2f680-5c72-11e9-9e5f-0c903ae18b3f.png)

**Comment by iandunn** [comment]
I think part of the reason for this is because we're using `PanelRow`, while the core blocks don't.

**Comment by iandunn** [comment]
This was fixed in 5175aff.
