### ISSUE TITLE
Retire or refresh Tagregator

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#847]
Tagregator hasn't been updated in years, and at this point I don't think it still works with any of the social media networks, because of API changes etc. We should decide if we want to retire it, or refresh it so that it works again. 

If we retire it, we should:
* Disable it on new sites, but keep it enabled on old sites so that it can continue to display posts that are already cached in the database.
* Delete the `Social Media Stream` page stub that gets created for every new site

**Comment by timiwahalahti** [comment]
I'm in favour of sunsetting the Tagregator. It's been hard to keep up-to-date with all the API changes with social media platforms already for a while, and for example, Instagram does not make it easy to query posts by hashtag.

**Comment by ryelle** [comment]
**I'm also in favor of retiring it.** I haven't seen the social media page featured on any WC site in a while (even before COVID), and like @timiwahalahti mentions, the maintenance burden is fairly high to keep up with various service APIs, not to mention users migrating to other sites (if we did bring it back we would probably want to introduce a Mastodon connection somehow?)

**Comment by CdrMarks** [comment]
No objection to retiring this.  Should a post be made on make/community?

Is there a replacement plugin that could be added in its place that is maintained and would shift the burden.

**Comment by iandunn** [comment]
I briefly looked at other plugins for the WP20 site and didn't see anything that I'd trust enough to run on the wordcamp.org/wordpress.org infrastructure. I didn't spend a lot of time, though, so I could have missed something.

**Comment by timiwahalahti** [comment]
Sounds like we should go ahead with sunsetting the plugin. Actionable items:

- [x] Disable it on new sites, but keep it enabled on old sites so that it can continue to display posts that are already cached in the database.
- [x] Disable completely on the new Events network
- [x] Delete the Social Media Stream page stub that gets created for every new site
- [x] Announce on Community Team P2
- [x] Close #373 and #589

**Comment by timiwahalahti** [comment]
Is Tagregator also network activated in production? It is in docker.

If that's the case, we'll need to write a quick script to activate it on every site after applying other changes. Or even better, detect which sites do have Tagregator posts and activate only on those sites.

**Comment by iandunn** [comment]
It's network-active on `WORDCAMP_NETWORK_ID`, and network-deactivated on `EVENTS_NETWORK_ID`. 

It's individually-activated on a few sites too:

```
> wp plugin active-on-sites tagregator

Checking sites  100% [=====================================================================] 1:09 / 1:09

Sites where tagregator is active:
+---------+----------------------------------------+
| blog_id | url                                    |
+---------+----------------------------------------+
| 206     | https://testing.wordcamp.org/2016/     |
| 294     | https://albuquerque.wordcamp.org/2013/ |
| 297     | https://baltimore.wordcamp.org/2013/   |
| 298     | https://slc.wordcamp.org/2013/         |
| 301     | https://buffalo.wordcamp.org/2013/     |
| 304     | https://tokyo.wordcamp.org/2013/       |
| 320     | https://la.wordcamp.org/2013/          |
+---------+----------------------------------------+
```

For simplicity, we could maybe just have the script activate it on sites where the `site_id = 1 && blog_id <= 1494` (or whatever the cutoff is). Many wouldn't _need_ it, but it wouldn't really hurt anything either, especially since they're not active sites and have static page caching. I don't feel strongly though.

**Comment by timiwahalahti** [comment]
> For simplicity, we could maybe just have the script activate it on sites where the site_id = 1 && blog_id <= 1494 (or whatever the cutoff is)

Fair enough, agreed. @iandunn can you coordinate that and merge #1068? The script could be one-liner:
```bash
wp site list | awk '{ if( $1 < 1494 ) print "wp plugin deactivate tagregator --url=$2"; }' | bash
```

Here is an P2 announcement draft https://make.wordpress.org/community/?p=40542&preview=1&_ppp=1b92a2f854

**Comment by iandunn** [comment]
After merging #1068, I activated the plugin individually on those sites, then network-deactivated it. It's still working at https://us.wordcamp.org/2016/social-media-stream/, https://sf.wordcamp.org/2014/social-media-stream/, etc 👍🏻 

I'll leave this open since we haven't published the announcement yet.

**Comment by timiwahalahti** [comment]
The announcement was published, thank you all! https://make.wordpress.org/community/2023/09/29/announcement-sunsetting-tagregator-plugin-on-wordcamp-org-websites/
