### ISSUE TITLE
CampTix Admin Flags dosn't save more than 1 flag

### ISSUE THREAD

**Issue by karmana** [WordPress/wordcamp.org#861]
**Describe the bug**

Admin Flags tabs in Camptix dashboard - I am not able to save more than 1 flag.  When I try to add another one they disappear and only the one in the last line is saved. I tried with comma, no comma, semicolon - none of that helps. 

**To reproduce**

1. Go to 'Tickets -> Configuration/CampTixSetup -> Admin Flags'
2. Add more than 1 flag
3. Click Save changes

**Expected behavior**

All listed flags are saved and visible on the Attendees list with possibility to choose the applicable one. 
As written in the handbook there should be an option to generate the report base on admin flags. 

**Screenshots**

Please see attached file. 
![flag-saving](https://user-images.githubusercontent.com/6827312/228770124-c837b031-c193-4904-b24b-23164b1f7426.gif)

**WordCamp**
It was noticed on WordCamp Gliwice site, but the issue was replicable on other site as well. 

**System (please complete the following information):**

 - Device: laptop
 - OS: iOS
 - Browser chrome, safari, firefox

**Comment by dd32** [comment]
The correct syntax for that field is as follows:

<img width="782" alt="Screenshot 2023-03-30 at 9 45 06 pm" src="https://user-images.githubusercontent.com/767313/228825888-474ab959-135b-4ef4-8d14-01e87bcafbc9.png">

The slug and label should be unique, so in your example it should be:
```
flag-slug: 1
flag-slug-2: 2
```

There's an error message if you don't use the `slug:label` format, such as when you insert `flag1`, that should be being triggered in this case but isn't.

**Comment by timiwahalahti** [comment]
Maybe the documentation on the format could be improved a little bit to make it clearer how to input the flags?

**Comment by karmana** [comment]
Thank you for clarification 🙈

W dniu czw., 30.03.2023 o 13:46 Dion Hulse ***@***.***>
napisał(a):
