### ISSUE TITLE
Sessions: Title repeated

### ISSUE THREAD

**Issue by melchoyce** [WordPress/wordcamp.org#87]
Session title seems to be repeated twice, and there's a weird box floating to the left of the second title?

![image](https://user-images.githubusercontent.com/2846578/55988633-61e5fb80-5c72-11e9-82a2-ea2f78d81c81.png)

**Comment by coreymckrill** [comment]
Yeah, there is some weirdness there. But I wonder if the "Registration" and "Opening Remarks" sessions should even be available to select in the block. They have the "custom" session type that is supposed to be used for things like meals and, uh, opening remarks. In the old shortcode, we specifically exclude these.

What do you think, @melchoyce ?

**Comment by melchoyce** [comment]
I don't think that's related?

**Comment by coreymckrill** [comment]
You're right, it turns out that the repeated title is actually the `alt` tag of an image that has no `src` because no featured image has been set for any of those sessions.

I started a new issue, #95, to discuss solutions.

**Comment by coreymckrill** [comment]
This is fixed with https://meta.trac.wordpress.org/changeset/8668
