### ISSUE TITLE
Content overflow issue on "category-sponsors" section.

### ISSUE THREAD

**Issue by mayurbaroliya-multidots** [WordPress/wordcamp.org#871]
**Title:-** Content overflow issue.

**Page URL:-** https://central.wordcamp.org/news/

**Issue Screenshot:-** https://share.cleanshot.com/BsJ1CkQJmrdC3HQ41BQH

**Comment by ryelle** [comment]
This was an issue in the Automattic sponsor post, I updated the content of the post and the text is wrapping correctly now.
