### ISSUE TITLE
Stop CCing support@wordcamp.org for allergy/special accommodation email

### ISSUE THREAD

**Issue by hellojuliarose** [WordPress/wordcamp.org#872]
When a WordCamp attendee registers for a WordCamp (purchases their ticket), they indicate whether they have a life threatening allergy or want to notify the organizers of any accessibility needs. If they indicate 'yes' for either of these, the WordCamp organizers receive an email, with an automatic CC to support@wordcamp.org. There's a Help Scout filter to auto-close these emails that are received in English, but we continue to receive translated notifications.

This is a request to stop CCing support@wordcamp.org on these allergy and special accommodation emails.

**Comment by naokomc** [comment]
+1 to Julia.

Currently, we are using a Help Scout workflow to suppress incoming notifications. We don't need to be notified of these messages. 

The filter selects messages that start with these & their known translations:
"An attendee who has a life-threatening allergy has registered"
"An attendee who requires special accommodations has registered"

But as new translations are added, we need to add them to the filter individually.

<img width="938" alt="Screenshot 2023-04-21 at 10 35 43" src="https://user-images.githubusercontent.com/34067/233520081-dfaf1d5e-f665-4f8b-8b79-ffd579690410.png">
