### ISSUE TITLE
Next Gen WordCamp Experiment: Accepting applications

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wordcamp.org#881]
# Purpose
This issue serves as a place to discuss technical details in supporting "[The Next Generation of WordCamps](https://make.wordpress.org/community/2023/05/08/the-next-generation-of-wordcamps/)", focusing on accepting applications.

# Features/Tasks
1. Update the [Become an Organizer](https://central.wordcamp.org/become-an-organizer/) page to lead users into the relevant form
1. Create a page with the application form 
1. Add the ability to approve/reject
## Update the [Become an Organizer](https://central.wordcamp.org/become-an-organizer/) page to lead users into the relevant form
Ideally, I think we end up with a dedicated landing page for these events, but for the interim we can probably tie into the existing WordCamp application flow to direct applicants.

**Page**
<img width="400" alt="Screenshot 2023-05-23 at 9 44 13 AM" src="https://github.com/WordPress/wordcamp.org/assets/1657336/0076a3fc-6a08-4583-bdbd-094300e8ef7d">

## Create a page with the application form 
We currently have [shortcodes](https://github.com/WordPress/wordcamp.org/tree/production/public_html/wp-content/plugins/wcpt/views/applications) that render html forms. We should probably stick with that since there isn't a Gutenberg block for this yet. We'll _lose_ the ability for admins to modify the form since fields are likely to change during the beta, but that tradeoff seems fine for now.

## Acceptance Criteria

1. A new page with a form container information from [this comment](https://github.com/WordPress/wordcamp.org/issues/881#issuecomment-1843798832)
2. Upon submission the form should create a `wordcamp` post type.

**Comment by devinmaeztri** [comment]
Proposed Application for New Event (Updated: July 24)

New Event Application

**Organizer Information**

- First Name: [Required]
- Last Name: [Required]
- Email Address: [Required]		
- [WordPress.org](http://wp.org/) Username: [Required]
- Slack Username:
- City/State/Country of Residence: [Required]	
- If you are a member of a WordPress Meetup group, please share the URL.	
- Have you attended a WordCamp or WordPress Meetup event? [Required]
- Have you organized a WordCamp or WordPress Meetup event? [Required]

**Event Information**

- Event city and country: [Required]
- Event dates: [Required]
Start date:
End date:
- In-person or online?* [Required] [Multiple Choices]
In-person
Online
Hybrid
- What best describes the event you would like to organize? [Required]
Activity focused (training, recruiting, networking, contributing, conferencing, etc)
Content topic focused (design, development, security, accessibility, SEO, agencies, marketing, end, etc)
Identity-based focused 
Job status focused (students, fresh graduates, job seekers, freelancers, business owners, etc)
WP expertise level focused (beginners, intermediate, advanced)
“Eco” WordCamp (no swag, smaller, more frequent, more sustainable)
Others (please specify)
- Number of attendees (approximately): [Required]
- If you have co-organizers, please share their WordPress.org username.
- If you have a potential venue, possibly donate, please share the URL. 
- What is the estimated cost to organize your event? [Required]
- Are you confident you can raise money from local sponsors? [Required]
- How do you see your event different from current WordPress events, such as Meetups and WordCamps? [Required]
- What are your plans to bring new attendees to your event? [Required]

**Comment by sam-suresh** [comment]
Please update the WordCamp application page:
https://central.wordcamp.org/become-an-organizer/

With this text:
### NextGen Events
Interested in shaping the future of WordPress? Apply for our new event type, the **Next Generation WordPress Event**, designed to foster innovation and collaboration in the WordPress community. [Apply here]

**Comment by StevenDufresne** [comment]
@sam-suresh Can I get the link for "Apply here"?

**Comment by devinmaeztri** [comment]
@StevenDufresne here is the link to the form. Thanks! 

https://wordpressdotorg.survey.fm/next-generation-of-wordpress-events

**Comment by iandunn** [comment]
> We currently have [shortcodes](https://github.com/WordPress/wordcamp.org/tree/production/public_html/wp-content/plugins/wcpt/views/applications) that render html forms. We should probably stick with that since there isn't a Gutenberg block for this yet.

There is a Jetpack block for forms, although it has some pretty big limitations. If we're gonna write something custom, then a dynamic block w/ no editor UI seems like about the same amount of work, but more future-proof.

**Comment by iandunn** [comment]
@sam-suresh , @devinmaeztri : The `Become an Organizer` page is just a normal WP page, so you should be able to edit it through wp-admin like any other page. Let me know if you run into any problems though.

**Comment by devinmaeztri** [comment]
I've added the blurb that @sam-suresh proposed, and the link. The page will be updated as we progress in the future. Thank you, everyone!

<img width="689" alt="Screenshot 2023-10-13 at 15 22 50" src="https://github.com/WordPress/wordcamp.org/assets/75025757/127b314d-d4ba-458c-baf0-ef65f913637a">

**Comment by StevenDufresne** [comment]
Maybe we don't need the `[]` brackets? The other organizer link doesn't include them.

**Comment by devinmaeztri** [comment]
Tweaked it as per @StevenDufresne suggestion!

<img width="623" alt="Screenshot 2023-10-16 at 13 41 44" src="https://github.com/WordPress/wordcamp.org/assets/75025757/6f6a7f40-c907-47ad-af67-eb3cd7fd438f">

**Comment by hellojuliarose** [comment]
Here are the desired questions for the new event application form.
 
## WordPress Event Organizer Application

### Organizer Information

- First Name: [Required]
- Last Name: [Required]
- Email Address: [Required]
- WordPress.org Username: [Required]
- Making WordPress Slack Username:
- City/State/Country of Residence: [Required]
- Is there a WordPress meetup in your community? If so, please share the URL:
- Have you attended a WordPress Meetup, WordCamp, or other WordPress event? [Required]
- Have you organized a WordPress event (meetup, WordCamp, or other event)? [Required]
- Please share links to your online/social media presence (Instagram, Facebook, X, LinkedIn, personal/business website, etc.):

### Event Information
- Event city and country: [Required]
- Event dates (start and end date): [Required]
- Is this event in-person or online? [Required] [Multiple Choice]
  - In-person
  - Online
  - Hybrid
- Please describe the event you would like to organize: [Required]
- What goals do you want to achieve with this event? [Required]
- Which of the following describe this event? [Select all that apply]
  - Activity focused (training, recruiting, networking, contributing, conferencing, etc.)
  - Topic focused (design, development, security, accessibility, SEO, agencies, marketing, etc.)
  - Identity focused (WordPress for Students, WordPress for Women, BlackPress, etc.)
  - Job-status focused (job seekers, freelancers, business owners, etc)
  - For a specific expertise level (beginners, intermediate, advanced users)
  - Sustainable event (no swag, small/easy to organize, low budget, etc.)
  - Other (please specify)
- Approximate number of attendees: [Required]
- If you have co-organizers, please share their WordPress.org username(s).
- _Your event URL will be: https://events.wordpress.org/[location]/[year]/[eventname]_
  - _For example: https://events.wordpress.org/narnia/2024/communityday_
  - What would you like to be the [event name] at the end of your event URL?
- If you have a potential venue (ideally donated), please share the URL and/or name.
- What is the estimated cost to organize your event? [Required]
- Are you confident you can raise money from local sponsors? Please explain. [Required]
- Is there anything else you would like to share?

**Comment by pkevan** [comment]
@hellojuliarose and I caught up on the above earlier today and agreed the following:

@hellojuliarose will go through the above fields and pull out which fields will map through to existing data in WC Central, and those which are for information (stored in original application).

@pkevan will look to transform the current WordCamp application shortcode to work with the above data on the events site, and populate within WC Central.

--
extra:
@pkevan will add a category interface to the WordCamp post type, to enable distinction within WC Central for Events and WordCamps.

**Comment by pkevan** [comment]
> and populate within WC Central.

This might be difficult due to the sites being on different multisites, but will see.

**Comment by hellojuliarose** [comment]
As @pkevan requested, here are the desired questions for the new event application form, with `a description` of how each question would populate the fields in the WordCamp Central post type. Any question not indicated below to populate a specific field is informational and simply stored in the original application.
 
## WordPress Event Organizer Application
`Note: The full text of the submitted application would populate the 'Original Application' section of the WordCamp post`
### Organizer Information

- First Name: [Required]
- Last Name: [Required]  `'First Name' + 'Last Name' together populate the 'Organizer Name' field`
- Email Address: [Required] `Populates the 'Email Address' field`
- WordPress.org Username: [Required] `Populates the 'WordPress.org Username' field`
- Making WordPress Slack Username:
- City/State/Country of Residence: [Required]
- Is there a WordPress meetup in your community? If so, please share the URL:
- Have you attended a WordPress Meetup, WordCamp, or other WordPress event? [Required]
- Have you organized a WordPress event (meetup, WordCamp, or other event)? [Required]
- Please share links to your online/social media presence (Instagram, Facebook, X, LinkedIn, personal/business website, etc.):

### Event Information
- Event city and country: [Required] `Populates the 'Location' field`
- Event date(s): [Required]
- Is this event in-person or online? [Required] [Multiple Choice]
  - In-person
  - Online `If 'Online' is selected, check the 'Virtual event only' box under 'Venue Information' (but if this is complicated, don't worry about it)`
  - Hybrid
- Please describe the event you would like to organize: [Required]
- What goals do you want to achieve with this event? [Required]
- Which of the following describe this event? [Select all that apply]
  - Activity focused (training, recruiting, networking, contributing, conferencing, etc.)
  - Topic focused (design, development, security, accessibility, SEO, agencies, marketing, etc.)
  - Identity focused (WordPress for Students, WordPress for Women, BlackPress, etc.)
  - Job-status focused (job seekers, freelancers, business owners, etc)
  - For a specific expertise level (beginners, intermediate, advanced users)
  - Sustainable event (no swag, small/easy to organize, low budget, etc.)
  - Other (please specify)
- Approximate number of attendees: [Required] `Populates the 'Number of Anticipated Attendees' box`
- If you have co-organizers, please share their name(s), email address(es) and WordPress.org username(s).
- _Your event URL will be: https://events.wordpress.org/[location]/[year]/[eventname]_
  - _For example: https://events.wordpress.org/narnia/2024/communityday_
  - What would you like to be the [event name] at the end of your event URL?
- If you have a potential venue (ideally donated), please share the URL and/or name.
- What is the estimated cost to organize your event? [Required]
- Are you confident you can raise money from local sponsors? Please explain. [Required]
- Is there anything else you would like to share?

**Comment by iandunn** [comment]
> @pkevan will add a category interface to the WordCamp post type, to enable distinction within WC Central for Events and WordCamps.

There's several places in the code that already make that distinction based on the site URL or current network ID. Is there an advantage to adding a taxonomy for it? If we do, then it'd probably be good to update the existing code so that everything is using a single source of truth.

**Comment by pkevan** [comment]
> Is there an advantage to adding a taxonomy for it

I'm only thinking about the `wordcamp` post type which exists within WordCamp Central, as a method for distinguishing and sorting through posts within the admin interface (https://central.wordcamp.org/wp-admin/edit.php?post_type=wordcamp). This would also allow the shortcodes to set this upon being received (although not a huge advantage or strictly necessary).

**Comment by pkevan** [comment]
i've spent today looking into this, and there is some added naming complications in the `wcpt` plugin, since the base class is called `Event`, which isn't ideal when attempting to name this `Events`.

@iandunn - what are you thoughts on continuing with the structure provided by the `wcpt` plugin, vs creating something self contained and potentially simpler, or am I missing some historic reason for this being structured in this way?

**Comment by iandunn** [comment]
> there is some added naming complications in the wcpt plugin, since the base class is called Event, which isn't ideal when attempting to name this Events.

Does "this" refer to the taxonomy? Or a new CPT for NextGen events? 

We considered a new CPT in #900 but decided do adapt the `wordcamp` post type instead, since they share so much functionality, and the technical differences are mostly superficial. That was implemented in #952 .

Do you want to name the new cpt/taxonomy just "Events" rather than "NextGen Events"? "Events" wouldn't seem specific enough to me. events.w.org displays all types of events, not just NextGen.

If I understand correctly, the application shortcode should just create a new `wordcamp` post with the taxonomy set to "nextgen" instead of "traditional". That seems like all that's needed to distinguish between the two types of events. Maybe I'm missing some of the things that you're planning, or have run into?

**Comment by pkevan** [comment]
> Does "this" refer to the taxonomy? Or a new CPT for NextGen events?

Apologies - should have been clearer. I'm attempting to add a new shortcode for the NextGen events, but was considering adding another method class to enable this, along with the relevant data, similar to how `wcpt-meetup` and `wcpt-wordcamp` folders are structured here: https://github.com/WordPress/wordcamp.org/tree/production/public_html/wp-content/plugins/wcpt.

The initial thoughts I had were that it would be possible to extend the current structure and code to follow convention, but it's in a MVC type framework which appears overly complex from the outset, but maybe I just need to spend a bit more time looking at it.

> If I understand correctly, the application shortcode should just create a new wordcamp post with the taxonomy set to "nextgen" instead of "traditional".

Correct - I was attempting to follow the current convention and extend it, but ran into the above complications.

**Comment by iandunn** [comment]
Ah, ok 👍🏻  `wcpt` is one of the oldest parts of the codebase, and I'm not a huge fan of large parts of it. If creating something like a self-contained `wcpt/nextgen/application.php` would be easier, that sounds fine to me 👍🏻

**Comment by pkevan** [comment]
Currently being worked on in `add-events-shortcode` branch, very much untested and WIP.

Notes (as much for myself!):
- maybe the form should be in another file, the current one for other events feels overly structured with unnecessary HTML elements
- the approach is to extend from the WordCamp form, since it's going to populate the same post type, hoping this is the easiest approach while keeping some of the rate limiting stuff and helpers in the base class.
- need to check post status and which one is most relevant in this instance
- trying to avoid anything labelled `nextgen` or `events-v2` but might need a better name than `Events` or maybe not
- ideally we would remove the numerical part from form elements `q_1079074_first_name`
- ideally the look of the form would be better but might be easier to keep it as-is on central

**Comment by iandunn** [comment]
>  remove the numerical part from form elements q_1079074_first_name

IIRC that's just legacy from when the form was hastily converted from Polldaddy, so it should be fine to remove it.

> trying to avoid anything labelled nextgen or events-v2 but might need a better name than Events or maybe not

Unfortunately I don't think we have a better name right now. I don't like "nextgen" either, since a few years from now we might have "next-nextgen" etc, but it's the official name of the program, and is already used in a lot of places in the codebase. IMO it'd be worse to introduce a 2nd name that isn't recognizable as referring to the NextGen events, and isn't consistent w/ everything else. What do you think, though?

**Comment by pkevan** [comment]
> when the form was hastily converted from Polldaddy, so it should be fine to remove it.

👍 great, it didn't appear to have significance.

> Unfortunately I don't think we have a better name right now. I don't like "nextgen" either, since a few years from now we might have "next-nextgen" etc, but it's the official name of the program, and is already used in a lot of places in the codebase. IMO it'd be worse to introduce a 2nd name that isn't recognizable as referring to the NextGen events, and isn't consistent w/ everything else. What do you think, though?

Going to the sunrise files it does just call them `Events` which was where my thought went to with it, and agree that we might end up with `next-nextgen` but largely naming things is hard 😄 .

**Comment by pkevan** [comment]
So I hit some complications in this yesterday, and seems like simplifying this won't be as easy as initially thought (🤦 !)

Should be in a place to test this later.

**Comment by iandunn** [comment]
> the sunrise files it does just call them Events which was where my thought went to with it

Ah, I see, you're right. That was a reference to the domain name `events.wordpress.org`. The root site there shows all types of events, but all of the other sites on that network are NextGen events. Yeah, naming things is hard 🤷🏻
