### ISSUE TITLE
Update WordCamp plugins to work with Pilot Sites

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#886]
Pilot sites will need to use many of the same plugins as WordCamps, and those plugins may need some updates to be compatible with post types of events. Some plugins that they _don't_ use may also need to be updated to account for both types.

This doesn't include mu-plugins, those will be done in #906

Depends on #885 

## general checks
- [x] #936
- [ ] Check is any instances of `SITE_ID_CURRENT_SITE` should to be updated to use `WORDCAMP_NETWORK_ID` or `EVENTS_NETWORK_ID`. The latter are more explicit/descriptive if we want the code to only use one of the networks.
- [ ] check all `get_sites()` because they include all networks by default. most queries will probably only want the wordcamp network, but it needs to be decided on a case by case basis because the context matters
- [ ] check all `(get|update|delete)_site_option` calls and see if we want to share that data across networks (based on context). if we do, then they can be updated to use `{action}_network_option( WORDCAMP_NETWORK_ID, ...)` instead. add a comment documenting the reason they're shared
- [ ] Test each plugin to make sure it works on both networks and doesn't have any unintended consequences

## individual plugins
- [x] `camptix` and all related plugins and mu-plugins
- [ ] `wordcamp-payments`
- [ ] `wordcamp-payments-network`
    - [ ] `wp_0_wcbd_sponsor_invoice_index` may need separate tables per network
- [ ] `wc-post-types`

There'll probably be more needed as well. We'll need to test sites to see what we actually run into.

**Comment by StevenDufresne** [comment]
- [x] Update `4-helpers-wcpt.php` to not use hardcoded `wordcamp` cpt.

https://github.com/WordPress/wordcamp.org/blob/18642950aa9b4bcd8647945290e6b86bf2210bb1/public_html/wp-content/mu-plugins/4-helpers-wcpt.php#L54


Edit: Pull Request added #937

**Comment by StevenDufresne** [comment]
I've done a first audit and have come up with this initial list. It may be missing supplemental plugins that need to be added to add functionality that wasn't immediately evident. 

- [x] Camptix
   - Related payment plugins. I wasn't sure which ones were necessary. 
- [x] WordCamp.org Post Types (this seems fine but needs #934)
      - ~~Currently requires: WordCamp Post Type. [See above](https://github.com/WordPress/wordcamp.org/issues/886#issuecomment-1624575560)~~
- [x] WordCamp Budgets (this looks like it works fine)
- [x] WordCamp.org QBO Client (couldn’t test)
- [x] WordCamp.org QBO Integration (couldn’t test)

I had a difficult time testing the QBO connection. The docker env is missing the sdk, and once I went through all the steps, the 0auth callback died and told me to contact customer service. 

Does this list make sense?

**Comment by StevenDufresne** [comment]
I've started turning on the plugins, after they are running, I'll cycle back and add them to the auto activate list represented in https://github.com/WordPress/wordcamp.org/issues/905

**Comment by StevenDufresne** [comment]
- [ ] `wc-post-types` depends on "Multi-Event Sponsors", if we turn on "Multi-Event Sponsors" for all networks, then its ok, otherwise we need to update:

https://github.com/WordPress/wordcamp.org/blob/b04355515cc64945c345e17bf75b56044aeb13ac/public_html/wp-content/plugins/wc-post-types/views/sponsors/metabox-sponsor-agreement.php#L32

We'll need it to link to the `central.wordcamp.org` network.

**Comment by StevenDufresne** [comment]
I think this issue was addressed in a series of commits to production. I'll close this. Reopen if that is incorrect.
