### ISSUE TITLE
Schedule Block isn't Printable

### ISSUE THREAD

**Issue by jakejackson1** [WordPress/wordcamp.org#889]
**Describe the bug**

If you attempt to print the WordCamp Europe schedule, none of the session or track details are displayed. All that is printed is a list of times, with no other information shown.

**To reproduce**

1. Go to https://europe.wordcamp.org/2023/schedule/
2. Go to `File -> Print` in your browser

**Expected behavior**

The full schedule of a WordCamp to be printed, including session and track information. 

**Screenshots**

**How the schedule looks in a browser**
<img width="1439" alt="Screenshot 2023-06-05 at 4 30 02 pm" src="https://github.com/WordPress/wordcamp.org/assets/2918419/26198331-a89c-44cf-8a22-781a3ddd434c">

**How the schedule looks when attempting to print**
<img width="1233" alt="Screenshot 2023-06-05 at 4 30 19 pm" src="https://github.com/WordPress/wordcamp.org/assets/2918419/c4222f42-ac03-4abe-bd2c-814c8d718291">

**WordCamp**

If this is a problem on a specific WordCamp's site, list the site or page URL here: https://europe.wordcamp.org/2023/schedule/

**System (please complete the following information):**

 - Device: Macbook M1
 - OS: iOS
 - Browser: Firefox 113.0.2, Safari 16.4, Chrome 114.0.5735.90

**Comment by timiwahalahti** [comment]
Additional info, first noticed by [Patricia BT](https://profiles.wordpress.org/patricia70/), looks like starred sessions are visible on the print.

**Comment by vagelisp** [comment]
Hello @jakejackson1, thanks for reporting this.
The schedule on WCEU23 website should be printable now.

**Comment by jakejackson1** [comment]
@vagelisp that was quick! Thanks everyone.
