### ISSUE TITLE
Sessions: "Visit session page" should appear below session meta

### ISSUE THREAD

**Issue by melchoyce** [WordPress/wordcamp.org#90]
Instead of above it.

**Comment by coreymckrill** [comment]
Would this also be the case if the link said "Read more" instead of "Visit session page"? (If the content was set to Excerpt instead of Full)

**Comment by melchoyce** [comment]
Nope — if we used "Read More," I'd expect it to show up inline like this:

![image](https://user-images.githubusercontent.com/2846578/56151290-ee4c3300-5f7e-11e9-9891-770127f6d04b.png)

Since that directly references an excerpt.

**Comment by coreymckrill** [comment]
Tying this in with the conversation [here](https://github.com/WordPress/wordcamp.org/issues/62#issuecomment-482378488):

I added a "Read more" link to excerpts in CampSite 2017:
https://meta.trac.wordpress.org/changeset/8646

The Twenty Twelve and Twenty Nineteen themes will just remain w/out those excerpt links, at least until someone complains.

Then I removed the redundant "Read more" links and settings for excerpts in all the blocks, _and_ moved the "View page" links beneath the meta information.
https://meta.trac.wordpress.org/changeset/8647

I think this one's done ✅
