### ISSUE TITLE
Make navigating networks easy/intuitive

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#902]
In #885 we talked about creating a new `events.wordpress.org` network for Pilot Events. That'll turn the wordcamp.org Multisite into multi-_network_ Multisite.

We may want some things that will make that easier for folks to understand and navigate. I can imagine someone going to `wp-admin/network/sites.php` and being confused that they only see WordCamp sites, or vice versa.

A menu bar item that links between the two might help. If you're on `events.wordpress.org`, it would link to `central.wordpress.org` and vice-versa. There's probably other things that will become more obvious once folks start using it.

**Comment by StevenDufresne** [comment]
> folks to understand and navigate

Which group of users will this affect?

**Comment by iandunn** [comment]
I was thinking about folks who have access to `wp-admin` both networks, so mostly the Community Team contributors who help manage the site and mentor WordCamps.

**Comment by StevenDufresne** [comment]
Based on where we landed, `central.wordpress.org` being the pivot, do you still think this is important?

**Comment by iandunn** [comment]
It could be useful, but doesn't seem essential to me. it may be best to see how folks experience the site and if this is a actual problem for them. I'll close so we can focus on more actionable things, and we can always reopen if we get feedback.
