### ISSUE TITLE
Life-threatening changed to Severe in allergy question for Camptix

### ISSUE THREAD

**Issue by sunsand187** [WordPress/wordcamp.org#904]
Feature requests should be made on the Make Community P2, to ensure everyone can contribute to new ideas. Please follow this process for new features: https://make.wordpress.org/community/feature-requests-for-community-sites/

If you have a problem, go back and select the Bug Report option.

---------------

If you've already made your feature proposal on the p2, you can summarize it here and make sure to include a link.

https://wordpress.slack.com/archives/G01EQQ51KLP/p1686805949390949

Change "life-threatening" to "severe" in referencing allergies for WC tickets. 

public function camptix_init() {
		$this->label = __( 'Life-threatening allergy', 'wordcamporg' );

		$this->question = __( 'Do you have a life-threatening allergy that would affect your experience at WordCamp?', 'wordcamporg' )

**Comment by ryelle** [comment]
@sunsand187 That link isn't working for me, is it a private group? Just for reference, could you copy out the discussion here?

**Comment by sunsand187** [comment]
Can I make a proposal? CampTix asks about Life threatening allergies not allergies so it could make people with allergies feel like they need to just bring food when they might be easily accommodated...

humans with food allergies read that and see "anaphylactic" not "I can't get out of bed for a week with gut issues"
Better wording: Do you have any food allergies that would affect the ability to consume the provided meals and snacks at WordCamp?

Cause for most allergies are life-altering not life-threatening outside of peanuts, shellfish, and some other rare anaphylactic reactions.
My sister @ Sam Daugherty is the reason I brought this up TBH... she found it confusing and felt like her allergies were less than 


Naoko Takano
Good point! @sunsand187
One feedback I have from translator’s standpoint is “affect” can be a vague word to put in another language, so some more clarity would be nice (I know that’s in the original language, but removing “life-threatening” changes things a bit). Maybe something simple like this could work?
> Do you have any severe food allergies?
Would you like to open a ticket on WordCamp.org <http://wordcamp.org/> website GitHub project?
https://github.com/WordPress/wordcamp.org/issues/new/choose
You can reference this link <https://github.com/WordPress/wordcamp.org/blob/b9a84f6cee90b69f41bbd19522862e9e6c988d7e/public_html/wp-content/mu-plugins/camptix-tweaks/addons/allergy.php#L13> for the source of the text.

**Comment by timiwahalahti** [comment]
Based on [Slack discussion](https://wordpress.slack.com/archives/C037W5S7X/p1689760733110009) team agrees to go ahead with this.

**Comment by timiwahalahti** [comment]
The PR has been made to change this.

I think it's also safe to update the wording on the Community Team handbook, so I did that. Note that code links to the URL https://make.wordpress.org/community/handbook/wordcamp-organizer/planning-details/selling-tickets/life-threatening-allergies/ so the slug of that page should be kept the same (it is used also elsewhere).
