### ISSUE TITLE
Update Docker env config for Events network

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#910]
#907 added some basic config for the Docker env, but more is needed to fully support and provision the new Events network.

- [x] Basic `wp-config.php` updates
- [x] Basic `nginx.conf` updates
- [x] Add nginx rule for `/xmlrpc.php`, something like `rewrite "/[\w-]+/\d{4}/[\w-]+/xmlrpc\.php" /xmlrpc.php last;`
- [x] Add nginx rule for uploaded files, something like `rewrite "/[\w-]+/\d{4}/[\w-]+/files/(.+)$" /wp-includes/ms-files.php?file=$1 last;`
- [x] Create new root site and example event sites. Update `EVENTS_ROOT_BLOG_ID` if it doesn't already match.
- [ ] Comprehensive testing

Other changes may be needed as well.

**Comment by iandunn** [comment]
I merged #912, which added the parts that I needed to do in order to work on #907. More changes and testing will be needed to make this issue complete, though.

**Comment by iandunn** [comment]
I moved the task for updating the database to https://github.com/WordPress/wordcamp.org/issues/668, because that's related and it's messy to try and have competing diffs for the SQL export

**Comment by timiwahalahti** [comment]
I tested the Events network, and it seems to work as expected. I will leave this open, in case someone else wants to do more testing.

**Comment by StevenDufresne** [comment]
I'll close this for now, it has been working for me and @timiwahalahti also gave it a test. 

We can reopen if we come up with a clearer definition of "Comprehensive testing", otherwise things could just be logged as bugs in the issue tracker as normal.
