### ISSUE TITLE
New event debrief survey for organizers

### ISSUE THREAD

**Issue by peiraisotta** [WordPress/wordcamp.org#930]
Hello team! As a part of the New event infrastructure, we'll also need a new debrief form/survey for organziers to complete once the event is concluded. It would be similar to the WordCamp debrief, and organizers should receive an automated reminder about it.

Below you can find the text of the survey. If needed, [you can find here the Google form](https://forms.gle/ERwS5bjH81yTMGkB9) that we'll be using until the debrief on central is created. Questions with the symbol * are mandatory questions.

Please let me know if you need any more info on my part, thanks a lot!

·····································
[Title] Organizer Survey (event debrief)

If you recently organized a WordPress event, please take the survey below to share your feedback about your experience.

Start Survey

What event did you organize? *

General Information

How many tickets were sold? *

How many people actually attended? *

How many people attended your event as Attendees? *

How many people attended your event as Organizers? *

How many people attended your event as Volunteers? *

How many people attended your event as Organizers? *

How many people attended your event as Speakers/Trainers/Facilitators? *

Did you livestream your event? *
Nope!
Yep!

If you live streamed your event, what service did you use, and how many viewers did you have?

Have the videos and slides been uploaded for wordpress.tv yet? *
Yes, they have all been uploaded
Some, but not all, we are still working on it
We have not started uploading videos and slides yet

If they haven't been uploaded yet, is there something specific holding up the process?

How was the Code of Conduct publicized at your event? (check all that apply)*
It was on the website, linked from main navigation
It was on the website, linked from other pages
It was mentioned in pre-event emails
It was mentioned in opening remarks
It was printed on individual collateral (like name badges, programs, etc)
It was printed on signs
Other:

Were there any reports of Code of Conduct violations at your event? *

Budget

How did you wind up in terms of budget? *
There is a surplus
We broke even
We lost money

If there was a budget surplus/deficit, what was the amount?

Have all of your vendors been paid? *
Yes, all of them
No, we still have more payments that we need to request

If there are outstanding payments, what's the holdup?

Which expenses were unanticipated, or cost more than you expected? *

Have payments been received from all your sponsors? *
Yes, all of them
No, but we have invoiced them all
No, we still have to invoice some late-addition sponsors

If you are still waiting for any sponsor payments, which sponsors are they?

Did you receive in-kind donations or contributions? If yes, what are they?*

Opinions

What do you think went really well at your event? *

What could have gone better at your event? * (This could include logistical things like printing name badges late, bigger things like overall schedule planning, or anything else that you've learned from this year.)

Would you do the event again?*
Yes
No

If not, why?

What were the goals that you wanted to reach by organizing this event?*

Have you reached those goals?*
Yes
No

If not, what blocked you from reaching them - What can be improved for the next time?

After completing the event, do you consider your event to be (check all that apply): *
Doable (less human and financial resources)
Replicable (by other communities in different parts of the world)
Scalable (can be changed in size or scale)
Desirable (seen as useful, important or necessary by the community)

Did you have enough support from WordCamp Central?*
Yes
No

If there were things that made planning this event harder or easier, let us know!

Have you written a recap post of the event yet? If so, please provide the URL so we can reblog it on the WordCamp Central website. *

Is there anything else we should know about how your event went?

Finish Survey

[Thank you message]: Thank you so much for sharing your feedback and providing an excellent experience to your community, we are very grateful for your contribution to the WordPress open source project!

**Comment by iandunn** [comment]
Hi @peiraisotta 👋🏻  

* What do you think about using a Jetpack form for this, similar to #929 ? That'd let you view the answers in `wp-admin` and also export to CSV.
    * Are there any particular requirements beyond those?
    * Are there any features of survey.fm or Google forms that you'd like to preserve?

* How should we determine who are the organizers? We'll need to do that in order to email them. We could assume that anyone added to `wp-admin` is an organizer, but that's bound to have false-positives and false-negatives. The list of organizers in in the WordCamp post type is probably more accurate, but maybe not complete, especially if they haven't filled it in, or there are multiple people serving in some of the roles.

**Comment by iandunn** [comment]
Is this intended to be sent to _all_ organizers for an event, or only the _lead_ organizer? if it's just the lead, then we've already got that in the WordCamp post type, so you can ignore my question about emailing them.

If it will be sent to all co-organizers, then I have some extra thoughts. These are more personal opinion than technical implementation, though. I'm happy to go with what you've requested if you'd prefer.

* I think it might be unnecessary to ask many of these questions, like `How many tickets were sold?`, if the event used events.wordpress.org and the tools available there. We should already have the data in those cases. Not everyone will be in that situation, though 🤔  We could add a response that says something like, "This data is already available in the events.wordpress.org website". Or we could have a separate form for events that didn't use the site, and it would include the extra questions.

* I think it may be worth considering whether or not most of the questions need to be required from everyone completing the survey. In many cases, like `Have payments been received from all your sponsors?`, I'm guessing only the lead organizer or budget wrangler would know the answer without asking another organizer for it. If folks don't know the answer to something unrelated to them, and aren't allowed to skip the question, they may enter false data or quit before submitting the survey. If you'd like to keep them required, we could add a response for "I don't know".

**Comment by timiwahalahti** [comment]
> How should we determine who are the organizers? We'll need to do that in order to email them. We could assume that anyone added to wp-admin is an organizer [...]. The list of organizers in in the WordCamp post type is probably more accurate

Do you mean Central's Tracker with WordCamp post type or `wcb_organizer` in WordCamp sites?

Not many teams fill the Tracker with organisers, and there are no fields for all organisers since Central is interested in just some specific roles. Organisers widely use the latter and have WordPress.org usernames filled in for avatars, so we should be able to get their emails with that as well, right? Also, that list is most typically complete with all organisers, so there's a smaller chance for false-negatives and only a small possibility for false-positives.

**Comment by iandunn** [comment]
Ah, yeah, that sounds like a better idea 👍🏻

**Comment by peiraisotta** [comment]
Hi!

> Is this intended to be sent to all organizers for an event, or only the lead organizer?

Only the lead.

**Comment by devinmaeztri** [comment]
Hello @iandunn and @StevenDufresne!

> Are there any particular requirements beyond those?

The goal is for WC Central (Program Supporters/Managers) to have access to the feedback easily and download them easily too, without relying on Organizers to share the feedback with us or move to a different platform.

> Are there any features of survey.fm or Google forms that you'd like to preserve?

I don't think so, except that we want the same function regarding required fields and ability to choose multiple answers, for example. 

> How should we determine who are the organizers?

The Organizer Survey is only for the Lead Organizer of the event. It is built upon the WordCamp debrief with a little modification. We built the form on GForm thinking that the form is subject to improvements, so it was to make it easy for us to make changes. We were also making some questions required as the Form is sent to the first few events that didn't use WC site such as Sevilla or use WC site such as Leipzig and Bengaluru, but we are not sure if we can get the data from the current WC site.

Thus, please let us know the questions that we can remove, as we can get the data from the WC site. 
With Rome and Japan move forward with the new URL, and if we can get both the Organizer Survey and Attendee Satisfaction Survey embedded in the new site. I don't think there will be new events using a different platform. 
Although, at the moment, Rome and Japan are using different registration systems/ticketing. Japan is using Meetup.com and Rome is using GForm. We will reconfirm with them.

Also, similar to Attendees Satisfaction Survey, we hope this survey is sent by default after the Camp completes.

**Comment by outdoor2kode** [comment]
Hey @devinmaeztri,

Can I get an email copy like the one [here](https://github.com/WordPress/wordcamp.org/issues/929#issuecomment-1678760930) for this ticket? Thanks!

**Comment by devinmaeztri** [comment]
Hello @renintw! Apologies for the delayed response. Here is the email copy for the Organizer Survey. 

NextGen Event Organizer Survey Email


Howdy [ORGANIZER EMAIL],

Congratulations on completing [NEXTGEN EVENT NAME]! We hope you had a great time, and that you'll soon get some well-deserved rest.

We'd love to hear how you feel the event went. What were your proudest moments and your greatest disappointments? We've created an Organizer Survey, so we can get all the details of how things went with your event. **Please fill it out this form within 10 days**: [LINK TO THE SURVEY].

**Event Budget**
Please update your working budget on your event dashboard. If you ran your money outside of WordPress Community Support, PBC, please also balance your budget spreadsheet and prepare your Transparency Report. If there are any issues, please reach out to us at support@wordcamp.org to schedule a budget close-out meeting. Please complete these steps within the next two weeks.

**Event Recording (if any)**
If you haven't yet done so, please review the submission guidelines before beginning to edit your videos (or before your videographers starts editing): http://blog.wordpress.tv/submission-guidelines/

To submit your video for publication to WordPress.tv, just upload them at this page: http://wordpress.tv/submit-video/

Our intrepid team of video moderators will review the videos and schedule them for publication. If your content is in a language other than English, please see if you can recruit someone from your community to join the WordPress TV moderators' team and review your videos: http://wordpress.tv/apply-to-be-a-wordpress-tv-moderator/

**Event Recap**
Finally, if you've published a recap on your site, please let us know, so we can reblog it on the WordCamp Central blog.

Thanks again for all you've done to grow the WordPress community in [EVENT LOCATION]!

Best wishes,
Your friendly WordCamp Central crew
