### ISSUE TITLE
Header image in the 'Attendee Visa Letter' missing

### ISSUE THREAD

**Issue by yoga1103** [WordPress/wordcamp.org#940]
**Header Image in the PDF 'Attendee Visa Letter' missing**

As the title says: The header image/content in the 'Attendee VIsa Letter' (in PDF format) is missing.

**To reproduce**

1. Go to 'WordCamp Docs' --> 'Attendee Visa Letter'
2. Click on 'Next'
3. Fill in the details
3. Download the letter in PDF format

**Expected behavior**

An invitation letter with a header 

**Screenshots**

[If applicable, add screenshots to help explain your problem.](https://photos.app.goo.gl/oA2RVSAz6zvWjAcg7)

**WordCamp**

bengaluru.wordcamp.org/2023/

**System (please complete the following information):**

 - Device: Laptop
 - OS: Ubuntu 23.04
 - Browser Firefox
 - Version 114.0.1

**Security Issues**

To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by ryelle** [comment]
Thanks for the report! It's already being tracked in #786, so you can follow that issue to track the fix.
