### ISSUE TITLE
Blocks: No featured image has been set: should we add a placeholder?

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#95]
In #87 we discovered that for blocks using the `FeaturedImage` component (currently Sessions and Sponsors), when no featured image is set, it still renders an `img` tag with an empty `src` attribute. This is not ideal behavior. Two better options would be:

* Render a placeholder instead. Either a generic image or a `div` container with an icon or some kind of background. Perhaps this could be defined outside of the component so different placeholders could be used in different contexts.
* Render nothing.

In the case of Sessions, it seems like we should render a placeholder so that in a grid layout there is consistency in having some kind of image for each session. But maybe we should also have a setting where the placeholder could be turned off? Or maybe we just let organizers hide the placeholder with CSS if they want?

**Comment by coreymckrill** [comment]
@melchoyce Any thoughts on this? If we were to have a placeholder for Session or Sponsor posts that don't have a featured image set, what would you want it to look like?

**Comment by melchoyce** [comment]
I think we shouldn't have a placeholder — especially for sessions, including a featured image is pretty rare (we only add them to Boston for social sharing), and so adding in a placeholder feels more unexpected to me than having a wonky grid.

**Comment by coreymckrill** [comment]
Works for me!
