### ISSUE TITLE
WordPress Event/WordCamp Vendor Payment dashboard & Reimbursement dashboard Enhancements

### ISSUE THREAD

**Issue by harmonyromo** [WordPress/wordcamp.org#977]
A few additional updates were shared that I think make sense and would not be super complicated additions:

- [x] For payment types, either only showing `pay by check` or `pay by ACH` when supported country (USA) is selected, or just add a note to indicate that those payment types are only available in the USA.

**Comment by iandunn** [comment]
@harmonyromo , I would guess that all of these should apply to traditional WordCamps too, is that correct?

**Comment by harmonyromo** [comment]
@iandunn Correct. These would be related to both event types.

**Comment by renintw** [comment]
Hey @Harmony 👋  I have a few questions the request items:

1. 
> For payment types, either only showing pay by check or pay by ACH when supported country (USA) is selected, or just add a note to indicate that those payment types are only available in the USA.

I saw that in `Add New Reimbursement Request` and `Add Vendor Payment`, there is `Payment Method` field, is this the right field you're referring to? And when it comes to only `only showing pay by check or pay by ACH when supported country (USA) is selected`, I guess you are suggesting removing `Direct Deposit` and `Check` when `Beneficiary’s Bank Country` is not `the US`, is that right?

I noticed in the `Add New Reimbursement Request` and '`dd Vendor Payment` sections, there's a `Payment Method` field. Is that the one you're referring to? Also, when you mention showing `pay by check` or `pay by ACH` only for supported countries like the USA, are you suggesting we should hide the `Direct Deposit` and `Check` options if the `Beneficiary’s Bank Country` isn't set to `the US`?

**Add New Reimbursement Request**
<img width="1416" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/a56261fb-57c6-49d9-8921-da1447415317">

**Add New Vendor Payment**
<img width="954" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/3f545682-e344-4a94-b745-f1c7a2856fce">

2. 
> Add an other payment type for PayPal or other transfer service

Is this implementation something you were picturing? By adding a text input `Other`
<img width="800" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/09515735-efcb-452f-816a-481ccd24edec">

And what format are you imagining for the detailed information when users choose`Other`?
For instance, if `Other` is selected and `PayPal (or another transfer service)` is entered, then we should display the `Payment Detail` input text area. 
<img width="847" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/5833e899-b858-49f5-b5d8-00fe60138d92">

3. 
> show a warning at the top of the page of the vendor payment requests/reimbursements/sponsor invoices to those events who are running the funds via their own account, that those tools are for those ones running the funds via WC Central

Do you have a specific field or value that indicates whether an event is managing its own funds? Could you point me to where I can find or access that information?

Regarding the `warning at the top of the page` suggestion, are you thinking of a distinct warning block, perhaps with a red background, or just some text added beneath the tool's name?
<img width="1152" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/a5b0bede-def2-4b92-bca0-210348e7bd35">


4.
> Add an error message when submitting sponsor invoices with non-ASCII symbols like &,`, etc. so organizers know that they can’t add any of those symbols to any single field of a sponsor invoice or payment request

Does this mean you'd like to check all `amounts` fields` in `Sponsor Invoices, Reimbursements, and Vendor Payments` to ensure no non-ASCII symbols are entered? Or is it just the `amount` fields in `Sponsor Invoices`? Or, are we not allowing non-ASCII symbols in `any field at all`?

<img width="853" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/01f96f4f-93b3-49fc-b1d3-36eaf5402457">

**Comment by outdoor2kode** [comment]
Hey @Harmony 👋  I have a few questions the request items:

1. 
> For payment types, either only showing pay by check or pay by ACH when supported country (USA) is selected, or just add a note to indicate that those payment types are only available in the USA.

I noticed in the `Add New Reimbursement Request` and `Add Vendor Payment` sections, there's a `Payment Method` field. Is that the one you're referring to? Also, when you mention showing `pay by check` or `pay by ACH` only for supported countries like the USA, are you suggesting we should hide the `Direct Deposit` and `Check` options if the `Beneficiary’s Bank Country` isn't set to `the US`?

**Add New Reimbursement Request**
<img width="1416" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/a56261fb-57c6-49d9-8921-da1447415317">

**Add New Vendor Payment**
<img width="954" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/3f545682-e344-4a94-b745-f1c7a2856fce">

2. 
> Add an other payment type for PayPal or other transfer service

Is this implementation something you were picturing? By adding a text input `Other`
<img width="800" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/09515735-efcb-452f-816a-481ccd24edec">

And what format are you imagining for the detailed information when users choose`Other`?
For instance, if `Other` is selected and `PayPal (or another transfer service)` is entered, then we should display the `Payment Detail` input text area. 
<img width="847" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/5833e899-b858-49f5-b5d8-00fe60138d92">

Also noticed that there's already a field in `Vendor Payment` providing a similar function, should we keep the field or remove it?
<img width="841" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/e4a5adec-28cb-46b5-9fd7-7d4e8ba5adbc">

3. 
> show a warning at the top of the page of the vendor payment requests/reimbursements/sponsor invoices to those events who are running the funds via their own account, that those tools are for those ones running the funds via WC Central

Do you have a specific field or value that indicates whether an event is managing its own funds? Could you point me to where I can find or access that information?

Regarding the `warning at the top of the page` suggestion, are you thinking of a distinct warning block, perhaps with a red background, or just some text added beneath the tool's name?
<img width="1152" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/a5b0bede-def2-4b92-bca0-210348e7bd35">


4.
> Add an error message when submitting sponsor invoices with non-ASCII symbols like &,`, etc. so organizers know that they can’t add any of those symbols to any single field of a sponsor invoice or payment request

Does this mean you'd like to check all `amounts` fields in `Sponsor Invoices, Reimbursements, and Vendor Payments` to ensure no non-ASCII symbols are entered? Or is it just the `amount` fields in `Sponsor Invoices`? Or, are we not allowing non-ASCII symbols in `any field at all` among the three tools?

<img width="853" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/01f96f4f-93b3-49fc-b1d3-36eaf5402457">

cc @iandunn

**Comment by harmonyromo** [comment]
Hello Ren-

Happy to offer thoughts here!

1. I saw that in Add New Reimbursement Request and Add Vendor Payment,
there is Payment Method field, is this the right field you're referring to?
And when it comes to only only showing pay by check or pay by ACH when
supported country (USA) is selected, I guess you are suggesting removing Direct
Deposit and Check when Beneficiary’s Bank Country is not the US, is that
right?

I noticed in the Add New Reimbursement Request and 'dd Vendor Payment sections,
there's a Payment Method field. Is that the one you're referring to? Also,
when you mention showing pay by check or pay by ACH only for supported
countries like the USA, are you suggesting we should hide the Direct Deposit
 and Check options if the Beneficiary’s Bank Country isn't set to the US?

That would be ideal, but it sounds complicated. Also, I worry about the
payment method not showing up until the USA is selected as the origin
country. That might be confusing also. I would think people would choose a
payment method prior to completing the info below. Is there a way to
potentially add some caveat statements like **ACH and CHECK are only
available in the US. I guess the other option would be to set the system to
indicate an error if a country other than the US is chosen and the
individual has selected ACH or check.

2. The proposed option is exactly what I pictured. Yes!

3. show a warning at the top of the page of the vendor payment
requests/reimbursements/sponsor invoices to those events who are running
the funds via their own account, that those tools are for those ones
running the funds via WC Central

Do you have a specific field or value that indicates whether an event is
managing its own funds? Could you point me to where I can find or access
that information?

There is a check box that is in the WordCamp Central Dashboard of a
WordCamp that says "Running Funds through WPCS", and this is either checked
or not. That is the only indicator that a WordCamp is running funds
locally. It's at the very bottom of this section. I think just having a
statement under the name of the tool as you propose works just fine.
[image: image.png]

4. Add an error message when submitting sponsor invoices with non-ASCII
symbols like &,`, etc. so organizers know that they can’t add any of those
symbols to any single field of a sponsor invoice or payment request

Does this mean you'd like to check all amounts fieldsinSponsor Invoices,
Reimbursements, and Vendor Paymentsto ensure no non-ASCII symbols are
entered? Or is it just theamountfields inSponsor Invoices? Or, are we not
allowing non-ASCII symbols in any field at all`?

So, this is particularly important when it comes to bank and beneficiary
name and address. That is generally where I get errors. If there is a way
to scan those particular input sections for the non-ASCII symbols, that
would be fabulous. The cells below are generally where the issues are.
[image: image.png]

Kind Regards-

Harmony Romo
Automattic | WordPress

**Comment by outdoor2kode** [comment]
Following a further talk with @harmonyromo, we've decided to introduce a `Country for payment receipt:` field ahead of the other fields and tweak the user flow, as demonstrated in the video.

https://github.com/WordPress/wordcamp.org/assets/18050944/06f45cc3-b0c4-4490-9585-23345d0248d3

**Comment by outdoor2kode** [comment]
Note: Three items listed in the issue description were separated into #1023.
