### ISSUE TITLE
Separate access to the Meetup and WordCamp trackers for Community Team contributors

### ISSUE THREAD

**Issue by catederosia** [WordPress/wordcamp.org#995]
Right now, new Community Team contributors can only be given access to both the Meetup and WordCamp tracker. We would like access divided so some contributors can get access to the Meetup Tracker with the ability to read the notes and others can be give access to the WordCamp Tracker with the ability to read the notes.

A summary of previous conversations about this:
- I asked if it could be done, and it was answered with a Yes.
- We then discussed if we would want access to all four options: Meetup with and without notes, WordCamp with and without notes
- We realized we just needed Meetup tracker with notes and WordCamp tracker with notes
- Finally, we discussed timeline and priority, as well as the need to make this a GitHub issue.

**Comment by catederosia** [comment]
We have some elements of our Q3 project that are impacted by this change. So that we can simply plan effectively and work within your timeline, is there an estimate you can share with me as to when this might be done?

**Comment by StevenDufresne** [comment]
What impact will this have on permissions management? Will will be needing to update permissions more frequently than we do now? I think this is currently managed through developer code commits, is that right?

**Comment by iandunn** [comment]
> this is currently managed through developer code commits, is that right?

That's correct

**Comment by catederosia** [comment]
@StevenDufresne Apologies for the delay. I was out sick all last week and am just catching up.

> What impact will this have on permissions management?
Right now Program Supporters (deputies) are give access to both trackers (Meetup and WordCamp) at once.

Splitting it means Program Supporters (deputies) would need to be given access to both. And Event Supporters (mentors) would need to be given access to just the Meetup tracker.

For us, it allows contributors additional impactful ways to contribute with fewer barriers while keeping the more sensitive information in the WordCamp tracker private/more contained.

> Will will be needing to update permissions more frequently than we do now?
Initially, yes. Not only do we have a new group of contributors that were not getting tracker access before, but were also transitioning a batch of supporters from one area of contribution to another.

In the long run: Not really. After this initial flurry, onboarding will slow WAY down and contributors do not move quickly from Event Supporter to Program Supporter, the next step with new permissions.

**Comment by catederosia** [comment]
As I plan out the rest of the year, does anyone know when this might be done? It will impact the choices we make around onboarding new supporters. Thanks in advance.

**Comment by iandunn** [comment]
This is done now, thanks for your patience!

I gave the new `meetup wrangler` role to everyone who currently has the `wordcamp wrangler` role, so that no one will lose their access. If you'd like any changes to who can access what, though, just let me know.

**Comment by catederosia** [comment]
Thank you, @iandunn (and @StevenDufresne)! Particularly for helping kindly navigate me through my first solo GitHub ticket.
